### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by p4rcomx** [Ekultek/Zeus-Scanner#1]
> $ sudo python zeus.py 
Traceback (most recent call last):
  File "zeus.py", line 141, in <module>
    setup(verbose=opt.runInVerbose)
  File "/Users/break/tools/Zeus-Scanner/lib/settings.py", line 222, in setup
    bin.unzip_gecko.main(verbose=verbose)
  File "/Users/break/tools/Zeus-Scanner/bin/unzip_gecko.py", line 78, in main
    if check_if_run():
  File "/Users/break/tools/Zeus-Scanner/bin/unzip_gecko.py", line 14, in check_if_run
    with open(file_check.format(os.getcwd())) as exc:
IOError: [Errno 2] No such file or directory: '/Users/break/tools/Zeus-Scanner/bin/executed.txt'

====================
installation issue

**Comment by Ekultek** [comment]
Do the following: `sudo touch /Users/break/tools/Zeus-Scanner/bin/executed.txt && echo "FALSE" > /Users/break/tools/Zeus-Scanner/bin/executed.txt`.

Seems that the file does not exist, will retractor and fix, let you know when it's done. For now that work around should work

**Comment by Ekultek** [comment]
fixed via https://github.com/Ekultek/Zeus-Scanner/commit/d0a0a8b9c5f65717755c5da7e0cce69640385834
