### ISSUE TITLE
TypeError: 'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#100]
Zeus version:
`1.0.47.8f84`

Firefox version:
`Version: (56.0)`

Geckodriver version:
geckodriver-v0.19.0-linux64.tar.gz

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/nmap_scan/__init__.py", line 123, in perform_port_scan
    data.show_open_ports(json_data)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/nmap_scan/__init__.py", line 75, in show_open_ports
    for port in oports[0[0[0]]]:
TypeError: 'int' object has no attribute '__getitem__'
````

Running details:
`Linux-4.10.0-35-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:php?id=10 -p`

Log file info:
```2017-10-14 14:38:16,358;zeus-log;INFO;log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-149.log'...
2017-10-14 14:38:16,358;zeus-log;INFO;using default search engine...
2017-10-14 14:38:16,359;zeus-log;INFO;starting dork scan with query 'inurl:php?id=10'...
2017-10-14 14:38:16,359;zeus-log;INFO;attempting to gather query URL...
2017-10-14 14:38:16,648;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-14 14:38:16,649;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-14 14:38:31,971;zeus-log;INFO;browser will open shortly...
2017-10-14 14:38:34,315;zeus-log;INFO;searching 'http://google.com' using query 'inurl:php?id=10'...
2017-10-14 14:38:37,518;zeus-log;INFO;closing the browser and continuing process..
2017-10-14 14:38:37,613;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-14 14:38:37,613;zeus-log;INFO;no proxy configuration detected...
2017-10-14 14:38:38,138;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.47.8f84)::Python->v2.7'...
2017-10-14 14:38:38,172;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-14 14:38:38,173;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-14 14:38:38,177;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-14 14:38:38,178;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-14 14:38:38,179;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-14 14:38:38,179;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-14 14:38:38,179;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-14 14:38:38,180;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-14 14:38:38,180;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-14 14:38:38,181;zeus-log;INFO;found a total of 10 URL's with a GET parameter...
2017-10-14 14:38:38,222;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/url-log/url-log-54.log'...
2017-10-14 14:38:40,174;zeus-log;INFO;creating arguments for nmap...
2017-10-14 14:38:40,174;zeus-log;INFO;attempting to find IP address for hostname 'www.marylandfarmlink.com'...
2017-10-14 14:38:40,246;zeus-log;INFO;found IP address for given URL -> '63.135.117.87'...
2017-10-14 14:38:40,247;zeus-log;INFO;starting port scan on IP address '63.135.117.87'...
2017-10-14 14:38:51,547;zeus-log;INFO;finding data for IP '63.135.117.87'...
2017-10-14 14:38:51,548;zeus-log;ERROR;[7;31;31mran into exception ''int' object has no attribute '__getitem__'', cannot continue quitting...
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/nmap_scan/__init__.py", line 123, in perform_port_scan
    data.show_open_ports(json_data)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/nmap_scan/__init__.py", line 75, in show_open_ports
    for port in oports[0[0[0]]]:
TypeError: 'int' object has no attribute '__getitem__'

2017-10-14 14:38:53,829;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-14 14:38:53,829;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-14 14:38:53,905;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-10-14 14:38:53,906;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
testing something
