### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#109]
Zeus version:
`1.0.55`

Firefox version:
`(56, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 496, in <module>
    __run_attacks_main()
  File "zeus.py", line 467, in __run_attacks_main
    batch=opt.runInBatch, auto_start=opt.autoStartSqlmap
  File "zeus.py", line 423, in __run_attacks
    agent=agent_to_use, tamper=opt.tamperXssPayloads
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 160, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 120, in scan_xss
    if query[1][10] in html_data:
IndexError: tuple index out of range
````

Running details:
`Linux-4.10.0-35-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d incontext:passwords -x`

Log file info:
```2017-10-18 13:16:04,585;zeus-log;INFO;log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-50.log'...
2017-10-18 13:16:04,585;zeus-log;INFO;using default search engine...
2017-10-18 13:16:04,585;zeus-log;INFO;starting dork scan with query 'incontext:passwords'...
2017-10-18 13:16:04,585;zeus-log;WARNING;will not parse webcache URLs...
2017-10-18 13:16:04,586;zeus-log;WARNING;only pulling URLs with GET(query) parameters...
2017-10-18 13:16:04,586;zeus-log;INFO;attempting to gather query URL...
2017-10-18 13:16:05,030;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-18 13:16:05,031;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-18 13:16:16,757;zeus-log;INFO;browser will open shortly...
2017-10-18 13:16:18,912;zeus-log;INFO;searching 'http://google.com' using query 'incontext:passwords'...
2017-10-18 13:16:22,839;zeus-log;INFO;closing the browser and continuing process..
2017-10-18 13:16:24,269;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-18 13:16:24,269;zeus-log;INFO;no proxy configuration detected...
2017-10-18 13:16:24,851;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.55)::Python->v2.7'...
2017-10-18 13:16:24,890;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/url-log/url-log-27.log'...
2017-10-18 13:16:24,890;zeus-log;INFO;found a total of 26 URLs with given query 'incontext:passwords'...
2017-10-18 13:16:26,482;zeus-log;INFO;loading payloads...
2017-10-18 13:16:26,618;zeus-log;INFO;payloads will be written to a temporary file and read from there...
2017-10-18 13:16:26,619;zeus-log;INFO;loaded URL's have been saved to '/tmp/tmpqin2ZG'...
2017-10-18 13:16:26,619;zeus-log;INFO;testing for XSS vulnerabilities on host 'http://webcache.googleusercontent.com/search?q=cache:UQfS4um0r8UJ:https://digitalcontentnext.org/incontext/%2Bincontext:passwords&hl=en&gbv=1&ct=clnk'...
2017-10-18 13:16:26,995;zeus-log;ERROR;[7;31;31mran into exception 'tuple index out of range' exception has been saved to log file...
Traceback (most recent call last):
  File "zeus.py", line 496, in <module>
    __run_attacks_main()
  File "zeus.py", line 467, in __run_attacks_main
    batch=opt.runInBatch, auto_start=opt.autoStartSqlmap
  File "zeus.py", line 423, in __run_attacks
    agent=agent_to_use, tamper=opt.tamperXssPayloads
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 160, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 120, in scan_xss
    if query[1][10] in html_data:
IndexError: tuple index out of range

2017-10-18 13:16:29,480;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-18 13:16:29,480;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-18 13:16:29,568;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-10-18 13:16:29,568;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
just making sure this is working, haven't seen an issue in a little bit.
