### ISSUE TITLE
WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#110]
Zeus version:
`1.0.39`

Error info:
```Traceback (most recent call last):
  File "/home/boris/Desktop/A N O N Y M O U S/Zeus-Scanner/var/google_search/search.py", line 248, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/home/boris/Desktop/A N O N Y M O U S/Zeus-Scanner/var/google_search/search.py", line 123, in get_urls
    browser = webdriver.Firefox(profile, proxy=proxy_to_use)
  File "/home/boris/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/home/boris/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
````

Running details:
`Linux-4.9.0-parrot13-686-pae-i686-with-Parrot-3.8-JollyRoger`

Commands used:
`zeus.py --rand-dork --sqli -L100 --random-agent --search-engine-ddg`

Log file info:
```2017-10-19 00:01:38,845;zeus-log;INFO;log file being saved to '/home/boris/Desktop/A N O N Y M O U S/Zeus-Scanner/log/zeus-log-99.log'...
2017-10-19 00:01:38,847;zeus-log;INFO;specified to use non-default search engine...
2017-10-19 00:01:38,850;zeus-log;INFO;using random dork 'start.php?sp=' as the search query...
2017-10-19 00:01:38,850;zeus-log;INFO;attempting to gather query URL...
2017-10-19 00:01:38,985;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-19 00:01:38,986;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-19 00:01:38,996;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception 'Message: 'geckodriver' executable needs to be in PATH.' exception has been logged to current log file...
Traceback (most recent call last):
  File "/home/boris/Desktop/A N O N Y M O U S/Zeus-Scanner/var/google_search/search.py", line 248, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/home/boris/Desktop/A N O N Y M O U S/Zeus-Scanner/var/google_search/search.py", line 123, in get_urls
    browser = webdriver.Firefox(profile, proxy=proxy_to_use)
  File "/home/boris/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/home/boris/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 


2017-10-19 00:01:38,998;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-19 00:01:38,998;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-19 00:01:39,013;zeus-log;INFO;[32mextracting traceback from log file...[0m
```

**Comment by Ekultek** [comment]
Alright a couple of things that you need to do here:

 - redownload the newest version of Zeus
 - run `sudo python zeus.py` that will install all the dependencies

Your commands are a little messed up, not as bad as I’ve seen (might have to write a parser for them):
 - `-L` only works with `-M` and you’d need to specify your own dork with `-d`

Other then that once you reinstall and get the dependencies done you should be alright. Thanks for using Zeus
