### ISSUE TITLE
Exception: random testing error (hSNUaTw)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#117]
Zeus version:
`1.0.56.d813e7`

Firefox version:
`(56, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 507, in <module>
    __run_attacks_main()
  File "zeus.py", line 478, in __run_attacks_main
    auto_start=opt.autoStartSqlmap
  File "zeus.py", line 433, in __run_attacks
    url, verbose=opt.runInVerbose, readable=opt.showReadableOutput
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/whois_lookup/whois.py", line 97, in whois_lookup_main
    "random testing error"
Exception: random testing error
````

Running details:
`Linux-4.10.0-37-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:php?id=10 -w --verbose --show-readable -W -E`

Log file info:
```2017-10-21 10:08:47,905;zeus-log;DEBUG;checking if the application has been run before...
2017-10-21 10:08:47,906;zeus-log;DEBUG;verifying operating system...
2017-10-21 10:08:47,906;zeus-log;DEBUG;already ran, skipping...
2017-10-21 10:08:47,906;zeus-log;DEBUG;running with options '{'runInVerbose': True, 'showReadableOutput': True, 'performWhoisLookup': True, 'noExclude': True, 'parseWebcache': True, 'dorkToUse': 'inurl:php?id=10'}'...
2017-10-21 10:08:47,909;zeus-log;INFO;log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-135.log'...
2017-10-21 10:08:47,910;zeus-log;DEBUG;using default search engine (Google)...
2017-10-21 10:08:47,910;zeus-log;INFO;using default search engine...
2017-10-21 10:08:47,910;zeus-log;INFO;starting dork scan with query 'inurl:php?id=10'...
2017-10-21 10:08:47,910;zeus-log;DEBUG;checking for user-agent and proxy configuration...
2017-10-21 10:08:47,910;zeus-log;INFO;attempting to gather query URL...
2017-10-21 10:08:47,910;zeus-log;DEBUG;setting up the virtual display to hide the browser...
2017-10-21 10:08:48,113;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-21 10:08:48,114;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-21 10:08:48,115;zeus-log;DEBUG;running selenium-webdriver and launching browser...
2017-10-21 10:08:48,115;zeus-log;DEBUG;adjusting selenium-webdriver user-agent to 'Zeus-Scanner(v1.0.56.d813e7)::Python->v2.7'...
2017-10-21 10:09:03,738;zeus-log;INFO;browser will open shortly...
2017-10-21 10:09:06,502;zeus-log;DEBUG;searching search engine for the 'q' element (search button)...
2017-10-21 10:09:06,593;zeus-log;INFO;searching 'http://google.com' using query 'inurl:php?id=10'...
2017-10-21 10:09:09,766;zeus-log;DEBUG;obtaining URL from selenium...
2017-10-21 10:09:09,780;zeus-log;DEBUG;found current URL from selenium browser...
2017-10-21 10:09:09,780;zeus-log;INFO;closing the browser and continuing process..
2017-10-21 10:09:09,968;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-21 10:09:09,973;zeus-log;INFO;no proxy configuration detected...
2017-10-21 10:09:10,574;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.56.d813e7)::Python->v2.7'...
2017-10-21 10:09:10,611;zeus-log;DEBUG;found 'http://www.imagesystems.com.mt/index.php?id=10'...
2017-10-21 10:09:10,612;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:kSrFQC-6V7sJ:http://www.imagesystems.com.mt/index.php?id%3D10%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-10-21 10:09:10,612;zeus-log;DEBUG;found 'http://www.icdcprague.org/index.php?id=10'...
2017-10-21 10:09:10,613;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:r1Vp6iF0AqUJ:http://www.icdcprague.org/index.php?id%3D10%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-10-21 10:09:10,613;zeus-log;DEBUG;found 'http://www.architecturalpapers.ch/index.php?ID=10'...
2017-10-21 10:09:10,614;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:P44DWpEEeHcJ:http://www.architecturalpapers.ch/index.php?ID%3D10%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-10-21 10:09:10,614;zeus-log;DEBUG;found 'http://www.katun.me/page.php?id=10'...
2017-10-21 10:09:10,615;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:tuhv_sc8i60J:http://www.katun.me/page.php?id%3D10%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-10-21 10:09:10,615;zeus-log;DEBUG;found 'http://www.dynatekbikes.com/news.php?id=10'...
2017-10-21 10:09:10,616;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:0iQyhkA88_gJ:http://www.dynatekbikes.com/news.php?id%3D10%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-10-21 10:09:10,616;zeus-log;DEBUG;found 'http://library.olivet.edu/forms/email/index.php?id=10'...
2017-10-21 10:09:10,617;zeus-log;DEBUG;found 'http://www.marylandfarmlink.com/dynamic_page.php?id=10'...
2017-10-21 10:09:10,617;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:KLqEWB7wB_QJ:http://www.marylandfarmlink.com/dynamic_page.php?id%3D10%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-10-21 10:09:10,618;zeus-log;DEBUG;found 'https://www.eia.gov/todayinenergy/detail.php?id=10'...
2017-10-21 10:09:10,618;zeus-log;DEBUG;found 'https://www.eia.gov/todayinenergy/detail.<b'...
2017-10-21 10:09:10,619;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:NpPieBZDnrYJ:https://www.eia.gov/todayinenergy/detail.php?id%3D10%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-10-21 10:09:10,619;zeus-log;DEBUG;found 'http://www.doorlinkmfg.com/product.php?id=10'...
2017-10-21 10:09:10,620;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:zZ17Vv8oqfkJ:http://www.doorlinkmfg.com/product.php?id%3D10%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-10-21 10:09:10,620;zeus-log;DEBUG;found 'http://www.apsf.org/initiatives.php?id=10'...
2017-10-21 10:09:10,622;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:OHE-Vo49-NAJ:http://www.apsf.org/initiatives.php?id%3D10%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-10-21 10:09:10,622;zeus-log;INFO;found a webcache URL, extracting...
2017-10-21 10:09:10,625;zeus-log;DEBUG;found 'https://www.eia.gov/todayinenergy/detail.php?id=10'...
2017-10-21 10:09:10,625;zeus-log;INFO;found a webcache URL, extracting...
2017-10-21 10:09:10,625;zeus-log;DEBUG;found 'http://www.apsf.org/initiatives.php?id=10'...
2017-10-21 10:09:10,625;zeus-log;INFO;found a webcache URL, extracting...
2017-10-21 10:09:10,626;zeus-log;DEBUG;found 'http://www.icdcprague.org/index.php?id=10'...
2017-10-21 10:09:10,626;zeus-log;INFO;found a webcache URL, extracting...
2017-10-21 10:09:10,626;zeus-log;DEBUG;found 'http://www.imagesystems.com.mt/index.php?id=10'...
2017-10-21 10:09:10,626;zeus-log;INFO;found a webcache URL, extracting...
2017-10-21 10:09:10,626;zeus-log;DEBUG;found 'http://www.marylandfarmlink.com/dynamic_page.php?id=10'...
2017-10-21 10:09:10,626;zeus-log;INFO;found a webcache URL, extracting...
2017-10-21 10:09:10,627;zeus-log;DEBUG;found 'http://www.katun.me/page.php?id=10'...
2017-10-21 10:09:10,627;zeus-log;INFO;found a webcache URL, extracting...
2017-10-21 10:09:10,627;zeus-log;DEBUG;found 'http://www.architecturalpapers.ch/index.php?ID=10'...
2017-10-21 10:09:10,627;zeus-log;INFO;found a webcache URL, extracting...
2017-10-21 10:09:10,627;zeus-log;DEBUG;found 'http://www.dynatekbikes.com/news.php?id=10'...
2017-10-21 10:09:10,627;zeus-log;INFO;found a webcache URL, extracting...
2017-10-21 10:09:10,628;zeus-log;DEBUG;found 'http://www.doorlinkmfg.com/product.php?id=10'...
2017-10-21 10:09:10,628;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/url-log/url-log-4.log'...
2017-10-21 10:09:10,628;zeus-log;INFO;found a total of 11 URLs with given query 'inurl:php?id=10'...
2017-10-21 10:09:12,156;zeus-log;ERROR;[7;31;31mran into exception 'random testing error' exception has been saved to log file...
Traceback (most recent call last):
  File "zeus.py", line 507, in <module>
    __run_attacks_main()
  File "zeus.py", line 478, in __run_attacks_main
    auto_start=opt.autoStartSqlmap
  File "zeus.py", line 433, in __run_attacks
    url, verbose=opt.runInVerbose, readable=opt.showReadableOutput
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/whois_lookup/whois.py", line 97, in whois_lookup_main
    "random testing error"
Exception: random testing error

2017-10-21 10:09:14,451;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-21 10:09:14,451;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-21 10:09:14,466;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-10-21 10:09:14,467;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
Just a test
