### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc2 in position 0: unexpected end of data (SGYcWMy)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#125]
Zeus version:
`1.1.1`

Firefox version:
`(55, 0)`

Geckodriver version:
`geckodriver-v0.18.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/tanus/Zeus-Scanner/var/google_search/search.py", line 272, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/home/tanus/Zeus-Scanner/var/google_search/search.py", line 159, in get_urls
    search.send_keys(query)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 350, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 499, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 295, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 461, in execute
    data = utils.dump_json(params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/utils.py", line 34, in dump_json
    return json.dumps(json_struct)
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc2 in position 0: unexpected end of data
````

Running details:
`Linux-4.12.0-parrot6-amd64-x86_64-with-Parrot-3.8-JollyRoger`

Commands used:
`zeus.py -l ../sqlmate/dorks9:34.txt`

Log file info:
```2017-10-27 14:08:54,570;zeus-log;INFO;log file being saved to '/home/tanus/Zeus-Scanner/log/zeus-log-5.log'...
2017-10-27 14:08:54,570;zeus-log;INFO;using default search engine...
2017-10-27 14:08:54,898;zeus-log;INFO;starting dork scan with query ' intext:"WAN IT LTD" inurl:"id=" +"site:edu.bd"'...
2017-10-27 14:08:54,898;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-10-27 14:08:54,898;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-10-27 14:08:54,898;zeus-log;INFO;attempting to gather query URL...
2017-10-27 14:08:55,147;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-27 14:08:55,148;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-27 14:09:08,492;zeus-log;INFO;browser will open shortly...
2017-10-27 14:09:21,351;zeus-log;INFO;searching 'http://google.com' using query ' intext:"WAN IT LTD" inurl:"id=" +"site:edu.bd"'...
2017-10-27 14:09:21,352;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception ''utf8' codec can't decode byte 0xc2 in position 0: unexpected end of data' exception has been logged to current log file...
Traceback (most recent call last):
  File "/home/tanus/Zeus-Scanner/var/google_search/search.py", line 272, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/home/tanus/Zeus-Scanner/var/google_search/search.py", line 159, in get_urls
    search.send_keys(query)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 350, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 499, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 295, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 461, in execute
    data = utils.dump_json(params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/utils.py", line 34, in dump_json
    return json.dumps(json_struct)
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc2 in position 0: unexpected end of data

2017-10-27 14:10:04,951;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-27 14:10:04,951;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-27 14:10:04,952;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-10-27 14:10:04,953;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
HA! I use sqlmate as well! It's super cool isn't it?

Lemme go ahead and take a look at this give me a few minutes

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/ecf067b6bbc8d3a1ab25a14239325482d37e5a57 it seems that selenium doesn't handle unicode very well, so for now the dork will be skipped until I can find a way to pass unicode to selenium.
