### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '/home/baal/bin/python/zeus-scanner/lob/admin-page-log' (iPDlToS)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#126]
Zeus version:
`1.1.6.c32363`

Firefox version:
`(56, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 530, in <module>
    __run_attacks_main()
  File "zeus.py", line 380, in __run_attacks_main
    auto_start=opt.autoStartSqlmap
  File "zeus.py", line 326, in __run_attacks
    verbose=verbose, do_threading=opt.threadPanels
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 216, in main
    check_for_admin_page(url, extensions, show_possibles=show, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 159, in check_for_admin_page
    replace_http(url)
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 450, in write_to_log_file
    create_dir(path.format(os.getcwd()))
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 215, in create_dir
    os.mkdir(dirpath)
OSError: [Errno 2] No such file or directory: '/home/baal/bin/python/zeus-scanner/lob/admin-page-log'
````

Running details:
`Linux-4.10.0-37-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -f /home/baal/bin/python/zeus-scanner/log/url-log/url-log-17.log -a`

Log file info:
```2017-10-29 10:45:21,009;zeus-log;INFO;log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-74.log'...
2017-10-29 10:45:22,747;zeus-log;WARNING;skipping 'http://www.doorlinkmfg.com/product.php?id=10'...
2017-10-29 10:45:23,737;zeus-log;INFO;parsing robots.txt...
2017-10-29 10:45:24,092;zeus-log;ERROR;unable to connect to '/robots.txt', assuming does not exist and continuing...
2017-10-29 10:45:24,093;zeus-log;WARNING;seems like this page is either blocking access to robots.txt or it does not exist...
2017-10-29 10:45:24,093;zeus-log;INFO;checking for a sitemap...
2017-10-29 10:45:24,783;zeus-log;INFO;found a sitemap, saving to file...
2017-10-29 10:45:24,790;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/sitemap-log/www.katun.me-sitemap.xml'...
2017-10-29 10:45:24,790;zeus-log;INFO;loading extensions...
2017-10-29 10:45:24,791;zeus-log;INFO;attempting to bruteforce admin panel...
2017-10-29 10:46:18,052;zeus-log;INFO;connected successfully to 'http://www.katun.me/index.php'...
2017-10-29 10:49:32,598;zeus-log;INFO;found 0 possible connections(s) and 1 successful connection(s)...
2017-10-29 10:49:32,598;zeus-log;INFO;creating connection tree...
2017-10-29 10:49:32,599;zeus-log;WARNING;only writing successful connections to log file...
2017-10-29 10:49:32,599;zeus-log;ERROR;[7;31;31mran into exception '[Errno 2] No such file or directory: '/home/baal/bin/python/zeus-scanner/lob/admin-page-log'' exception has been saved to log file...
Traceback (most recent call last):
  File "zeus.py", line 530, in <module>
    __run_attacks_main()
  File "zeus.py", line 380, in __run_attacks_main
    auto_start=opt.autoStartSqlmap
  File "zeus.py", line 326, in __run_attacks
    verbose=verbose, do_threading=opt.threadPanels
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 216, in main
    check_for_admin_page(url, extensions, show_possibles=show, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 159, in check_for_admin_page
    replace_http(url)
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 450, in write_to_log_file
    create_dir(path.format(os.getcwd()))
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 215, in create_dir
    os.mkdir(dirpath)
OSError: [Errno 2] No such file or directory: '/home/baal/bin/python/zeus-scanner/lob/admin-page-log'

2017-10-29 10:49:49,264;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-29 10:49:49,264;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-29 10:49:49,336;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-10-29 10:49:49,337;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
testing
