### ISSUE TITLE
TypeError: int() argument must be a string or a number, not 'tuple' (ONwRtHZ)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#127]
Zeus version:
`1.1.7.603077`

Firefox version:
`(56, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 416, in <module>
    __run_attacks_main()
  File "zeus.py", line 378, in __run_attacks_main
    auto_start=opt.autoStartSqlmap
  File "zeus.py", line 333, in __run_attacks
    url, verbose=opt.runInVerbose, readable=opt.showReadableOutput
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/whois_lookup/whois.py", line 110, in whois_lookup_main
    raw_information = gather_raw_whois_info(domain)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/whois_lookup/whois.py", line 47, in gather_raw_whois_info
    "Authorization": "Token {}".format(__get_token()),
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/whois_lookup/whois.py", line 37, in __get_token
    token = __decode(encoded, int(n))
TypeError: int() argument must be a string or a number, not 'tuple'
````

Running details:
`Linux-4.10.0-37-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:php?id=10 -w`

Log file info:
```2017-10-29 11:04:21,209;zeus-log;INFO;log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-82.log'...
2017-10-29 11:04:21,210;zeus-log;INFO;using default search engine...
2017-10-29 11:04:21,212;zeus-log;INFO;starting dork scan with query 'inurl:php?id=10'...
2017-10-29 11:04:21,212;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-10-29 11:04:21,213;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-10-29 11:04:21,213;zeus-log;INFO;attempting to gather query URL...
2017-10-29 11:04:21,474;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-29 11:04:21,475;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-29 11:04:31,871;zeus-log;INFO;browser will open shortly...
2017-10-29 11:04:33,825;zeus-log;INFO;searching 'http://google.com' using query 'inurl:php?id=10'...
2017-10-29 11:04:37,006;zeus-log;INFO;closing the browser and continuing process..
2017-10-29 11:04:37,052;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-29 11:04:37,052;zeus-log;INFO;no proxy configuration detected...
2017-10-29 11:04:37,453;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner/1.1.7.603077 (Language=Python/2.7.13; Platform=Linux)'...
2017-10-29 11:04:37,464;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/url-log/url-log-18.log'...
2017-10-29 11:04:37,464;zeus-log;INFO;found a total of 22 URLs with given query 'inurl:php?id=10'...
2017-10-29 11:04:40,861;zeus-log;INFO;performing WhoIs lookup on given domain 'www.cacert.org'...
2017-10-29 11:04:40,878;zeus-log;ERROR;[7;31;31mran into exception 'int() argument must be a string or a number, not 'tuple'' exception has been saved to log file...
Traceback (most recent call last):
  File "zeus.py", line 416, in <module>
    __run_attacks_main()
  File "zeus.py", line 378, in __run_attacks_main
    auto_start=opt.autoStartSqlmap
  File "zeus.py", line 333, in __run_attacks
    url, verbose=opt.runInVerbose, readable=opt.showReadableOutput
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/whois_lookup/whois.py", line 110, in whois_lookup_main
    raw_information = gather_raw_whois_info(domain)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/whois_lookup/whois.py", line 47, in gather_raw_whois_info
    "Authorization": "Token {}".format(__get_token()),
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/whois_lookup/whois.py", line 37, in __get_token
    token = __decode(encoded, int(n))
TypeError: int() argument must be a string or a number, not 'tuple'

2017-10-29 11:04:44,177;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-29 11:04:44,177;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-29 11:04:44,178;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-10-29 11:04:44,179;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
testing
