### ISSUE TITLE
TypeError: object of type 'NoneType' has no len() (roQCcwe)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#128]
Zeus version:
`1.1.8`

Firefox version:
`(56, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 416, in <module>
    __run_attacks_main()
  File "zeus.py", line 378, in __run_attacks_main
    auto_start=opt.autoStartSqlmap
  File "zeus.py", line 333, in __run_attacks
    url, verbose=opt.runInVerbose, readable=opt.showReadableOutput
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/whois_lookup/whois.py", line 134, in whois_lookup_main
    if len(v) != 0 or v is not None:
TypeError: object of type 'NoneType' has no len()
````

Running details:
`Linux-4.10.0-37-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:suite?sal**=* -w --verbose -W -E`

Log file info:
```2017-10-30 21:50:30,170;zeus-log;DEBUG;checking if the application has been run before...
2017-10-30 21:50:30,179;zeus-log;DEBUG;verifying operating system...
2017-10-30 21:50:30,180;zeus-log;DEBUG;already ran, skipping...
2017-10-30 21:50:30,181;zeus-log;DEBUG;running with options '{'noExclude': True, 'runInVerbose': True, 'parseWebcache': True, 'performWhoisLookup': True, 'dorkToUse': 'inurl:suite?sal**=*'}'...
2017-10-30 21:50:30,181;zeus-log;INFO;log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-100.log'...
2017-10-30 21:50:30,182;zeus-log;DEBUG;using default search engine (Google)...
2017-10-30 21:50:30,182;zeus-log;INFO;using default search engine...
2017-10-30 21:50:30,182;zeus-log;INFO;starting dork scan with query 'inurl:suite?sal**=*'...
2017-10-30 21:50:30,182;zeus-log;DEBUG;checking for user-agent and proxy configuration...
2017-10-30 21:50:30,182;zeus-log;INFO;attempting to gather query URL...
2017-10-30 21:50:30,182;zeus-log;DEBUG;setting up the virtual display to hide the browser...
2017-10-30 21:50:30,451;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-30 21:50:30,452;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-30 21:50:30,452;zeus-log;DEBUG;running selenium-webdriver and launching browser...
2017-10-30 21:50:30,452;zeus-log;DEBUG;adjusting selenium-webdriver user-agent to 'Zeus-Scanner/1.1.8 (Language=Python/2.7.13; Platform=Linux)'...
2017-10-30 21:50:45,968;zeus-log;INFO;browser will open shortly...
2017-10-30 21:50:48,611;zeus-log;DEBUG;searching search engine for the 'q' element (search button)...
2017-10-30 21:50:48,641;zeus-log;INFO;searching 'http://google.com' using query 'inurl:suite?sal**=*'...
2017-10-30 21:50:51,856;zeus-log;DEBUG;obtaining URL from selenium...
2017-10-30 21:50:51,866;zeus-log;DEBUG;found current URL from selenium browser...
2017-10-30 21:50:51,866;zeus-log;INFO;closing the browser and continuing process..
2017-10-30 21:50:51,989;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-30 21:50:51,989;zeus-log;INFO;no proxy configuration detected...
2017-10-30 21:50:52,479;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner/1.1.8 (Language=Python/2.7.13; Platform=Linux)'...
2017-10-30 21:50:52,574;zeus-log;DEBUG;found 'https://forums.iis.net/t/1160305.aspx?Business+Productivity+Suite+BPS+'...
2017-10-30 21:50:52,575;zeus-log;DEBUG;found 'https://forums.iis.net/t/1160305.aspx?Business+Productivity+<b'...
2017-10-30 21:50:52,575;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:nULKFnJbEHgJ:https://forums.iis.net/t/1160305.aspx?Business%2BProductivity%2BSuite%2BBPS%2B%2Binurl:suite?sal'...
2017-10-30 21:50:52,576;zeus-log;DEBUG;found 'https://websites.jaispirit.com/product/business-productivity-suite-sal/'...
2017-10-30 21:50:52,576;zeus-log;DEBUG;found 'https://websites.jaispirit.com/product/business-productivity-<b'...
2017-10-30 21:50:52,576;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:04ZrlqJASWUJ:https://websites.jaispirit.com/product/business-productivity-suite-sal/%2Binurl:suite?sal'...
2017-10-30 21:50:52,577;zeus-log;DEBUG;found 'http://sendgop.weebly.com/blog/microsoft-productivity-suite-sal'...
2017-10-30 21:50:52,577;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:Tp16BAtxljAJ:http://sendgop.weebly.com/blog/microsoft-productivity-suite-sal%2Binurl:suite?sal'...
2017-10-30 21:50:52,578;zeus-log;DEBUG;found 'https://www.rhipe.com/knowledge/microsoft-12-conversations/conversation-3-productivity-suite/'...
2017-10-30 21:50:52,578;zeus-log;DEBUG;found 'https://www.rhipe.com/.../conversation-3-productivity-<b'...
2017-10-30 21:50:52,579;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:Y6oZbvZv364J:https://www.rhipe.com/knowledge/microsoft-12-conversations/conversation-3-productivity-suite/%2Binurl:suite?sal'...
2017-10-30 21:50:52,579;zeus-log;DEBUG;found 'https://3rdquote.sg/microsoft-productivity-suite-sal-all-lng-licensesoftware-assurance-pack-microsoft-volume-license-1-license-sal'...
2017-10-30 21:50:52,579;zeus-log;DEBUG;found 'https://3rdquote.sg/microsoft-productivity-<b'...
2017-10-30 21:50:52,580;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:9-NVPm3tMRgJ:https://3rdquote.sg/microsoft-productivity-suite-sal-all-lng-licensesoftware-assurance-pack-microsoft-volume-license-1-license-sal%2Binurl:suite?sal'...
2017-10-30 21:50:52,580;zeus-log;DEBUG;found 'http://gurupid.jimdo.com/2017/07/18/microsoft-productivity-suite-sal/'...
2017-10-30 21:50:52,580;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:YGamY356v2MJ:http://gurupid.jimdo.com/2017/07/18/microsoft-productivity-suite-sal/%2Binurl:suite?sal'...
2017-10-30 21:50:52,580;zeus-log;DEBUG;found 'https://lb.kompass.com/c/suite-home-sal/lb014088/'...
2017-10-30 21:50:52,581;zeus-log;DEBUG;found 'https://lb.kompass.com/c/<b'...
2017-10-30 21:50:52,581;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:KcmHhYvA3EQJ:https://lb.kompass.com/c/suite-home-sal/lb014088/%2Binurl:suite?sal'...
2017-10-30 21:50:52,581;zeus-log;DEBUG;found 'http://wptest.loenbro.com/microsoft-business-productivity-suite-sal.pdf'...
2017-10-30 21:50:52,581;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:ODkB_URrmvYJ:http://wptest.loenbro.com/microsoft-business-productivity-suite-sal.pdf%2Binurl:suite?sal'...
2017-10-30 21:50:52,582;zeus-log;DEBUG;found 'https://lockpid.jimdo.com/2017/07/15/microsoft-productivity-suite-sal/'...
2017-10-30 21:50:52,582;zeus-log;DEBUG;found 'https://lockpid.jimdo.com/2017/07/.../microsoft-productivity-<b'...
2017-10-30 21:50:52,582;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:iZbgSw6lOfIJ:https://lockpid.jimdo.com/2017/07/15/microsoft-productivity-suite-sal/%2Binurl:suite?sal'...
2017-10-30 21:50:52,582;zeus-log;DEBUG;found 'https://www.amazon.com/Silk-Route-Suite-III-Salt/dp/B003P5YSMI'...
2017-10-30 21:50:52,583;zeus-log;DEBUG;found 'https://www.amazon.com/Silk-Route-<b'...
2017-10-30 21:50:52,583;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:42BGtGGuZnEJ:https://www.amazon.com/Silk-Route-Suite-III-Salt/dp/B003P5YSMI%2Binurl:suite?sal'...
2017-10-30 21:50:52,583;zeus-log;INFO;found a webcache URL, extracting...
2017-10-30 21:50:52,583;zeus-log;DEBUG;found 'https://forums.iis.net/t/1160305.aspx?Business'...
2017-10-30 21:50:52,584;zeus-log;INFO;found a webcache URL, extracting...
2017-10-30 21:50:52,584;zeus-log;DEBUG;found 'http://sendgop.weebly.com/blog/microsoft-productivity-suite-sal'...
2017-10-30 21:50:52,584;zeus-log;INFO;found a webcache URL, extracting...
2017-10-30 21:50:52,584;zeus-log;DEBUG;found 'http://gurupid.jimdo.com/2017/07/18/microsoft-productivity-suite-sal/'...
2017-10-30 21:50:52,584;zeus-log;INFO;found a webcache URL, extracting...
2017-10-30 21:50:52,584;zeus-log;DEBUG;found 'https://websites.jaispirit.com/product/business-productivity-suite-sal/'...
2017-10-30 21:50:52,584;zeus-log;INFO;found a webcache URL, extracting...
2017-10-30 21:50:52,585;zeus-log;DEBUG;found 'https://www.rhipe.com/knowledge/microsoft-12-conversations/conversation-3-productivity-suite/'...
2017-10-30 21:50:52,585;zeus-log;INFO;found a webcache URL, extracting...
2017-10-30 21:50:52,585;zeus-log;DEBUG;found 'https://lb.kompass.com/c/suite-home-sal/lb014088/'...
2017-10-30 21:50:52,585;zeus-log;INFO;found a webcache URL, extracting...
2017-10-30 21:50:52,585;zeus-log;DEBUG;found 'https://www.amazon.com/Silk-Route-Suite-III-Salt/dp/B003P5YSMI'...
2017-10-30 21:50:52,585;zeus-log;INFO;found a webcache URL, extracting...
2017-10-30 21:50:52,586;zeus-log;DEBUG;found 'http://wptest.loenbro.com/microsoft-business-productivity-suite-sal.pdf'...
2017-10-30 21:50:52,586;zeus-log;INFO;found a webcache URL, extracting...
2017-10-30 21:50:52,586;zeus-log;DEBUG;found 'https://lockpid.jimdo.com/2017/07/15/microsoft-productivity-suite-sal/'...
2017-10-30 21:50:52,586;zeus-log;INFO;found a webcache URL, extracting...
2017-10-30 21:50:52,586;zeus-log;DEBUG;found 'https://3rdquote.sg/microsoft-productivity-suite-sal-all-lng-licensesoftware-assurance-pack-microsoft-volume-license-1-license-sal'...
2017-10-30 21:50:52,587;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/url-log/url-log-33.log'...
2017-10-30 21:50:52,587;zeus-log;INFO;found a total of 18 URLs with given query 'inurl:suite?sal**=*'...
2017-10-30 21:52:48,873;zeus-log;INFO;performing WhoIs lookup on given domain 'websites.jaispirit.com'...
2017-10-30 21:52:50,630;zeus-log;INFO;discovered raw information...
2017-10-30 21:52:50,630;zeus-log;INFO;gathering interesting information...
2017-10-30 21:52:50,631;zeus-log;DEBUG;found '[]'...
2017-10-30 21:52:50,631;zeus-log;DEBUG;found '[]'...
2017-10-30 21:52:50,631;zeus-log;DEBUG;found '[]'...
2017-10-30 21:52:50,632;zeus-log;ERROR;[7;31;31mran into exception 'object of type 'NoneType' has no len()' exception has been saved to log file...
Traceback (most recent call last):
  File "zeus.py", line 416, in <module>
    __run_attacks_main()
  File "zeus.py", line 378, in __run_attacks_main
    auto_start=opt.autoStartSqlmap
  File "zeus.py", line 333, in __run_attacks
    url, verbose=opt.runInVerbose, readable=opt.showReadableOutput
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/whois_lookup/whois.py", line 134, in whois_lookup_main
    if len(v) != 0 or v is not None:
TypeError: object of type 'NoneType' has no len()

2017-10-30 21:53:00,199;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-30 21:53:00,203;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-30 21:53:00,290;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-10-30 21:53:00,290;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
fixed via https://github.com/Ekultek/Zeus-Scanner/commit/99575425f11435ba3684afaa3f4426e8e48d7fe0
