### ISSUE TITLE
WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//www.google.com.ph/%3Fgfe_rd%3Dcr%26dcr%3D0%26ei%3D41D5WZXSCIel8wf02qzwCg&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20www.google.com.ph. (RwyaGfx)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#132]
Zeus version:
`1.1.11.0e3f6f`

Firefox version:
`(52, 3)`

Geckodriver version:
`geckodriver-v0.17.0-linux32.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/root/tools/Zeus-Scanner/var/google_search/search.py", line 294, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/root/tools/Zeus-Scanner/var/google_search/search.py", line 151, in get_urls
    browser.get(url)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 309, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//www.google.com.ph/%3Fgfe_rd%3Dcr%26dcr%3D0%26ei%3D41D5WZXSCIel8wf02qzwCg&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20www.google.com.ph.
````

Running details:
`Linux-4.12.0-kali1-686-pae-i686-with-Kali-kali-rolling-kali-rolling`

Commands used:
`./zeus.py -d ip:121.42.88.86`

Log file info:
```2017-11-01 00:43:09,913;zeus-log;INFO;log file being saved to '/root/tools/Zeus-Scanner/log/zeus-log-7.log'...
2017-11-01 00:43:09,914;zeus-log;INFO;using default search engine...
2017-11-01 00:43:09,914;zeus-log;INFO;starting dork scan with query 'ip:121.42.88.86'...
2017-11-01 00:43:09,914;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-11-01 00:43:09,914;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-11-01 00:43:09,914;zeus-log;INFO;attempting to gather query URL...
2017-11-01 00:43:10,035;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-11-01 00:43:10,035;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-11-01 00:43:14,613;zeus-log;INFO;browser will open shortly...
2017-11-01 00:43:36,376;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception 'Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//www.google.com.ph/%3Fgfe_rd%3Dcr%26dcr%3D0%26ei%3D41D5WZXSCIel8wf02qzwCg&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20www.google.com.ph.' exception has been logged to current log file...
Traceback (most recent call last):
  File "/root/tools/Zeus-Scanner/var/google_search/search.py", line 294, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/root/tools/Zeus-Scanner/var/google_search/search.py", line 151, in get_urls
    browser.get(url)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 309, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//www.google.com.ph/%3Fgfe_rd%3Dcr%26dcr%3D0%26ei%3D41D5WZXSCIel8wf02qzwCg&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20www.google.com.ph.


2017-11-01 00:43:54,055;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-01 00:43:54,056;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-01 00:43:54,057;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-01 00:43:54,057;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
Fixed via https://github.com/Ekultek/Zeus-Scanner/commit/b26d29108c0526badde3785f53190f0c070cc1cc
