### ISSUE TITLE
ConnectionError: HTTPSConnectionPool(host='liqidweb.com', port=443): Max retries exceeded with url: /?user-agent=Mozilla%2F5.0+ArchLinux+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F535.1+%28KHTML%2C+like+Gecko%29+Chrome%2F13.0.782.41+Safari%2F535.1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f042a07d990>: Failed to establish a new connection: [Errno 111] Con... (rJOGneH)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#134]
Zeus version:
`1.1.15`

Firefox version:
`(56, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/var/blackwidow/__init__.py", line 53, in test_connection
    attempt = requests.get(self.url, params=self.headers, proxies=self.proxy)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='liqidweb.com', port=443): Max retries exceeded with url: /?user-agent=Mozilla%2F5.0+ArchLinux+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F535.1+%28KHTML%2C+like+Gecko%29+Chrome%2F13.0.782.41+Safari%2F535.1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f042a07d990>: Failed to establish a new connection: [Errno 111] Con...
````

Running details:
`Linux-4.10.0-37-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -b https://liqidweb.com --verbose --random-agent`

Log file info:
```2017-11-03 09:41:41,335;zeus-log;DEBUG;checking if the application has been run before...
2017-11-03 09:41:41,336;zeus-log;DEBUG;verifying operating system...
2017-11-03 09:41:41,336;zeus-log;DEBUG;already ran, skipping...
2017-11-03 09:41:41,336;zeus-log;DEBUG;running with options '{'runInVerbose': True, 'useRandomAgent': True, 'spiderWebSite': 'https://liqidweb.com'}'...
2017-11-03 09:41:41,337;zeus-log;INFO;log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-38.log'...
2017-11-03 09:41:41,337;zeus-log;DEBUG;grabbing random user-agent from '/home/baal/bin/python/zeus-scanner/etc/agents.txt'...
2017-11-03 09:41:41,338;zeus-log;DEBUG;using default search engine (Google)...
2017-11-03 09:41:41,338;zeus-log;INFO;using default search engine...
2017-11-03 09:41:41,338;zeus-log;DEBUG;settings user-agent to 'Mozilla/5.0 ArchLinux (X11; Linux x86_64) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.41 Safari/535.1'...
2017-11-03 09:41:41,338;zeus-log;INFO;starting blackwidow on 'https://liqidweb.com'...
2017-11-03 09:41:41,339;zeus-log;DEBUG;testing connection to the URL...
2017-11-03 09:41:41,410;zeus-log;ERROR;[7;31;31mfailed to connect to 'https://liqidweb.com' received error 'HTTPSConnectionPool(host='liqidweb.com', port=443): Max retries exceeded with url: /?user-agent=Mozilla%2F5.0+ArchLinux+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F535.1+%28KHTML%2C+like+Gecko%29+Chrome%2F13.0.782.41+Safari%2F535.1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f042a07d990>: Failed to establish a new connection: [Errno 111] Connection refused',))'...
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/var/blackwidow/__init__.py", line 53, in test_connection
    attempt = requests.get(self.url, params=self.headers, proxies=self.proxy)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='liqidweb.com', port=443): Max retries exceeded with url: /?user-agent=Mozilla%2F5.0+ArchLinux+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F535.1+%28KHTML%2C+like+Gecko%29+Chrome%2F13.0.782.41+Safari%2F535.1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f042a07d990>: Failed to establish a new connection: [Errno 111] Connection refused',))

2017-11-03 09:41:59,703;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-03 09:41:59,703;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-03 09:41:59,738;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-03 09:41:59,738;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
fixed via https://github.com/Ekultek/Zeus-Scanner/commit/90ba39f3ed1f0582773ac5607b9a1ce2b3d27abd
