### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'status_code' (Trsynnc)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#138]
Zeus version:
`1.1.19`

Firefox version:
`(56, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/intel_me/__init__.py", line 148, in main_intel_amt
    json_data = __get_hardware(url, agent=agent, proxy=proxy)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/intel_me/__init__.py", line 81, in __get_hardware
    if not req.status_code == 200:
AttributeError: 'NoneType' object has no attribute 'status_code'
````

Running details:
`Linux-4.10.0-37-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:php?id=10 --verbose -i`

Log file info:
```2017-11-06 12:11:08,191;zeus-log;DEBUG;checking if the application has been run before...
2017-11-06 12:11:08,192;zeus-log;DEBUG;verifying operating system...
2017-11-06 12:11:08,201;zeus-log;DEBUG;already ran, skipping...
2017-11-06 12:11:08,202;zeus-log;DEBUG;running with options '{'runInVerbose': True, 'intelCheck': True, 'dorkToUse': 'inurl:php?id=10'}'...
2017-11-06 12:11:08,203;zeus-log;INFO;log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-35.log'...
2017-11-06 12:11:08,203;zeus-log;DEBUG;using default search engine (Google)...
2017-11-06 12:11:08,203;zeus-log;INFO;using default search engine...
2017-11-06 12:11:08,203;zeus-log;INFO;starting dork scan with query 'inurl:php?id=10'...
2017-11-06 12:11:08,203;zeus-log;DEBUG;checking for user-agent and proxy configuration...
2017-11-06 12:11:08,203;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-11-06 12:11:08,203;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-11-06 12:11:08,204;zeus-log;INFO;attempting to gather query URL...
2017-11-06 12:11:08,204;zeus-log;DEBUG;setting up the virtual display to hide the browser...
2017-11-06 12:11:09,073;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-11-06 12:11:09,073;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-11-06 12:11:09,073;zeus-log;DEBUG;running selenium-webdriver and launching browser...
2017-11-06 12:11:09,073;zeus-log;DEBUG;adjusting selenium-webdriver user-agent to 'Zeus-Scanner/1.1.19 (Language=Python/2.7.13; Platform=Linux)'...
2017-11-06 12:11:33,210;zeus-log;INFO;browser will open shortly...
2017-11-06 12:11:36,484;zeus-log;DEBUG;searching search engine for the 'q' element (search button)...
2017-11-06 12:11:36,831;zeus-log;INFO;searching 'http://google.com' using query 'inurl:php?id=10'...
2017-11-06 12:11:41,467;zeus-log;DEBUG;obtaining URL from selenium...
2017-11-06 12:11:41,475;zeus-log;DEBUG;found current URL from selenium browser...
2017-11-06 12:11:41,475;zeus-log;INFO;closing the browser and continuing process..
2017-11-06 12:11:42,200;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-11-06 12:11:42,200;zeus-log;INFO;no proxy configuration detected...
2017-11-06 12:11:43,337;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner/1.1.19 (Language=Python/2.7.13; Platform=Linux)'...
2017-11-06 12:11:43,403;zeus-log;DEBUG;found 'http://www.icdcprague.org/index.php?id=10'...
2017-11-06 12:11:43,404;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:r1Vp6iF0AqUJ:http://www.icdcprague.org/index.php?id%3D10%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-11-06 12:11:43,404;zeus-log;DEBUG;found 'http://www.architecturalpapers.ch/index.php?ID=10'...
2017-11-06 12:11:43,404;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:P44DWpEEeHcJ:http://www.architecturalpapers.ch/index.php?ID%3D10%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-11-06 12:11:43,405;zeus-log;DEBUG;found 'http://www.katun.me/page.php?id=10'...
2017-11-06 12:11:43,405;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:tuhv_sc8i60J:http://www.katun.me/page.php?id%3D10%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-11-06 12:11:43,405;zeus-log;DEBUG;found 'http://www.imagesystems.com.mt/index.php?id=10'...
2017-11-06 12:11:43,405;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:kSrFQC-6V7sJ:http://www.imagesystems.com.mt/index.php?id%3D10%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-11-06 12:11:43,406;zeus-log;DEBUG;found 'http://www.dynatekbikes.com/news.php?id=10'...
2017-11-06 12:11:43,406;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:0iQyhkA88_gJ:http://www.dynatekbikes.com/news.php?id%3D10%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-11-06 12:11:43,406;zeus-log;DEBUG;found 'http://www.cacert.org/index.php?id=4'...
2017-11-06 12:11:43,407;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:D89Bx39OgA8J:http://www.cacert.org/index.php?id%3D4%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-11-06 12:11:43,407;zeus-log;DEBUG;found 'https://stackoverflow.com/questions/43393957/hide-dynamic-page-movie-phpid-10-from-my-php-websites-urls-and-replace-space'...
2017-11-06 12:11:43,407;zeus-log;DEBUG;found 'https://stackoverflow.com/.../hide-dynamic-page-movie-<b'...
2017-11-06 12:11:43,407;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:Ftqh2WeO0REJ:https://stackoverflow.com/questions/43393957/hide-dynamic-page-movie-phpid-10-from-my-php-websites-urls-and-replace-space%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-11-06 12:11:43,408;zeus-log;DEBUG;found 'https://cambridge-editing.com/careers/view.php?id=10'...
2017-11-06 12:11:43,408;zeus-log;DEBUG;found 'https://cambridge-editing.com/careers/view.<b'...
2017-11-06 12:11:43,408;zeus-log;DEBUG;found 'https://cambridge-editing.com/careers/view.php?id=10+inurl:php?id=10'...
2017-11-06 12:11:43,408;zeus-log;DEBUG;found 'http://www.philrosinski.com/index.php?id=10'...
2017-11-06 12:11:43,409;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:JBglQm3iZvYJ:http://www.philrosinski.com/index.php?id%3D10%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-11-06 12:11:43,409;zeus-log;DEBUG;found 'http://www.thundertiger.com/products-detail.php?id=10'...
2017-11-06 12:11:43,409;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:MYXiIfkDXQwJ:http://www.thundertiger.com/products-detail.php?id%3D10%2Binurl:php?id%3D10&hl=en&gbv=1&ct=clnk'...
2017-11-06 12:11:43,497;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/url-log/url-log-13.log'...
2017-11-06 12:11:43,497;zeus-log;INFO;found a total of 22 URLs with given query 'inurl:php?id=10'...
2017-11-06 12:11:45,763;zeus-log;INFO;attempting to connect to 'https://cambridge-editing.com' and get hardware info...
2017-11-06 12:11:45,763;zeus-log;INFO;attempting to get raw hardware information...
2017-11-06 12:11:45,764;zeus-log;INFO;header value not established, attempting to get bypass...
2017-11-06 12:11:55,775;zeus-log;INFO;header value not established, attempting to get bypass...
2017-11-06 12:12:05,783;zeus-log;INFO;header value not established, attempting to get bypass...
2017-11-06 12:12:15,794;zeus-log;INFO;header value not established, attempting to get bypass...
2017-11-06 12:12:25,803;zeus-log;ERROR;ran into exception ''NoneType' object has no attribute 'status_code'', cannot continue...
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/intel_me/__init__.py", line 148, in main_intel_amt
    json_data = __get_hardware(url, agent=agent, proxy=proxy)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/intel_me/__init__.py", line 81, in __get_hardware
    if not req.status_code == 200:
AttributeError: 'NoneType' object has no attribute 'status_code'

2017-11-06 12:13:02,725;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-06 12:13:02,725;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-06 12:13:02,754;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-06 12:13:02,755;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
This was me testing
