### ISSUE TITLE
ConnectionError: HTTPConnectionPool(host='www.microsofttranslator.com', port=80): Max retries exceeded with url: /bv.aspx?ref=SERP%0A&connection=close&user-agent=Zeus-Scanner%2F1.2.2+%28Language%3DPython%2F2.7.14%3B+Platform%3DLinux%29 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fae9ba245d0>: Failed to establish a new connection: [Errno 111] Con... (JIlZkri)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#141]
Zeus version:
`1.2.2`

Firefox version:
`(52, 4)`

Geckodriver version:
`geckodriver-v0.17.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "./zeus.py", line 344, in <module>
    __run_attacks_main()
  File "./zeus.py", line 289, in __run_attacks_main
    proxy=proxy_to_use, xforward=opt.forwardedForRandomIP
  File "/root/Zeus-Scanner/lib/header_check/__init__.py", line 94, in main_header_check
    found_headers = load_headers(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/root/Zeus-Scanner/lib/header_check/__init__.py", line 54, in load_headers
    req = requests.get(url, params=header_value, proxies=proxy)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='www.microsofttranslator.com', port=80): Max retries exceeded with url: /bv.aspx?ref=SERP%0A&connection=close&user-agent=Zeus-Scanner%2F1.2.2+%28Language%3DPython%2F2.7.14%3B+Platform%3DLinux%29 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fae9ba245d0>: Failed to establish a new connection: [Errno 111] Con...
````

Running details:
`Linux-4.12.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`./zeus.py -B -d index.php?pid= -s`

Log file info:
```2017-11-10 23:39:08,387;zeus-log;INFO;log file being saved to '/root/Zeus-Scanner/log/zeus-log-7.log'...
2017-11-10 23:39:08,387;zeus-log;INFO;specified to use non-default search engine...
2017-11-10 23:39:08,387;zeus-log;INFO;starting dork scan with query 'index.php?pid='...
2017-11-10 23:39:08,388;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-11-10 23:39:08,388;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-11-10 23:39:08,388;zeus-log;INFO;attempting to gather query URL...
2017-11-10 23:39:08,505;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-11-10 23:39:08,505;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-11-10 23:39:11,366;zeus-log;INFO;browser will open shortly...
2017-11-10 23:39:12,085;zeus-log;INFO;searching 'http://bing.com' using query 'index.php?pid='...
2017-11-10 23:39:15,285;zeus-log;INFO;closing the browser and continuing process..
2017-11-10 23:39:15,315;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-11-10 23:39:15,316;zeus-log;INFO;no proxy configuration detected...
2017-11-10 23:39:15,823;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner/1.2.2 (Language=Python/2.7.14; Platform=Linux)'...
2017-11-10 23:39:15,827;zeus-log;INFO;successfully wrote found items to '/root/Zeus-Scanner/log/url-log/url-log-5.log'...
2017-11-10 23:39:15,827;zeus-log;INFO;found a total of 22 URLs with given query 'index.php?pid='...
2017-11-10 23:39:15,828;zeus-log;INFO;checking URL headers...
2017-11-10 23:39:15,842;zeus-log;INFO;attempting to get request headers for 'http://www.microsofttranslator.com/bv.aspx?ref=SERP'...
2017-11-10 23:39:15,916;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code 'HTTPConnectionPool(host='www.microsofttranslator.com', port=80): Max retries exceeded with url: /bv.aspx?ref=SERP%0A&connection=close&user-agent=Zeus-Scanner%2F1.2.2+%28Language%3DPython%2F2.7.14%3B+Platform%3DLinux%29 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fae9ba245d0>: Failed to establish a new connection: [Errno 111] Connection refused',))'...
Traceback (most recent call last):
  File "./zeus.py", line 344, in <module>
    __run_attacks_main()
  File "./zeus.py", line 289, in __run_attacks_main
    proxy=proxy_to_use, xforward=opt.forwardedForRandomIP
  File "/root/Zeus-Scanner/lib/header_check/__init__.py", line 94, in main_header_check
    found_headers = load_headers(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/root/Zeus-Scanner/lib/header_check/__init__.py", line 54, in load_headers
    req = requests.get(url, params=header_value, proxies=proxy)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='www.microsofttranslator.com', port=80): Max retries exceeded with url: /bv.aspx?ref=SERP%0A&connection=close&user-agent=Zeus-Scanner%2F1.2.2+%28Language%3DPython%2F2.7.14%3B+Platform%3DLinux%29 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fae9ba245d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

2017-11-10 23:39:23,970;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-10 23:39:23,970;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-10 23:39:23,971;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-10 23:39:23,971;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/d4d6630f59aeb4908e22073303f9f12aa46dd300
