### ISSUE TITLE
OSError: [Errno 8] Exec format error (FjsgKHL)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#143]
Zeus version:
`1.2.8`

Firefox version:
`(52, 4)`

Geckodriver version:
`geckodriver-v0.17.0-linux32.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/root/Soft/zeus-scanner/var/google_search/search.py", line 394, in parse_search_results
    tor=tor, batch=batch
  File "/root/Soft/zeus-scanner/var/google_search/search.py", line 218, in get_urls
    browser = webdriver.Firefox(profile, proxy=proxy_to_use)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
````

Running details:
`Linux-3.10.107-perf-aarch64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`zeus.py -r -s`

Log file info:
```2017-11-13 15:00:23,827;zeus-log;INFO;log file being saved to '/root/Soft/zeus-scanner/log/zeus-log-8.log'...
2017-11-13 15:00:23,829;zeus-log;INFO;using default search engine...
2017-11-13 15:00:23,834;zeus-log;INFO;using random dork 'inurl:general.php?middle=' as the search query...
2017-11-13 15:00:23,834;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-11-13 15:00:23,835;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-11-13 15:00:23,836;zeus-log;INFO;attempting to gather query URL...
2017-11-13 15:00:24,060;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-11-13 15:00:24,061;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-11-13 15:00:24,099;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception '[Errno 8] Exec format error' exception has been logged to current log file...
Traceback (most recent call last):
  File "/root/Soft/zeus-scanner/var/google_search/search.py", line 394, in parse_search_results
    tor=tor, batch=batch
  File "/root/Soft/zeus-scanner/var/google_search/search.py", line 218, in get_urls
    browser = webdriver.Firefox(profile, proxy=proxy_to_use)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

2017-11-13 15:00:30,705;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-13 15:00:30,707;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-13 15:00:30,716;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-13 15:00:30,718;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
This has to do with the binary, so let me do some research and I’ll get this done

**Comment by Ekultek** [comment]
should be patched via https://github.com/Ekultek/Zeus-Scanner/commit/d4c1e2dc1c1e9665207d66115bd6328cd67bbe59
