### ISSUE TITLE
urlparse

### ISSUE THREAD

**Issue by rexortas** [Ekultek/Zeus-Scanner#15]
[*] starting up at 20:22:21..

[20:22:21 INFO] log file being saved to '/home/username/Downloads/Zeus-Scanner/log/zeus-log-48.log'...
[20:22:21 INFO] using default search engine...
[20:22:21 CRITICAL] failed to provide a mandatory argument, you will be redirected to the help menu...
Traceback (most recent call last):
  File "zeus.py", line 16, in <module>
    from lib.attacks.xss_scan import main_xss
  File "/home/username/Downloads/Zeus-Scanner/lib/attacks/xss_scan/__init__.py", line 3, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'

At start I get a strange error. Help me to understand. I'm using python 2.7

**Comment by Ekultek** [comment]
You’re not using python 2.7 then, urlparse is a standard library.

Try opening IDLE and doing:

```
import urllib.parse
```

I’m thinking that this is compatibility problems

**Comment by rexortas** [comment]
$ python2
Python 2.7.14 (default, Sep 20 2017, 01:25:59) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib.parse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named parse

**Comment by rexortas** [comment]
"import urlparse" in IDLE is worked

**Comment by Ekultek** [comment]
Alright now run `sudo python2 zeus.py —verbose`

- Thomas Perkins

**Comment by Ekultek** [comment]
and?

**Comment by rexortas** [comment]
$ sudo python2 zeus.py --verbose
[09:44:14 DEBUG] checking if the application has been run before...
[09:44:14 DEBUG] verifying operating system...
[09:44:14 DEBUG] already ran, skipping...

    __          __________                             __   
   / /          \____    /____  __ __  ______          \ \  
  / /    ______   /     // __ \|  |  \/  ___/  ______   \ \ 
  \ \   /_____/  /     /\  ___/|  |  /\___ \  /_____/   / / 
   \_\          /_______ \___  >____//____  >          /_/  
                       \/   \/           \/  v1.0.19.8e6fa(revision)
        https://github.com/ekultek/zeus-scanner.git
                Advanced Dork Searching...


[*] starting up at 09:44:14..


[09:44:14 DEBUG] running with options '{'runInVerbose': True}'...
[09:44:14 INFO] log file being saved to '/home/username/Downloads/Zeus-Scanner/log/zeus-log-51.log'...
[09:44:14 DEBUG] using default search engine (Google)...
[09:44:14 INFO] using default search engine...
[09:44:14 CRITICAL] failed to provide a mandatory argument, you will be redirected to the help menu...
Traceback (most recent call last):
  File "zeus.py", line 16, in <module>
    from lib.attacks.xss_scan import main_xss
  File "/home/username/Downloads/Zeus-Scanner/lib/attacks/xss_scan/__init__.py", line 3, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'


[*] shutting down at 09:44:19..

**Comment by Ekultek** [comment]
this is an issue on your side. I am unable to reproduce it, try reinstalling python, my best guess is that somewhere on your system you either have a file name `urlparse` and python is trying to pull from that, or your python version is bad.

- Try re-installing python 
- Try to see if you have a file named urlparse

There's not much I can do about this, I am sorry.
