### ISSUE TITLE
 [04:23:52 CRITICAL] your current firefox version is not supported by Zeus...

### ISSUE THREAD

**Issue by mayday77** [Ekultek/Zeus-Scanner#151]
# What's the problem
[04:23:52 INFO] seems this is your first time running the application, doing setup please wait...
[04:23:52 INFO] attempting to get firefox browser version...
[04:23:52 ERROR] failed to run firefox...
[04:23:52 CRITICAL] your current firefox version is not supported by Zeus...

# Running context
Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

 - Operating system:
 
 - Zeus version: v1.2.15(dev)

# Any idea on a solution?
Was reinstall a firefox , latest version. Still no luck

# Full console commands run

# Stacktrace (if applicable)

# Full file log information
root@kali:~/Downloads/Zeus-Scanner# ./zeus.py --verbose
[04:24:36 DEBUG] checking if the application has been run before...
[04:24:36 DEBUG] verifying operating system...
Attacking targets without consent is not only illegal, but it is unethical and frowned upon in most countries. By installing this program you are agreeing that you are responsible for your own actions, you are over the age of 18 or legally considered an adult in your place of origin, and that you will obey all laws, regulations, and rules set forth by your place of origin. You will only see this disclaimer once. If you agree to the conditions type 'yes'...yes
[04:24:39 INFO] seems this is your first time running the application, doing setup please wait...
[04:24:39 DEBUG] checking if xvfb is on your system...
[04:24:39 INFO] attempting to get firefox browser version...
[04:24:39 ERROR] failed to run firefox...
[04:24:39 CRITICAL] your current firefox version is not supported by Zeus...

**Comment by Ekultek** [comment]
What's the problem? Zeus can only support Firefox versions 51 - 56.

If you are getting this error you need to downgrade/upgrade firefox. To get your browser version do something like this:

```
baal@baal-Aspire-5733Z:~/bin/python/zeus-scanner$ firefox --version
Mozilla Firefox 56.0
baal@baal-Aspire-5733Z:~/bin/python/zeus-scanner$ 
```

To upgrade firefox:

```
$ for pid in $(ps -ef | grep "firefox" | awk '{print $2}'); do kill -9 ${pid}; done > /dev/null 2>&1  # kill all firefox instances
$ mv ~/.mozilla ~/.mozilla.old  # wipe your profile to prevent any issues, this way you can always reinstate it after the installation
$ sudo apt-get update  # update apt
$ sudo apt-get --purge --reinstall install firefox  # re-install firefox to the latest version
```

That should fix this issue for you. I'll leave this open for 24 hours just in case you have any questions

**Comment by mayday77** [comment]
firefox  55 (64 ) 
[09:25:30 INFO] seems this is your first time running the application, doing setup please wait...
[09:25:30 INFO] attempting to get firefox browser version...
[09:25:30 ERROR] failed to run firefox...
[09:25:30 CRITICAL] your current firefox version is not supported by Zeus...
The same  =(((
Sorry

**Comment by Ekultek** [comment]
Run firefox—version

Post the whole command

- Thomas Perkins

**Comment by Ekultek** [comment]
Wait I think I see the problem

- Thomas Perkins

**Comment by Ekultek** [comment]
Do me a favor and run `firefox --version` post the entire command output

**Comment by mayday77** [comment]
Problem is when i trying to make friefox --version ,firefox opened and no output  on to terminal =( But , in About windows i can see version is 55

**Comment by Ekultek** [comment]
Alright I know what's going on

**Comment by Ekultek** [comment]
should be patched via https://github.com/Ekultek/Zeus-Scanner/commit/7747c7fb8e9cf6da405160c744702871f7e3b9fe re-install

**Comment by mayday77** [comment]
09:55:51 INFO] seems this is your first time running the application, doing setup please wait...
[09:55:51 INFO] attempting to get firefox browser version...
[09:55:51 ERROR] failed to run firefox...
[09:55:51 PROMPT] enter your firefox browser version (if you don't know it run firefox --version 56.0
[09:55:58 CRITICAL] your current firefox version is not supported by Zeus...


[*] shutting down at 09:55:58..

**Comment by Ekultek** [comment]
Enter just 56

**Comment by mayday77** [comment]
[10:06:07 INFO] seems this is your first time running the application, doing setup please wait...
[10:06:07 INFO] attempting to get firefox browser version...
[10:06:07 ERROR] failed to run firefox...
[10:06:07 PROMPT] enter your firefox browser version (if you don't know it run firefox --version 56
[10:06:10 CRITICAL] your current firefox version is not supported by Zeus...


[*] shutting down at 10:06:10..

**Comment by Ekultek** [comment]
Hopefully https://github.com/Ekultek/Zeus-Scanner/commit/95e6ab3c709d1ce6235ad3e75b7734ee60d02afb should do it. It should accept the string as the browser version now. and you should be able to use `56.0` or `56`

**Comment by mayday77** [comment]
56 
10:17:06 INFO] seems this is your first time running the application, doing setup please wait...
[10:17:06 INFO] attempting to get firefox browser version...
[10:17:06 ERROR] failed to run firefox...
[10:17:06 PROMPT] enter your firefox browser version (if you don't know it run firefox --version 56
[10:17:08 INFO] done, continuing process...

    __          __________                             __   
   / /          \____    /____  __ __  ______          \ \  
  / /    ______   /     // __ \|  |  \/  ___/  ______   \ \ 
  \ \   /_____/  /     /\  ___/|  |  /\___ \  /_____/   / / 
   \_\          /_______ \___  >____//____  >          /_/  
                       \/   \/           \/  v1.2.18.95e6ab(revision)
	https://github.com/ekultek/zeus-scanner.git
		Advanced Dork Searching...


[*] starting up at 10:17:08..


[10:17:08 INFO] log file being saved to '/root/Downloads/Zeus-Scanner/log/zeus-log-1.log'...
[10:17:08 INFO] using default search engine...
[10:17:08 CRITICAL] failed to provide a mandatory argument, you will be redirected to the help menu...
Usage: zeus.py -d|r|l|f|b| DORK|FILE|URL [ATTACKS] [--OPTS]

Options:
  -h, --help            show this help message and exit

  Mandatory Options:
    These options have to be used in order for Zeus to run

    -d DORK, --dork=DORK
                        Specify a singular Google dork to use for queries
    -l FILE-PATH, --dork-list=FILE-PATH
                        Specify a file full of dorks to run through
    -r, --rand-dork     Use a random dork from the etc/dorks.txt file to
                        perform the scan
    -b URL, --blackwidow=URL
                        Spider a single webpage for all available URL's
    -f FILE-PATH, --url-file=FILE-PATH
                        Run an attack on URL's in a given file

  Attack arguments:
    These arguments will give you the choice on how you want to check the
    websites

    -s, --sqli          Run a Sqlmap SQLi scan on the discovered URL's
    -p, --port-scan     Run a Nmap port scan on the discovered URL's
    -a, --admin-panel   Search for the websites admin panel
    -x, --xss-scan      Run an XSS scan on the found URL's
    -w, --whois-lookup  Perform a WhoIs lookup on the provided domain
    -c, --clickjacking  Perform a clickjacking scan on a provided URL
    --sqlmap-args=SQLMAP-ARGS
                        Pass the arguments to send to the sqlmap API within
                        quotes & separated by a comma. IE 'dbms mysql, verbose
                        3, level 5'
    --sqlmap-conf=CONFIG-FILE-PATH
                        Pass a configuration file that contains the sqlmap
                        arguments
    --nmap-args=NMAP-ARGS
                        Pass the arguments to send to the nmap API within
                        quotes & separated by a pipe. IE '-O|-p 445, 1080'
    --show-sqlmap       Show the arguments that the sqlmap API understands
    --show-nmap         Show the arguments that nmap understands
    -P, --show-possibles
                        Show all connections made during the admin panel
                        search
    --tamper=TAMPER-SCRIPT
                        Send the XSS payloads through tampering before sending
                        to the target
    --thread            Run multiple threads on functions that support multi-
                        threading
    --auto              Automatically start the sqlmap API (or at least try
                        to)

  Search options:
    Arguments that will control the search criteria

    -L HOW-MANY-LINKS, --links=HOW-MANY-LINKS
                        Specify how many links to try and search on Google
    -M, --multi         Search multiple pages of Google
    -E, --exclude-none  Do not exclude URLs because they do not have a
                        GET(query) parameter in them
    -W, --webcache      Parse webcache URLs for the redirect in them
    --x-forward         Add a header called 'X-Forwarded-For' with three
                        random IP addresses
    --time-sec=SECONDS  Control the sleep time to the WhoIS lookup to prevent
                        errors

  Anonymity arguments:
    Arguments that help with anonymity and hiding identity

    --proxy=PROXY-STRING
                        Use a proxy to do the scraping, will not auto
                        configure to the API's
    --proxy-file=FILE-PATH
                        Grab a random proxy from a given file of proxies
    --random-agent      Use a random user-agent from the etc/agents.txt file
    --agent=USER-AGENT  Use your own personal user-agent
    --tor               Use Tor connection as the proxy and set the firefox
                        browser settings to mimic Tor

  Search engine arguments:
    Arguments to change the search engine used (default is Google)

    -D, --search-engine-ddg
                        Use DuckDuckGo as the search engine
    -B, --search-engine-bing
                        Use Bing as the search engine
    -A, --search-engine-aol
                        Use AOL as the search engine

  Misc Options:
    These options affect how the program will run

    --verbose           Run the application in verbose mode (more output)
    --show-requests     Show all HTTP requests made by the application
    --batch             Skip the questions and run in default batch mode
    --update            Update to the latest development version
    --hide              Hide the banner during running
    --version           Show the current version and exit
    -T THREAD-AMOUNT, --x-threads=THREAD-AMOUNT
                        Specify how many threads you want to pass
    --show-success      Calculate the dorks success rate and output the
                        calculation in human readable form


[*] shutting down at 10:17:10..

**Comment by Ekultek** [comment]
Right on man, have fun. I’ll leave this open for 24 hours in case you have other questions

**Comment by mayday77** [comment]
Fck!
can i donate ? Bitcoins ?

root@kali:~/Downloads/Zeus-Scanner# ./zeus.py -d indexp.php?id=books

    __          __________                             __   
   / /          \____    /____  __ __  ______          \ \  
  / /    ______   /     // __ \|  |  \/  ___/  ______   \ \ 
  \ \   /_____/  /     /\  ___/|  |  /\___ \  /_____/   / / 
   \_\          /_______ \___  >____//____  >          /_/  
                       \/   \/           \/  v1.2.18.95e6ab(revision)
	https://github.com/ekultek/zeus-scanner.git
		Advanced Dork Searching...


[*] starting up at 10:19:32..


[10:19:32 INFO] log file being saved to '/root/Downloads/Zeus-Scanner/log/zeus-log-3.log'...
[10:19:32 INFO] using default search engine...
[10:19:32 INFO] starting dork scan with query 'indexp.php?id=books'...
[10:19:32 WARNING] will not parse webcache URL's (to parse webcache pass -W)...
[10:19:32 WARNING] only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
[10:19:32 INFO] attempting to gather query URL...
[10:19:32 INFO] firefox browser display will be hidden while it performs the query...
[10:19:32 WARNING] your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
[10:19:33 ERROR] search.pyc failed to gather the URL from search engine, caught exception 'Message: Unable to find a matching set of capabilities' exception has been logged to current log file...
Traceback (most recent call last):
  File "/root/Downloads/Zeus-Scanner/var/google_search/search.py", line 413, in parse_search_results
    tor=tor, batch=batch
  File "/root/Downloads/Zeus-Scanner/var/google_search/search.py", line 223, in get_urls
    browser = webdriver.Firefox(profile, proxy=proxy_to_use)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Unable to find a matching set of capabilities

[10:19:33 ERROR] ran into exception 'Unable to determine SOCKS version from socks://127.0.0.1:9050/'...
Traceback (most recent call last):
  File "./zeus.py", line 336, in <module>
    show_success=opt.showSuccessRate
  File "/root/Downloads/Zeus-Scanner/var/google_search/search.py", line 491, in parse_search_results
    request_issue_creation()
  File "/root/Downloads/Zeus-Scanner/var/auto_issue/github.py", line 32, in request_issue_creation
    if not lib.core.settings.get_md5sum():
  File "/root/Downloads/Zeus-Scanner/lib/core/settings.py", line 689, in get_md5sum
    posted_checksum = requests.get(url).content
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 390, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 290, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 184, in proxy_manager_for
    **proxy_kwargs
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/socks.py", line 160, in __init__
    "Unable to determine SOCKS version from %s" % proxy_url
ValueError: Unable to determine SOCKS version from socks://127.0.0.1:9050/
[10:19:33 ERROR] ran into exception 'Unable to determine SOCKS version from socks://127.0.0.1:9050/' exception has been saved to log file...
Traceback (most recent call last):
  File "./zeus.py", line 348, in <module>
    request_issue_creation()
  File "/root/Downloads/Zeus-Scanner/var/auto_issue/github.py", line 32, in request_issue_creation
    if not lib.core.settings.get_md5sum():
  File "/root/Downloads/Zeus-Scanner/lib/core/settings.py", line 689, in get_md5sum
    posted_checksum = requests.get(url).content
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 390, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 290, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 184, in proxy_manager_for
    **proxy_kwargs
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/socks.py", line 160, in __init__
    "Unable to determine SOCKS version from %s" % proxy_url
ValueError: Unable to determine SOCKS version from socks://127.0.0.1:9050/
Traceback (most recent call last):
  File "./zeus.py", line 568, in <module>
    request_issue_creation()
  File "/root/Downloads/Zeus-Scanner/var/auto_issue/github.py", line 32, in request_issue_creation
    if not lib.core.settings.get_md5sum():
  File "/root/Downloads/Zeus-Scanner/lib/core/settings.py", line 689, in get_md5sum
    posted_checksum = requests.get(url).content
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 390, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 290, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 184, in proxy_manager_for
    **proxy_kwargs
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/socks.py", line 160, in __init__
    "Unable to determine SOCKS version from %s" % proxy_url
ValueError: Unable to determine SOCKS version from socks://127.0.0.1:9050/
root@kali:~/Downloads/Zeus-Scanner#

**Comment by Ekultek** [comment]
Yes you can donate, see the README for the donations link.

And as for this, God damn it I'm gonna need some nicotine for this one. Give me a couple minutes

**Comment by Ekultek** [comment]
You installed the wrong driver version, I'm assuming that your firefox is extremely old since the `--version` flag isn't working. Run this:
```
$ for pid in $(ps -ef | grep "firefox" | awk '{print $2}'); do kill -9 ${pid}; done > /dev/null 2>&1&& mv ~/.mozilla ~/.mozilla.old && sudo apt-get update && sudo apt-get --purge --reinstall install firefox=56.0 
```

**Comment by Ekultek** [comment]
As for the socks proxy error, do you have Tor running?

**Comment by Ekultek** [comment]
Socks proxies require the socks type. Tor is socks5 so it would look like this:

```
root@baal-Aspire-5733Z:~/bin/python/zeus-scanner# python zeus.py -r --proxy socks5://127.0.0.1:9050

    __          __________                             __   
   / /          \____    /____  __ __  ______          \ \  
  / /    ______   /     // __ \|  |  \/  ___/  ______   \ \ 
  \ \   /_____/  /     /\  ___/|  |  /\___ \  /_____/   / / 
   \_\          /_______ \___  >____//____  >          /_/  
                       \/   \/           \/  v1.2.18.95e6ab(revision)
        https://github.com/ekultek/zeus-scanner.git
                Advanced Dork Searching...


[*] starting up at 09:29:58..


[09:29:58 INFO] log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-10.log'...
[09:29:58 INFO] using default search engine...
[09:29:58 INFO] using random dork 'filetype:pwd service' as the search query...
[09:29:58 WARNING] will not parse webcache URL's (to parse webcache pass -W)...
[09:29:58 WARNING] only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
[09:29:58 INFO] attempting to gather query URL...
[09:29:58 INFO] firefox browser display will be hidden while it performs the query...
[09:29:58 WARNING] your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...

```

**Comment by Ekultek** [comment]
[here](https://github.com/Ekultek/Zeus-Scanner#donations) is the donations link if you want to donate.

**Comment by Ekultek** [comment]
@mayday77 I’ll give you 24 hours in case any other issues arise and then I’ll close this down

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/8b3a776af461c6216531b106ca569a8d2e14fefb

**Comment by Ekultek** [comment]
What will happen now once this error is hit:

    All firefox sessions will be killed
    Mozilla profile will be cached
    Mozilla will be reinstalled to version 56.0
    selenium will be reinstalled and upgraded to the latest version
    program will rewrite all it's paths so it will attempt to reinstall itself again

**Comment by mayday77** [comment]
root@kali:~/Downloads/Zeus-Scanner# sudo ./zeus.py --dork index.php?id=1
Attacking targets without consent is not only illegal, but it is unethical and frowned upon in most countries. By installing this program you are agreeing that you are responsible for your own actions, you are over the age of 18 or legally considered an adult in your place of origin, and that you will obey all laws, regulations, and rules set forth by your place of origin. You will only see this disclaimer once. If you agree to the conditions type 'yes'...yes
[08:53:39 INFO] seems this is your first time running the application, doing setup please wait...
[08:53:39 INFO] attempting to get firefox browser version...
[08:53:39 ERROR] failed to run firefox...
[08:53:39 PROMPT] enter your firefox browser version (if you don't know it run firefox --version 56
[08:53:42 INFO] done, continuing process...

    __          __________                             __   
   / /          \____    /____  __ __  ______          \ \  
  / /    ______   /     // __ \|  |  \/  ___/  ______   \ \ 
  \ \   /_____/  /     /\  ___/|  |  /\___ \  /_____/   / / 
   \_\          /_______ \___  >____//____  >          /_/  
                       \/   \/           \/  v1.2.19.8b3a77(revision)
	https://github.com/ekultek/zeus-scanner.git
		Advanced Dork Searching...


[*] starting up at 08:53:42..


[08:53:42 INFO] log file being saved to '/root/Downloads/Zeus-Scanner/log/zeus-log-5.log'...
[08:53:42 INFO] using default search engine...
[08:53:42 INFO] starting dork scan with query 'index.php?id=1'...
[08:53:42 WARNING] will not parse webcache URL's (to parse webcache pass -W)...
[08:53:42 WARNING] only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
[08:53:42 INFO] attempting to gather query URL...
[08:53:42 INFO] firefox browser display will be hidden while it performs the query...
[08:53:42 WARNING] your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
[08:53:43 CRITICAL] it appears that firefox, selenium, and geckodriver are not playing nice with one another...
[08:53:43 PROMPT] would you like to attempt to resolve this issue automatically[y/N]: y
Requirement already up-to-date: selenium in /usr/local/lib/python2.7/dist-packages


[*] shutting down at 08:54:19..

**Comment by Ekultek** [comment]
So after you reinstall everything you get that?

**Comment by mayday77** [comment]
seems to be , Kali have an issue with firefox installed.

**Comment by Ekultek** [comment]
You need to find your browser version for me

**Comment by Ekultek** [comment]
It can’t be Kali, a lot of the users are using Kali and blackarch, so it can’t be Kali

**Comment by Ekultek** [comment]
So get your browser version, and let me know what it is. I  have a feeling that it’s not 56.

**Comment by mayday77** [comment]
Teamviewer ?

**Comment by mayday77** [comment]
56/02

**Comment by Ekultek** [comment]
Yeah, I’ve got some stuff to do first, I’ll let you know when i have a minute, give me about an hour

**Comment by mayday77** [comment]
Was re-instal FF again
[09:34:23 PROMPT] zeus was able to successfully extract the URL from Google's ban URL it is advised to shutdown zeus and attempt to extract the URL's manually. failing to do so will most likely result in no results being found by zeus. would you like to shutdown[y/N]: y
[09:35:01 INFO] successfully wrote found items to '/root/Downloads/Zeus-Scanner/log/extracted-url-log/extracted-url-1.log'...
[09:35:01 INFO] it is advised to extract the URL's from the produced URL written to the above (IE open the log, copy the url into firefox)...

=)))))))))))))))))))))))

**Comment by mayday77** [comment]
2017-11-16 09:45:42,600;zeus-log;INFO;log file being saved to '/root/Downloads/Zeus-Scanner/log/zeus-log-18.log'...
2017-11-16 09:45:42,600;zeus-log;INFO;specified to use non-default search engine...
2017-11-16 09:45:42,601;zeus-log;INFO;starting dork scan with query '*.php?id=133'...
2017-11-16 09:45:47,944;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-11-16 09:45:47,944;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-11-16 09:45:47,945;zeus-log;INFO;attempting to gather query URL...
2017-11-16 09:45:48,087;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-11-16 09:45:48,088;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-11-16 09:45:51,783;zeus-log;INFO;browser will open shortly...
2017-11-16 09:45:54,070;zeus-log;INFO;searching search engine using query 'http://duckduckgo.com/html'...
2017-11-16 09:45:57,271;zeus-log;INFO;closing the browser and continuing process..
2017-11-16 09:45:57,332;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-11-16 09:45:57,332;zeus-log;INFO;no proxy configuration detected...
2017-11-16 09:45:59,051;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner/1.2.19.8b3a77 (Language=Python/2.7.14; Platform=Linux)'...
2017-11-16 09:45:59,056;zeus-log;INFO;successfully wrote found items to '/root/Downloads/Zeus-Scanner/log/url-log/url-log-1.log'...
2017-11-16 09:45:59,057;zeus-log;INFO;found a total of 2 URLs with given query '*.php?id=133'...


parsed two links " 
http://duckduckgo.com/
https://duckduckgo.com/

**Comment by mayday77** [comment]
Much better with Bing 
total 17 links was found

**Comment by Ekultek** [comment]
Yes DDG is still a work in progress, it works but not as well as others. You should try -M -L 100 ;) 

As always this will remain open for 24 hours

**Comment by Ekultek** [comment]
Also, you can still use google as the search engine, just use a different dork. Example:

instead of:
```
python zeus.py -d inurl:php?id=10
```
use
```
python zeus.py -d php?id=10
```

Google will usually only pick up on them if you're using it's advanced search syntax. You can also try running with a random agent, and a proxy. Good way to find proxies see [here](https://github.com/stamparm/fetch-some-proxies)

**Comment by Ekultek** [comment]
Been about 24 hours, assuming no issues and closing
