### ISSUE TITLE
WebDriverException: Message: Unable to find a matching set of capabilities (LysVQfL)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#154]
Zeus version:
`1.2.18.95e6ab`

Firefox version:
`failed to start`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/root/Downloads/Zeus-Scanner/var/google_search/search.py", line 413, in parse_search_results
    tor=tor, batch=batch
  File "/root/Downloads/Zeus-Scanner/var/google_search/search.py", line 223, in get_urls
    browser = webdriver.Firefox(profile, proxy=proxy_to_use)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Unable to find a matching set of capabilities
````

Running details:
`Linux-4.6.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`./zeus.py --dork index.php?id=1`

Log file info:
```2017-11-16 01:19:27,741;zeus-log;INFO;log file being saved to '/root/Downloads/Zeus-Scanner/log/zeus-log-8.log'...
2017-11-16 01:19:27,742;zeus-log;INFO;using default search engine...
2017-11-16 01:19:27,742;zeus-log;INFO;starting dork scan with query 'index.php?id=1'...
2017-11-16 01:19:27,742;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-11-16 01:19:27,742;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-11-16 01:19:27,742;zeus-log;INFO;attempting to gather query URL...
2017-11-16 01:19:27,862;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-11-16 01:19:27,863;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-11-16 01:19:29,027;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception 'Message: Unable to find a matching set of capabilities' exception has been logged to current log file...
Traceback (most recent call last):
  File "/root/Downloads/Zeus-Scanner/var/google_search/search.py", line 413, in parse_search_results
    tor=tor, batch=batch
  File "/root/Downloads/Zeus-Scanner/var/google_search/search.py", line 223, in get_urls
    browser = webdriver.Firefox(profile, proxy=proxy_to_use)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Unable to find a matching set of capabilities


2017-11-16 01:19:39,965;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-16 01:19:39,966;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-16 01:19:39,974;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-16 01:19:39,974;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
2017-11-16 01:19:39,986;zeus-log;ERROR;[7;31;31mfailed to run firefox...[0m
```

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/8b3a776af461c6216531b106ca569a8d2e14fefb

**Comment by Ekultek** [comment]
What will happen now once this error is hit:

1) All firefox sessions will be killed
2) Mozilla profile will be cached
3) Mozilla will be reinstalled to version 56.0
4) selenium will be reinstalled and upgraded to the latest version
5) program will rewrite all it's paths so it will attempt to reinstall itself again
