### ISSUE TITLE
IOError: [Errno 13] Permission denied: '/home/sohan/pentest/zeus-scanner/log/blacklist/.blacklist' (gfeMOcw)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#155]
Zeus version:
`1.2.19.8b3a77`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.17.0-linux64.tar.gzgeckodriver-v0.17.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 336, in <module>
    show_success=opt.showSuccessRate
  File "/home/sohan/pentest/zeus-scanner/var/google_search/search.py", line 356, in parse_search_results
    parse_blacklist(query, BLACKLIST_FILE_PATH, batch=batch)
  File "/home/sohan/pentest/zeus-scanner/lib/core/settings.py", line 1052, in parse_blacklist
    with open(full_path, "a+") as log:
IOError: [Errno 13] Permission denied: '/home/sohan/pentest/zeus-scanner/log/blacklist/.blacklist'
````

Running details:
`Linux-4.8.0-36-generic-x86_64-with-Ubuntu-16.04-xenial`

Commands used:
`zeus.py -d hello --verbose`

Log file info:
```2017-11-16 20:58:14,735;zeus-log;DEBUG;checking if the application has been run before...
2017-11-16 20:58:14,735;zeus-log;DEBUG;verifying operating system...
2017-11-16 20:58:14,735;zeus-log;DEBUG;already ran, skipping...
2017-11-16 20:58:14,735;zeus-log;DEBUG;running with options '{'runInVerbose': True, 'dorkToUse': 'hello'}'...
2017-11-16 20:58:14,735;zeus-log;INFO;log file being saved to '/home/sohan/pentest/zeus-scanner/log/zeus-log-10.log'...
2017-11-16 20:58:14,735;zeus-log;DEBUG;using default search engine (Google)...
2017-11-16 20:58:14,735;zeus-log;INFO;using default search engine...
2017-11-16 20:58:14,735;zeus-log;INFO;starting dork scan with query 'hello'...
2017-11-16 20:58:14,735;zeus-log;DEBUG;parsing blacklist...
2017-11-16 20:58:14,735;zeus-log;ERROR;[7;31;31mran into exception '[Errno 13] Permission denied: '/home/sohan/pentest/zeus-scanner/log/blacklist/.blacklist''...
Traceback (most recent call last):
  File "zeus.py", line 336, in <module>
    show_success=opt.showSuccessRate
  File "/home/sohan/pentest/zeus-scanner/var/google_search/search.py", line 356, in parse_search_results
    parse_blacklist(query, BLACKLIST_FILE_PATH, batch=batch)
  File "/home/sohan/pentest/zeus-scanner/lib/core/settings.py", line 1052, in parse_blacklist
    with open(full_path, "a+") as log:
IOError: [Errno 13] Permission denied: '/home/sohan/pentest/zeus-scanner/log/blacklist/.blacklist'

2017-11-16 20:58:24,284;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-16 20:58:24,285;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-16 20:58:24,286;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-16 20:58:24,286;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
Your permissions are affecting you, run with sudo and it’ll work

**Comment by Ekultek** [comment]
But i should probably catch this

**Comment by Ekultek** [comment]
catch via https://github.com/Ekultek/Zeus-Scanner/commit/08f1f83b74a2b887d9931439721f4e14add853dd will tell you to run with sudo
