### ISSUE TITLE
Exception: random error (zrAdYuy)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#156]
Zeus version:
`1.2.20.08f1f8`

Firefox version:
`(56, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/var/google_search/search.py", line 415, in parse_search_results
    tor=tor, batch=batch
  File "/home/baal/bin/python/zeus-scanner/var/google_search/search.py", line 168, in get_urls
    raise Exception("random error")
Exception: random error
````

Running details:
`Linux-4.10.0-38-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:php?id=10`

Log file info:
```2017-11-16 09:35:33,725;zeus-log;INFO;log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-40.log'...
2017-11-16 09:35:33,728;zeus-log;INFO;using default search engine...
2017-11-16 09:35:33,728;zeus-log;INFO;starting dork scan with query 'inurl:php?id=10'...
2017-11-16 09:35:33,728;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-11-16 09:35:33,729;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-11-16 09:35:33,729;zeus-log;INFO;attempting to gather query URL...
2017-11-16 09:35:33,729;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception 'random error' exception has been logged to current log file...
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/var/google_search/search.py", line 415, in parse_search_results
    tor=tor, batch=batch
  File "/home/baal/bin/python/zeus-scanner/var/google_search/search.py", line 168, in get_urls
    raise Exception("random error")
Exception: random error

2017-11-16 09:35:35,310;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-16 09:35:35,311;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-16 09:35:35,311;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-16 09:35:35,311;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
testing
