### ISSUE TITLE
WebDriverException: Message: 'geckodriver' executable needs to be in PATH.  (dEsDlQm)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#159]
Zeus version:
`1.2.21.8b57b6`

Firefox version:
`(52, 4)`

Geckodriver version:
`geckodriver-v0.17.0-linux64.tar.gzgeckodriver-v0.17.0-linux64.tar.gzgeckodriver-v0.17.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/test/Desktop/Git/Zeus-Scanner/var/google_search/search.py", line 414, in parse_search_results
    tor=tor, batch=batch
  File "/home/test/Desktop/Git/Zeus-Scanner/var/google_search/search.py", line 224, in get_urls
    browser = webdriver.Firefox(profile, proxy=proxy_to_use)
  File "/home/test/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/home/test/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
````

Running details:
`Linux-4.8.0-kali2-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`./zeus.py -d inurl:php?id=`

Log file info:
```2017-11-18 19:45:04,935;zeus-log;INFO;log file being saved to '/home/test/Desktop/Git/Zeus-Scanner/log/zeus-log-10.log'...
2017-11-18 19:45:04,935;zeus-log;INFO;using default search engine...
2017-11-18 19:45:04,935;zeus-log;INFO;starting dork scan with query 'inurl:php?id='...
2017-11-18 19:45:04,935;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-11-18 19:45:04,936;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-11-18 19:45:04,936;zeus-log;INFO;attempting to gather query URL...
2017-11-18 19:45:05,058;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-11-18 19:45:05,058;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-11-18 19:45:05,121;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception 'Message: 'geckodriver' executable needs to be in PATH.' exception has been logged to current log file...
Traceback (most recent call last):
  File "/home/test/Desktop/Git/Zeus-Scanner/var/google_search/search.py", line 414, in parse_search_results
    tor=tor, batch=batch
  File "/home/test/Desktop/Git/Zeus-Scanner/var/google_search/search.py", line 224, in get_urls
    browser = webdriver.Firefox(profile, proxy=proxy_to_use)
  File "/home/test/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/home/test/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 


2017-11-18 19:45:14,085;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-18 19:45:14,085;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-18 19:45:14,085;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-18 19:45:14,085;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/7d8727b9dfd63afcd8685d9241c46a339bd9e073
