### ISSUE TITLE
WebDriverException: Message: Can not connect to the Service /usr/bin/geckodriver (qXPOUrh)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#161]
Zeus version:
`1.2.26`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/ubuntu/zeus-scanner/var/google_search/search.py", line 421, in parse_search_results
    tor=tor, batch=batch
  File "/home/ubuntu/zeus-scanner/var/google_search/search.py", line 244, in get_urls
    browser = webdriver.Firefox(profile, executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 102, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
WebDriverException: Message: Can not connect to the Service /usr/bin/geckodriver
````

Running details:
`Linux-4.4.0-1038-aws-x86_64-with-Ubuntu-16.04-xenial`

Commands used:
`zeus.py -d php?catid= --thread 10 --tor`

Log file info:
```2017-11-21 08:43:04,398;zeus-log;INFO;log file being saved to '/home/ubuntu/zeus-scanner/log/zeus-log-37.log'...
2017-11-21 08:43:04,398;zeus-log;INFO;using default search engine...
2017-11-21 08:43:04,398;zeus-log;INFO;starting dork scan with query 'php?catid='...
2017-11-21 08:43:04,398;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-11-21 08:43:04,398;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-11-21 08:43:04,399;zeus-log;INFO;attempting to gather query URL...
2017-11-21 08:43:04,399;zeus-log;WARNING;using Google with tor will most likely result in a ban URL...
2017-11-21 08:43:04,521;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-11-21 08:43:04,521;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-11-21 08:43:04,523;zeus-log;INFO;setting tor browser settings...
2017-11-21 08:50:52,040;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception 'Message: Can not connect to the Service /usr/bin/geckodriver' exception has been logged to current log file...
Traceback (most recent call last):
  File "/home/ubuntu/zeus-scanner/var/google_search/search.py", line 421, in parse_search_results
    tor=tor, batch=batch
  File "/home/ubuntu/zeus-scanner/var/google_search/search.py", line 244, in get_urls
    browser = webdriver.Firefox(profile, executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 102, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
WebDriverException: Message: Can not connect to the Service /usr/bin/geckodriver


2017-11-21 08:51:14,984;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-21 08:51:15,933;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-21 08:51:17,248;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-21 08:51:17,699;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
Do you have `127.0.0.1 localhost` in `/etc/hosts`?

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/d875092c6cf175c0606d30551ac9593b0e334b7b will check if the correct connection is written to /etc/hosts and write it if it isn't
