### ISSUE TITLE
Unhandled exception (KqxfErQ)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#175]
Zeus version:
`1.2.41.4c496b`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 292, in __run_attacks_main
    proxy=proxy_to_use, xforward=opt.forwardedForRandomIP
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 269, in main_header_check
    return write_to_log_file(protection, HEADER_RESULT_PATH, HEADERS_FILENAME.format(replace_http(url)))
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 161, in write_to_log_file
    json.dump(data_to_write, log, sort_keys=True, indent=4)
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xed in position 34: invalid continuation byte
````

Running details:
`Linux-4.10.0-38-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -r -M --verbose --random-agent -a --batch -L 300`

Log file info:
```2017-11-27 14:25:06,416;zeus-log;DEBUG;loading script 'stringray'...
2017-11-27 14:25:06,417;zeus-log;DEBUG;loading script 'squid'...
2017-11-27 14:25:06,513;zeus-log;DEBUG;loading script 'wallarm'...
2017-11-27 14:25:06,514;zeus-log;DEBUG;loading script 'yunsuo'...
2017-11-27 14:25:06,546;zeus-log;DEBUG;loading script 'anquanbao'...
2017-11-27 14:25:06,549;zeus-log;DEBUG;loading script 'generic'...
2017-11-27 14:25:06,549;zeus-log;WARNING;the target URL WAF/IDS/IPS has been identified as 'Amazon Web Services Web Application Firewall (Amazon)'...
2017-11-27 14:25:06,550;zeus-log;DEBUG;loading XML data...
2017-11-27 14:25:06,550;zeus-log;INFO;attempting to get request headers for 'http://www.consultoras.org/download-file.php?idf=28513'...
2017-11-27 14:25:07,807;zeus-log;INFO;found a request cookie, saving to file...
2017-11-27 14:25:07,814;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/www.consultoras.org-cookie.log'...
2017-11-27 14:25:07,858;zeus-log;DEBUG;fetched {'Content-disposition': 'attachment; filename="La Consultor\xeda Espa\xf1ola - El Sector en Cifras 2016 (English).pdf"', 'Transfer-Encoding': 'chunked', 'Set-Cookie': 'PHPSESSID=54a2bc49d356d3753f7d6cae958bba96; path=/', 'Expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'Keep-Alive': 'timeout=3, max=300', 'Server': 'Apache', 'Connection': 'Keep-Alive', 'Pragma': 'no-cache', 'Cache-Control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Date': 'Mon, 27 Nov 2017 20:25:07 GMT', 'Content-Type': 'application/octet-stream'}...
2017-11-27 14:25:07,859;zeus-log;INFO;writing found headers to log file...
2017-11-27 14:25:07,861;zeus-log;ERROR;[7;31;31mran into exception ''utf8' codec can't decode byte 0xed in position 34: invalid continuation byte' exception has been saved to log file...
Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 292, in __run_attacks_main
    proxy=proxy_to_use, xforward=opt.forwardedForRandomIP
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 269, in main_header_check
    return write_to_log_file(protection, HEADER_RESULT_PATH, HEADERS_FILENAME.format(replace_http(url)))
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 161, in write_to_log_file
    json.dump(data_to_write, log, sort_keys=True, indent=4)
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xed in position 34: invalid continuation byte

2017-11-27 14:47:38,472;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-27 14:47:38,473;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-27 14:47:38,557;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-27 14:47:38,558;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
Might just catch this and output that there was Unicode in it, and put what I can into a dict
