### ISSUE TITLE
Unhandled exception (pNHTwWF)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#179]
Zeus version:
`1.3.1.f1e3c5`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1014, in run_attacks
    pgp_main(url, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/var/search/pgp_search.py", line 185, in pgp_main
    return get_pgp_keys(urls, query, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/var/search/pgp_search.py", line 132, in get_pgp_keys
    timeout=10
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pgp.mit.edu', port=443): Read timed out. (read timeout=10)
````

Running details:
`Linux-4.10.0-38-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle: index of/admin --verbose -M -L 300 --x-forward --proxy=http://170.246.114.210:8080 -P --random-agent --batch`

Log file info:
```2017-11-28 11:51:43,981;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=vindex&search=0x5DDB4E87CD1738CA'...
2017-11-28 11:51:44,952;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=vindex&search=0x2AE53B2BB8F2E3AF'...
2017-11-28 11:51:45,505;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=get&search=0xA897A582B47E2BF6'...
2017-11-28 11:51:46,037;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=get&search=0x1573C764BCB173BC'...
2017-11-28 11:51:46,559;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=vindex&search=0xDBF98C529E87ABAA'...
2017-11-28 11:51:47,104;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=get&search=0xC0AB43396C54AB3E'...
2017-11-28 11:51:47,636;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=get&search=0x5101B6E8D19D24BE'...
2017-11-28 11:51:58,189;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code 'HTTPSConnectionPool(host='pgp.mit.edu', port=443): Read timed out. (read timeout=10)'...
Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1014, in run_attacks
    pgp_main(url, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/var/search/pgp_search.py", line 185, in pgp_main
    return get_pgp_keys(urls, query, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/var/search/pgp_search.py", line 132, in get_pgp_keys
    timeout=10
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pgp.mit.edu', port=443): Read timed out. (read timeout=10)

2017-11-28 11:53:07,037;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-28 11:53:07,038;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-28 11:53:07,079;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-28 11:53:07,084;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
should be fixed via https://github.com/Ekultek/Zeus-Scanner/commit/b12982a9582be2dd2139d85403d766eac9171d54
