### ISSUE TITLE
UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#18]
Error info:```Traceback (most recent call last):
  File "zeus.py", line 417, in <module>
    auto=opt.autoStartSqlmap, verbose=opt.runInVerbose, batch=opt.runInBatch
  File "zeus.py", line 380, in __run_attacks
    main_xss(url, verbose=verbose, proxy=proxy_to_use, agent=agent_to_use, tamper=opt.tamperXssPayloads)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 131, in main_xss
    filename = create_urls(start_url, payloads, tamper=tamper)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 86, in create_urls
    return tf_name, data
UnboundLocalError: local variable 'data' referenced before assignment
````

Running details:
`Linux-4.10.0-33-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d incontent:admin -x --verbose`

**Comment by Ekultek** [comment]
This is also just a test
