### ISSUE TITLE
Unhandled exception (XONiZAZ)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#191]
Zeus version:
`1.3.9.daa83f`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1002, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 171, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 117, in scan_xss
    xss_request = requests.get(url, proxies=config_proxy, headers=config_headers)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:cp.php?cl=cp nowmenuid= --batch --verbose -x --random-agent --x-forward -M -L 3000`

Log file info:
```2017-11-30 09:37:24,867;zeus-log;INFO;found a request cookie, saving to file...
2017-11-30 09:37:24,975;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/www.btydkj.com-cookie.log'...
2017-11-30 09:37:24,975;zeus-log;DEBUG;fetched {'X-Powered-By': 'PHP/5.4.45', 'Transfer-Encoding': 'chunked', 'Set-Cookie': 'PHPSESSID=q2q01lg229p9mbrig46tapuub7; path=/, language=cn; expires=Fri, 01-Dec-2017 15:38:24 GMT; path=/', 'Expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'Vary': 'Accept-Encoding', 'Server': 'nginx/1.13.3', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Date': 'Thu, 30 Nov 2017 15:37:24 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Encoding': 'gzip'}...
2017-11-30 09:37:24,975;zeus-log;INFO;writing found headers to log file...
2017-11-30 09:37:24,976;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.btydkj.com-headers.json'...
2017-11-30 09:37:24,994;zeus-log;INFO;loading payloads...
2017-11-30 09:37:25,020;zeus-log;DEBUG;a total of 296 payloads loaded...
2017-11-30 09:37:25,020;zeus-log;INFO;payloads will be written to a temporary file and read from there...
2017-11-30 09:37:25,023;zeus-log;INFO;loaded URL's have been saved to '/tmp/tmpL7HAdB'...
2017-11-30 09:37:25,023;zeus-log;INFO;testing for XSS vulnerabilities on host 'http://www.btydkj.com/cp.php?cl=cp&nowmenuid=11059665'...
2017-11-30 09:37:25,418;zeus-log;INFO;trying payload 'cl=cp&nowmenuid=11059665\x3c'...
2017-11-30 09:37:25,418;zeus-log;DEBUG;host 'http://www.btydkj.com/cp.php?cl=cp&nowmenuid=11059665' does not appear to be vulnerable to XSS attacks with payload 'cl=cp&nowmenuid=11059665\x3c'...
2017-11-30 09:37:25,827;zeus-log;INFO;trying payload 'cl=cp&nowmenuid=11059665\x3C'...
2017-11-30 09:37:25,828;zeus-log;DEBUG;host 'http://www.btydkj.com/cp.php?cl=cp&nowmenuid=11059665' does not appear to be vulnerable to XSS attacks with payload 'cl=cp&nowmenuid=11059665\x3C'...
2017-11-30 09:37:26,144;zeus-log;INFO;trying payload 'cl=cp&nowmenuid=11059665\u003c'...
2017-11-30 09:37:26,144;zeus-log;DEBUG;host 'http://www.btydkj.com/cp.php?cl=cp&nowmenuid=11059665' does not appear to be vulnerable to XSS attacks with payload 'cl=cp&nowmenuid=11059665\u003c'...
2017-11-30 09:37:26,588;zeus-log;INFO;trying payload 'cl=cp&nowmenuid=11059665\u003C'...
2017-11-30 09:37:26,588;zeus-log;DEBUG;host 'http://www.btydkj.com/cp.php?cl=cp&nowmenuid=11059665' does not appear to be vulnerable to XSS attacks with payload 'cl=cp&nowmenuid=11059665\u003C'...
2017-11-30 09:37:27,013;zeus-log;INFO;trying payload 'cl=cp&nowmenuid=11059665&lt;'...
2017-11-30 09:37:27,013;zeus-log;DEBUG;payload 'cl=cp&nowmenuid=11059665&lt;' appears to be usable...
2017-11-30 09:37:27,438;zeus-log;INFO;trying payload 'cl=cp&nowmenuid=11059665%3C'...
2017-11-30 09:37:27,438;zeus-log;DEBUG;payload 'cl=cp&nowmenuid=11059665%3C' appears to be usable...
2017-11-30 09:37:27,602;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code '('Connection aborted.', error(104, 'Connection reset by peer'))'...
Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1002, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 171, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 117, in scan_xss
    xss_request = requests.get(url, proxies=config_proxy, headers=config_headers)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

2017-11-30 09:37:27,858;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-30 09:37:27,859;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-30 09:37:27,859;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-30 09:37:27,860;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/5de72f5d33e9199f0366c5d1d3e6fa9824d9c2ab
