### ISSUE TITLE
Unhandled exception (vlRqAeZ)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#193]
Zeus version:
`1.3.9.daa83f`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 353, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1002, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 171, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 117, in scan_xss
    xss_request = requests.get(url, proxies=config_proxy, headers=config_headers)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:cp.php?cl=cp nowmenuid= --batch --verbose -x --random-agent --x-forward`

Log file info:
```2017-11-30 09:44:07,139;zeus-log;DEBUG;loading script 'anquanbao'...
2017-11-30 09:44:07,140;zeus-log;DEBUG;loading script 'generic'...
2017-11-30 09:44:07,141;zeus-log;INFO;no WAF/IDS/IPS has been identified on target URL...
2017-11-30 09:44:07,141;zeus-log;DEBUG;loading XML data...
2017-11-30 09:44:07,346;zeus-log;INFO;attempting to get request headers for 'http://www.sunstar.cc/cp.php?cl=cp&nowmenuid=11802'...
2017-11-30 09:44:07,347;zeus-log;INFO;random IP address generated for header '134.203.202.106'...
2017-11-30 09:44:07,348;zeus-log;INFO;random IP address generated for header '93.232.103.140'...
2017-11-30 09:44:07,349;zeus-log;INFO;random IP address generated for header '241.154.233.71'...
2017-11-30 09:44:07,940;zeus-log;INFO;found a request cookie, saving to file...
2017-11-30 09:44:07,941;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/www.sunstar.cc-cookie.log'...
2017-11-30 09:44:07,942;zeus-log;DEBUG;fetched {'X-Powered-By': 'PHP/5.4.45', 'Transfer-Encoding': 'chunked', 'Set-Cookie': 'PHPSESSID=2018c136tc30jkgh6gecohi4d3; path=/, language=en; expires=Fri, 01-Dec-2017 15:45:07 GMT; path=/', 'Expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'Vary': 'Accept-Encoding', 'Server': 'nginx/1.13.3', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Date': 'Thu, 30 Nov 2017 15:44:07 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Encoding': 'gzip'}...
2017-11-30 09:44:07,942;zeus-log;INFO;writing found headers to log file...
2017-11-30 09:44:07,943;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.sunstar.cc-headers.json'...
2017-11-30 09:44:08,013;zeus-log;INFO;loading payloads...
2017-11-30 09:44:08,028;zeus-log;DEBUG;a total of 296 payloads loaded...
2017-11-30 09:44:08,028;zeus-log;INFO;payloads will be written to a temporary file and read from there...
2017-11-30 09:44:08,029;zeus-log;INFO;loaded URL's have been saved to '/tmp/tmpNHnQzW'...
2017-11-30 09:44:08,030;zeus-log;INFO;testing for XSS vulnerabilities on host 'http://www.sunstar.cc/cp.php?cl=cp&nowmenuid=11802'...
2017-11-30 09:44:08,311;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code '('Connection aborted.', error(104, 'Connection reset by peer'))'...
Traceback (most recent call last):
  File "zeus.py", line 353, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1002, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 171, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 117, in scan_xss
    xss_request = requests.get(url, proxies=config_proxy, headers=config_headers)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

2017-11-30 09:44:08,811;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-30 09:44:08,811;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-30 09:44:08,827;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-30 09:44:08,828;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
duplicate #191
