### ISSUE TITLE
Unhandled exception (AdChNFH)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#194]
Zeus version:
`1.3.9.daa83f`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 353, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1002, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 171, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 117, in scan_xss
    xss_request = requests.get(url, proxies=config_proxy, headers=config_headers)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:cp.php?cl=cp nowmenuid= --batch --verbose -x --random-agent --x-forward`

Log file info:
```2017-11-30 10:14:24,040;zeus-log;DEBUG;loading script 'squid'...
2017-11-30 10:14:24,044;zeus-log;DEBUG;loading script 'wallarm'...
2017-11-30 10:14:24,045;zeus-log;DEBUG;loading script 'yunsuo'...
2017-11-30 10:14:24,060;zeus-log;DEBUG;loading script 'bigip'...
2017-11-30 10:14:24,084;zeus-log;DEBUG;loading script 'anquanbao'...
2017-11-30 10:14:24,085;zeus-log;DEBUG;loading script 'generic'...
2017-11-30 10:14:24,087;zeus-log;INFO;no WAF/IDS/IPS has been identified on target URL...
2017-11-30 10:14:24,087;zeus-log;DEBUG;loading XML data...
2017-11-30 10:14:24,223;zeus-log;INFO;attempting to get request headers for 'http://www.sunstar.cc/cp.php?cl=cp&nowmenuid=11802'...
2017-11-30 10:14:24,224;zeus-log;INFO;random IP address generated for header '192.80.130.225'...
2017-11-30 10:14:24,224;zeus-log;INFO;random IP address generated for header '60.228.66.69'...
2017-11-30 10:14:24,224;zeus-log;INFO;random IP address generated for header '138.76.162.19'...
2017-11-30 10:14:24,500;zeus-log;INFO;found a request cookie, saving to file...
2017-11-30 10:14:24,501;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/www.sunstar.cc-cookie.log'...
2017-11-30 10:14:24,676;zeus-log;DEBUG;fetched {'X-Powered-By': 'PHP/5.4.45', 'Transfer-Encoding': 'chunked', 'Set-Cookie': 'PHPSESSID=tvjq4urcksdpmugnbq0vrtg6l5; path=/, language=en; expires=Fri, 01-Dec-2017 16:15:24 GMT; path=/', 'Expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'Vary': 'Accept-Encoding', 'Server': 'nginx/1.13.3', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Date': 'Thu, 30 Nov 2017 16:14:24 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Encoding': 'gzip'}...
2017-11-30 10:14:24,676;zeus-log;INFO;writing found headers to log file...
2017-11-30 10:14:24,677;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.sunstar.cc-headers.json'...
2017-11-30 10:14:24,693;zeus-log;INFO;loading payloads...
2017-11-30 10:14:24,710;zeus-log;DEBUG;a total of 296 payloads loaded...
2017-11-30 10:14:24,710;zeus-log;INFO;payloads will be written to a temporary file and read from there...
2017-11-30 10:14:24,711;zeus-log;INFO;loaded URL's have been saved to '/tmp/tmplBdUTz'...
2017-11-30 10:14:24,712;zeus-log;INFO;testing for XSS vulnerabilities on host 'http://www.sunstar.cc/cp.php?cl=cp&nowmenuid=11802'...
2017-11-30 10:14:24,838;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code '('Connection aborted.', error(104, 'Connection reset by peer'))'...
Traceback (most recent call last):
  File "zeus.py", line 353, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1002, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 171, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 117, in scan_xss
    xss_request = requests.get(url, proxies=config_proxy, headers=config_headers)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

2017-11-30 10:14:25,276;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-30 10:14:25,277;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-30 10:14:25,298;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-30 10:14:25,299;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
duplpicate #191
