### ISSUE TITLE
Unhandled exception (WRMTxMD)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#196]
Zeus version:
`1.3.9.daa83f`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 353, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1002, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 171, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 117, in scan_xss
    xss_request = requests.get(url, proxies=config_proxy, headers=config_headers)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:cp.php?cl=cp nowmenuid= --batch -x`

Log file info:
```2017-11-30 10:43:46,520;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-11-30 10:43:46,521;zeus-log;INFO;no proxy configuration detected...
2017-11-30 10:43:47,102;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner/1.3.9.daa83f (Language=Python/2.7.13; Platform=Linux)'...
2017-11-30 10:43:47,166;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/url-log/url-log-1.log'...
2017-11-30 10:43:47,166;zeus-log;INFO;found a total of 20 URLs with given query 'inurl:cp.php?cl=cp nowmenuid='...
2017-11-30 10:43:47,167;zeus-log;INFO;currently running on 'http://www.sunstar.cc/cp.php?cl=cp&nowmenuid=11802' (target #1)...
2017-11-30 10:43:47,167;zeus-log;INFO;checking for HTTP headers...
2017-11-30 10:43:47,167;zeus-log;INFO;checking if target URL is protected by some kind of WAF/IPS/IDS...
2017-11-30 10:43:48,304;zeus-log;INFO;no WAF/IDS/IPS has been identified on target URL...
2017-11-30 10:43:48,392;zeus-log;INFO;attempting to get request headers for 'http://www.sunstar.cc/cp.php?cl=cp&nowmenuid=11802'...
2017-11-30 10:43:48,683;zeus-log;INFO;found a request cookie, saving to file...
2017-11-30 10:43:48,686;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/www.sunstar.cc-cookie.log'...
2017-11-30 10:43:48,699;zeus-log;INFO;writing found headers to log file...
2017-11-30 10:43:48,700;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.sunstar.cc-headers.json'...
2017-11-30 10:43:48,840;zeus-log;INFO;loading payloads...
2017-11-30 10:43:48,855;zeus-log;INFO;payloads will be written to a temporary file and read from there...
2017-11-30 10:43:48,860;zeus-log;INFO;loaded URL's have been saved to '/tmp/tmpZ6UpHs'...
2017-11-30 10:43:48,860;zeus-log;INFO;testing for XSS vulnerabilities on host 'http://www.sunstar.cc/cp.php?cl=cp&nowmenuid=11802'...
2017-11-30 10:43:50,389;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code '('Connection aborted.', error(104, 'Connection reset by peer'))'...
Traceback (most recent call last):
  File "zeus.py", line 353, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1002, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 171, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 117, in scan_xss
    xss_request = requests.get(url, proxies=config_proxy, headers=config_headers)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

2017-11-30 10:43:50,924;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-11-30 10:43:50,925;zeus-log;INFO;[32mgetting authorization...[0m
2017-11-30 10:43:50,964;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-11-30 10:43:50,964;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
duplicate #191
