### ISSUE TITLE
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8775): Max retries exceeded with url: /task/new?Content-Type=application%2Fjson (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffaa1c7d490>: Failed to establish a new connection: [Errno 111] Connection refused',))

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#20]
Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/sqlmap_scan/__init__.py", line 133, in sqlmap_scan_main
    sqlmap_scan.init_new_scan()
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/sqlmap_scan/__init__.py", line 41, in init_new_scan
    return requests.get(new_scan_url, params=self.headers)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8775): Max retries exceeded with url: /task/new?Content-Type=application%2Fjson (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffaa1c7d490>: Failed to establish a new connection: [Errno 111] Connection refused',))
````

Running details:
`Linux-4.10.0-33-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d incontent:admin -s --verbose`

**Comment by Ekultek** [comment]
oops
