### ISSUE TITLE
Unhandled exception (nDxWMJi)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#202]
Zeus version:
`1.3.10.5de72f`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1023, in run_attacks
    pgp_main(url, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/var/search/pgp_search.py", line 185, in pgp_main
    return get_pgp_keys(urls, query, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/var/search/pgp_search.py", line 132, in get_pgp_keys
    timeout=10
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pgp.mit.edu', port=443): Read timed out. (read timeout=10)
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d ext:conf   inurl:rsyncd.conf -cvs -man --verbose --batch -P --x-forward --random-agent --proxy socks5://127.0.0.1:9050 --tamper=enclosebrackets -M -L 10 --thread -T 7`

Log file info:
```2017-12-01 03:48:11,602;zeus-log;INFO;gathering PGP key(s) and writing to a file...
2017-12-01 03:48:11,602;zeus-log;INFO;checking a maximum of 75 PGP keys...
2017-12-01 03:48:11,602;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=get&search=0x5CF2B8EE0DB90F7D'...
2017-12-01 03:48:12,330;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=get&search=0x5380F40B62F719B7'...
2017-12-01 03:48:12,884;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=get&search=0xE008EA06A18C5750'...
2017-12-01 03:48:14,667;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=vindex&search=0xD793CA211F7F1AFB'...
2017-12-01 03:48:15,348;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=get&search=0x618271BEBE64CC5F'...
2017-12-01 03:48:22,984;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=get&search=0xDB9B21A1A806A555'...
2017-12-01 03:48:24,533;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=get&search=0x4570F0078AE809FE'...
2017-12-01 03:48:26,075;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=vindex&search=0x33EDBC19D120CE8C'...
2017-12-01 03:48:26,616;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=vindex&search=0x15001D837961A569'...
2017-12-01 03:48:27,182;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=vindex&search=0x3C1D8BBDFB31030E'...
2017-12-01 03:48:27,718;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=vindex&search=0x7D8181E8DFE07B95'...
2017-12-01 03:48:28,635;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=get&search=0xF53EC306179A2C5D'...
2017-12-01 03:48:29,544;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=get&search=0x6F613A9720500207'...
2017-12-01 03:48:30,086;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=vindex&search=0xBBC6183385271086'...
2017-12-01 03:48:30,762;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=get&search=0x2E59E072A9F831F6'...
2017-12-01 03:48:31,440;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=vindex&search=0x611033FDAAAF9A6F'...
2017-12-01 03:48:32,050;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=vindex&search=0x456EFCD12936C225'...
2017-12-01 03:48:32,615;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=vindex&search=0x25C949FC87B69BBE'...
2017-12-01 03:48:33,388;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=vindex&search=0x9B45C4632663C345'...
2017-12-01 03:48:34,034;zeus-log;DEBUG;checking 'https://pgp.mit.edu/pks/lookup?op=vindex&search=0xB90DD7C9ED61953D'...
2017-12-01 03:48:46,518;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code 'HTTPSConnectionPool(host='pgp.mit.edu', port=443): Read timed out. (read timeout=10)'...
Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1023, in run_attacks
    pgp_main(url, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/var/search/pgp_search.py", line 185, in pgp_main
    return get_pgp_keys(urls, query, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/var/search/pgp_search.py", line 132, in get_pgp_keys
    timeout=10
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pgp.mit.edu', port=443): Read timed out. (read timeout=10)

2017-12-01 06:56:56,324;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-01 06:56:58,370;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-01 06:57:00,106;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-01 06:57:00,455;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
patches via https://github.com/Ekultek/Zeus-Scanner/commit/083e54128471e06003e90388d11401ce9ddfefca
