### ISSUE TITLE
Unhandled exception (ftuMtoX)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#203]
Zeus version:
`1.3.10.5de72f`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 992, in run_attacks
    opts=create_arguments(nmap=True, nmap_args=nmap_arguments)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/nmap_scan/__init__.py", line 110, in perform_port_scan
    found_ip_address = socket.gethostbyname(url)
gaierror: [Errno -3] Temporary failure in name resolution
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d ext:dat bpk.dat --verbose --batch -p --x-forward --random-agent --proxy socks5://127.0.0.1:9050 --tamper=enclosebrackets -M -L 10 --thread -T 7`

Log file info:
```2017-12-01 07:43:14,557;zeus-log;INFO;random IP address generated for header '101.173.49.231'...
2017-12-01 07:43:14,557;zeus-log;INFO;random IP address generated for header '3.17.98.179'...
2017-12-01 07:43:14,557;zeus-log;INFO;random IP address generated for header '93.163.199.156'...
2017-12-01 07:43:15,920;zeus-log;INFO;found a request cookie, saving to file...
2017-12-01 07:43:15,922;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/www.boutin-services.com-cookie.log'...
2017-12-01 07:43:15,922;zeus-log;DEBUG;fetched {'Content-Length': '0', 'X-Powered-By': 'PHP/5.5.38', 'Set-Cookie': '60gpBAK=R1224225179; path=/; expires=Fri, 01-Dec-2017 14:54:45 GMT, 60gp=R2337197939; path=/; expires=Fri, 01-Dec-2017 14:54:45 GMT', 'Server': 'Apache', 'X-IPLB-Instance': '5182', 'Date': 'Fri, 01 Dec 2017 13:43:15 GMT', 'Content-Type': 'text/html'}...
2017-12-01 07:43:15,922;zeus-log;INFO;writing found headers to log file...
2017-12-01 07:43:15,924;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.boutin-services.com-headers.json'...
2017-12-01 07:43:15,925;zeus-log;INFO;creating arguments for nmap...
2017-12-01 07:43:15,925;zeus-log;WARNING;if the port scan is not completed in 02:00(m) it will timeout...
2017-12-01 07:43:15,925;zeus-log;INFO;attempting to find IP address for hostname 'www.boutin-services.com'...
2017-12-01 07:43:15,926;zeus-log;INFO;found IP address for given URL -> '213.186.33.19'...
2017-12-01 07:43:15,926;zeus-log;DEBUG;checking for nmap on your system...
2017-12-01 07:43:15,927;zeus-log;DEBUG;nmap has been found under '/usr/local/bin/nmap'...
2017-12-01 07:43:15,927;zeus-log;INFO;starting port scan on IP address '213.186.33.19'...
2017-12-01 07:45:15,925;zeus-log;ERROR;port scan is taking to long and has hit the timeout, you can increase this time by passing the --time-sec flag (IE --time-sec 300)...
2017-12-01 07:45:15,926;zeus-log;INFO;currently running on 'http://inverse.la/vulsls/nmlsnmnmgo.dat' (target #7)...
2017-12-01 07:45:15,926;zeus-log;INFO;checking for HTTP headers...
2017-12-01 07:45:15,926;zeus-log;INFO;checking if target URL is protected by some kind of WAF/IPS/IDS...
2017-12-01 07:45:15,926;zeus-log;INFO;random IP address generated for header '189.228.182.3'...
2017-12-01 07:45:15,926;zeus-log;INFO;random IP address generated for header '33.184.92.149'...
2017-12-01 07:45:15,927;zeus-log;INFO;random IP address generated for header '68.79.177.137'...
2017-12-01 07:45:15,927;zeus-log;DEBUG;attempting connection to 'http://inverse.la/vulsls/nmlsnmnmgo.dat AND 1=1 UNION ALL SELECT 1,NULL,'<script>alert("XSS")</script>',table_name FROM information_schema.tables WHERE 2>1--/**/; EXEC xp_cmdshell('cat ../../../etc/passwd')#'...
2017-12-01 07:45:35,936;zeus-log;WARNING;detection request failed, assuming no protection and continuing...
2017-12-01 07:45:35,936;zeus-log;INFO;no WAF/IDS/IPS has been identified on target URL...
2017-12-01 07:45:35,937;zeus-log;DEBUG;loading XML data...
2017-12-01 07:45:35,938;zeus-log;INFO;attempting to get request headers for 'http://inverse.la/vulsls/nmlsnmnmgo.dat'...
2017-12-01 07:45:35,938;zeus-log;INFO;random IP address generated for header '95.239.113.245'...
2017-12-01 07:45:35,939;zeus-log;INFO;random IP address generated for header '6.170.140.157'...
2017-12-01 07:45:35,939;zeus-log;INFO;random IP address generated for header '201.67.133.232'...
2017-12-01 07:45:55,955;zeus-log;ERROR;unable to retrieve headers for site 'http://inverse.la/vulsls/nmlsnmnmgo.dat'...
2017-12-01 07:45:55,956;zeus-log;INFO;creating arguments for nmap...
2017-12-01 07:45:55,956;zeus-log;WARNING;if the port scan is not completed in 02:00(m) it will timeout...
2017-12-01 07:45:55,956;zeus-log;INFO;attempting to find IP address for hostname 'inverse.la'...
2017-12-01 07:46:01,802;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code '[Errno -3] Temporary failure in name resolution'...
Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 992, in run_attacks
    opts=create_arguments(nmap=True, nmap_args=nmap_arguments)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/nmap_scan/__init__.py", line 110, in perform_port_scan
    found_ip_address = socket.gethostbyname(url)
gaierror: [Errno -3] Temporary failure in name resolution

2017-12-01 07:46:02,177;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-01 07:46:02,177;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-01 07:46:02,370;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-01 07:46:02,370;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/083e54128471e06003e90388d11401ce9ddfefca
