### ISSUE TITLE
Unhandled exception (TPDhSNR)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#207]
Zeus version:
`1.3.11.083e54`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 998, in run_attacks
    verbose=verbose, do_threading=do_threading, batch=batch
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 261, in main
    check_for_admin_page(url, extensions, show_possibles=show, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 140, in check_for_admin_page
    if int(data[2]) == error_code:
ValueError: invalid literal for int() with base 10: '404:'
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle: "index of/root" --verbose --batch -a --x-forward --random-agent --proxy socks5://127.0.0.1:9050 --tamper=enclosebrackets -M -L 10`

Log file info:
```2017-12-01 12:24:55,978;zeus-log;DEBUG;loading script 'yunsuo'...
2017-12-01 12:24:55,979;zeus-log;DEBUG;loading script 'bigip'...
2017-12-01 12:24:55,980;zeus-log;DEBUG;loading script 'anquanbao'...
2017-12-01 12:24:55,981;zeus-log;DEBUG;loading script 'generic'...
2017-12-01 12:24:55,982;zeus-log;WARNING;the target URL WAF/IDS/IPS has been identified as 'Varnish FireWall (OWASP)'...
2017-12-01 12:24:55,982;zeus-log;DEBUG;loading XML data...
2017-12-01 12:24:56,011;zeus-log;INFO;attempting to get request headers for 'https://link.springer.com/content/pdf/10.1007/s00784-013-0965-8.pdf'...
2017-12-01 12:24:56,012;zeus-log;INFO;random IP address generated for header '162.26.246.49'...
2017-12-01 12:24:56,012;zeus-log;INFO;random IP address generated for header '159.118.150.76'...
2017-12-01 12:24:56,012;zeus-log;INFO;random IP address generated for header '174.116.74.118'...
2017-12-01 12:24:56,624;zeus-log;INFO;found a request cookie, saving to file...
2017-12-01 12:24:56,626;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/link.springer.com-cookie.log'...
2017-12-01 12:24:56,627;zeus-log;DEBUG;fetched {'X-Timer': 'S1512152696.323224,VS0,VE269', 'Via': '1.1 varnish', 'X-Cache': 'MISS', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Set-Cookie': 'sim-inst-token=1::1512182696220:2da6e0d9;Path=/;Domain=.springer.com;HttpOnly', 'Accept-Ranges': 'bytes', 'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'Vary': 'Accept-Encoding', 'X-Vcap-Request-Id': '5c1e8bbc-4937-4fff-47e9-0b0888fa00b6, ff189471-0b88-44a5-4965-949f9e7341c4', 'Server': 'openresty', 'Connection': 'keep-alive', 'X-Served-By': 'bunsen.live.cf.private.springer.com, cache-dfw18629-DFW', 'X-Cache-Hits': '0', 'Cache-Control': 'private, max-age=0, must-revalidate', 'Date': 'Fri, 01 Dec 2017 18:24:56 GMT', 'Content-Type': 'text/html;charset=utf-8', 'Age': '0'}...
2017-12-01 12:24:56,627;zeus-log;INFO;writing found headers to log file...
2017-12-01 12:24:56,628;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/link.springer.com-headers.json'...
2017-12-01 12:24:56,685;zeus-log;INFO;parsing robots.txt...
2017-12-01 12:24:56,741;zeus-log;INFO;robots.txt page will be saved into a file...
2017-12-01 12:24:56,742;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/robots/link.springer.com-robots_text.log'...
2017-12-01 12:24:56,742;zeus-log;INFO;checking for a sitemap...
2017-12-01 12:24:57,185;zeus-log;ERROR;unable to connect to 'http://link.springer.com/sitemap.xml', assuming does not exist and continuing...
2017-12-01 12:24:57,186;zeus-log;INFO;loading extensions...
2017-12-01 12:24:57,203;zeus-log;DEBUG;loaded a total of 643 extensions...
2017-12-01 12:24:57,203;zeus-log;INFO;attempting to bruteforce admin panel...
2017-12-01 12:24:57,204;zeus-log;DEBUG;trying 'http://link.springer.com:23'...
2017-12-01 12:25:02,209;zeus-log;WARNING;connection timed out assuming won't connect and skipping...
2017-12-01 12:25:02,209;zeus-log;DEBUG;trying 'http://link.springer.com:82'...
2017-12-01 12:25:07,216;zeus-log;WARNING;connection timed out assuming won't connect and skipping...
2017-12-01 12:25:07,216;zeus-log;DEBUG;trying 'http://link.springer.com:2082'...
2017-12-01 12:25:12,224;zeus-log;WARNING;connection timed out assuming won't connect and skipping...
2017-12-01 12:25:12,224;zeus-log;DEBUG;trying 'http://link.springer.com:2083'...
2017-12-01 12:25:17,233;zeus-log;WARNING;connection timed out assuming won't connect and skipping...
2017-12-01 12:25:17,234;zeus-log;DEBUG;trying 'http://link.springer.com/administratie/'...
2017-12-01 12:25:17,822;zeus-log;ERROR;[7;31;31mran into exception 'invalid literal for int() with base 10: '404:'' exception has been saved to log file...
Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 998, in run_attacks
    verbose=verbose, do_threading=do_threading, batch=batch
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 261, in main
    check_for_admin_page(url, extensions, show_possibles=show, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 140, in check_for_admin_page
    if int(data[2]) == error_code:
ValueError: invalid literal for int() with base 10: '404:'

2017-12-01 12:25:18,027;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-01 12:25:18,028;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-01 12:25:18,044;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-01 12:25:18,045;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
patched via patched via https://github.com/Ekultek/Zeus-Scanner/commit/ade2d5f82c1b77fb9daa80a2a8500078a4539178
