### ISSUE TITLE
Unhandled exception (XaUgNPH)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#210]
Zeus version:
`1.3.11.083e54`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 998, in run_attacks
    verbose=verbose, do_threading=do_threading, batch=batch
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 263, in main
    if not lib.core.common.pause():
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 262, in pause
    message, paused=True
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 241, in prompt
    time.strftime("%H:%M:%S"), "PROMPT", question, opts
EOFError
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allinurl: admin mdb --verbose --batch -a --x-forward --random-agent --proxy socks5://127.0.0.1:9050 --tamper=enclosebrackets -M -L 10`

Log file info:
```2017-12-01 12:32:37,208;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,208;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,208;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,208;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,208;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,209;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,209;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,209;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,209;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,209;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,209;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,209;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,210;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,210;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,210;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,210;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,210;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,210;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,211;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,211;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,211;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,211;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,211;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,211;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,211;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,212;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,212;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,212;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,212;zeus-log;ERROR;failed to connect got error code 404: (reason: unexpected error code)...
2017-12-01 12:32:37,212;zeus-log;DEBUG;trying 'http://www.ebrd.com/admin_login.asp'...
2017-12-01 12:32:40,223;zeus-log;ERROR;[7;31;31mran into exception '' exception has been saved to log file...
Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 998, in run_attacks
    verbose=verbose, do_threading=do_threading, batch=batch
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 263, in main
    if not lib.core.common.pause():
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 262, in pause
    message, paused=True
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 241, in prompt
    time.strftime("%H:%M:%S"), "PROMPT", question, opts
EOFError

2017-12-01 12:32:40,484;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-01 12:32:40,485;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-01 12:32:40,485;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-01 12:32:40,487;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
This happens when the issue finder is being run and CNTRL-C is pressed, so it's invalid
