### ISSUE TITLE
Unhandled exception (eZcQMsr)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#211]
Zeus version:
`1.3.11.083e54`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 995, in run_attacks
    opts=create_arguments(nmap=True, nmap_args=nmap_arguments)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/nmap_scan/__init__.py", line 112, in perform_port_scan
    found_ip_address = socket.gethostbyname_ex(url)
gaierror: [Errno -3] Temporary failure in name resolution
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:\"Test page for Apache Installation\" --verbose --batch -p --x-forward --random-agent --proxy socks5://127.0.0.1:9050 --tamper=enclosebrackets -M -L 10`

Log file info:
```2017-12-01 15:03:05,716;zeus-log;INFO;random IP address generated for header '133.214.190.239'...
2017-12-01 15:03:05,716;zeus-log;INFO;random IP address generated for header '2.35.114.148'...
2017-12-01 15:03:05,716;zeus-log;INFO;random IP address generated for header '95.109.5.215'...
2017-12-01 15:03:06,086;zeus-log;DEBUG;fetched {'Transfer-Encoding': 'chunked', 'Keep-Alive': 'timeout=15, max=100', 'Server': 'Apache/1.3.6 (Unix) PHP/4.0.6', 'Connection': 'Keep-Alive', 'Date': 'Fri, 01 Dec 2017 20:55:46 GMT', 'Content-Type': 'text/html'}...
2017-12-01 15:03:06,086;zeus-log;INFO;writing found headers to log file...
2017-12-01 15:03:06,089;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.ax6.nl(1).json'...
2017-12-01 15:03:06,089;zeus-log;INFO;creating arguments for nmap...
2017-12-01 15:03:06,090;zeus-log;WARNING;if the port scan is not completed in 02:00(m) it will timeout...
2017-12-01 15:03:06,090;zeus-log;INFO;attempting to find IP address for hostname 'www.ax6.nl'...
2017-12-01 15:03:06,091;zeus-log;INFO;found IP address for given URL -> '82.95.116.181'...
2017-12-01 15:03:06,091;zeus-log;DEBUG;checking for nmap on your system...
2017-12-01 15:03:06,091;zeus-log;DEBUG;nmap has been found under '/usr/local/bin/nmap'...
2017-12-01 15:03:06,092;zeus-log;INFO;starting port scan on IP address '82.95.116.181'...
2017-12-01 15:03:22,696;zeus-log;INFO;finding data for IP '82.95.116.181'...
2017-12-01 15:03:22,697;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/nmap-scan-log/nmap(8).json'...
2017-12-01 15:03:22,698;zeus-log;INFO;port scan completed, all data saved to JSON file under 'None'...
2017-12-01 15:03:22,698;zeus-log;INFO;currently running on 'http://kaukonen.net/' (target #5)...
2017-12-01 15:03:22,698;zeus-log;INFO;checking for HTTP headers...
2017-12-01 15:03:22,698;zeus-log;INFO;checking if target URL is protected by some kind of WAF/IPS/IDS...
2017-12-01 15:03:22,699;zeus-log;INFO;random IP address generated for header '171.244.72.166'...
2017-12-01 15:03:22,699;zeus-log;INFO;random IP address generated for header '81.255.148.56'...
2017-12-01 15:03:22,699;zeus-log;INFO;random IP address generated for header '105.161.18.80'...
2017-12-01 15:03:22,699;zeus-log;DEBUG;attempting connection to 'http://kaukonen.net/ AND 1=1 UNION ALL SELECT 1,NULL,'<script>alert("XSS")</script>',table_name FROM information_schema.tables WHERE 2>1--/**/; EXEC xp_cmdshell('cat ../../../etc/passwd')#'...
2017-12-01 15:03:42,720;zeus-log;WARNING;detection request failed, assuming no protection and continuing...
2017-12-01 15:03:42,721;zeus-log;INFO;no WAF/IDS/IPS has been identified on target URL...
2017-12-01 15:03:42,721;zeus-log;DEBUG;loading XML data...
2017-12-01 15:03:42,722;zeus-log;INFO;attempting to get request headers for 'http://kaukonen.net/'...
2017-12-01 15:03:42,723;zeus-log;INFO;random IP address generated for header '237.180.127.112'...
2017-12-01 15:03:42,723;zeus-log;INFO;random IP address generated for header '94.236.113.225'...
2017-12-01 15:03:42,723;zeus-log;INFO;random IP address generated for header '43.212.126.221'...
2017-12-01 15:04:02,745;zeus-log;ERROR;unable to retrieve headers for site 'http://kaukonen.net/'...
2017-12-01 15:04:02,745;zeus-log;INFO;creating arguments for nmap...
2017-12-01 15:04:02,746;zeus-log;WARNING;if the port scan is not completed in 02:00(m) it will timeout...
2017-12-01 15:04:02,746;zeus-log;INFO;attempting to find IP address for hostname 'kaukonen.net'...
2017-12-01 15:04:38,909;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code '[Errno -3] Temporary failure in name resolution'...
Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 995, in run_attacks
    opts=create_arguments(nmap=True, nmap_args=nmap_arguments)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/nmap_scan/__init__.py", line 112, in perform_port_scan
    found_ip_address = socket.gethostbyname_ex(url)
gaierror: [Errno -3] Temporary failure in name resolution

2017-12-01 15:04:39,209;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-01 15:04:39,210;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-01 15:04:39,224;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-01 15:04:39,225;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
patched via patched via https://github.com/Ekultek/Zeus-Scanner/commit/ade2d5f82c1b77fb9daa80a2a8500078a4539178
