### ISSUE TITLE
Unhandled exception (XjZXrZy)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#219]
Zeus version:
`1.3.15-pre`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1001, in run_attacks
    verbose=verbose, do_threading=do_threading, batch=batch
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 215, in main
    results = check_for_externals(url, robots=True, batch=batch)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 59, in check_for_externals
    for line in data.split("\n"):
AttributeError: 'int' object has no attribute 'split'
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle: "index of/admin" --verbose --batch -a --x-forward --random-agent --proxy socks5://127.0.0.1:9050 --tamper=enclosebrackets -M -L 10`

Log file info:
```2017-12-02 11:15:52,701;zeus-log;DEBUG;checking if the application has been run before...
2017-12-02 11:15:52,702;zeus-log;DEBUG;verifying operating system...
2017-12-02 11:15:52,725;zeus-log;DEBUG;already ran, skipping...
2017-12-02 11:15:52,726;zeus-log;DEBUG;running with options '{'proxyConfig': 'socks5://127.0.0.1:9050', 'searchMultiplePages': True, 'adminPanelFinder': True, 'forwardedForRandomIP': True, 'useRandomAgent': True, 'runInBatch': True, 'tamperXssPayloads': 'enclosebrackets', 'runInVerbose': True, 'amountToSearch': 10, 'dorkToUse': 'allintitle: "index of/admin"'}'...
2017-12-02 11:15:52,726;zeus-log;INFO;log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-3.log'...
2017-12-02 11:15:52,726;zeus-log;DEBUG;grabbing random user-agent from '/home/baal/bin/python/zeus-scanner/etc/text_files/agents.txt'...
2017-12-02 11:15:52,752;zeus-log;INFO;random agent being used 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.0.6) Gecko/20060803 Firefox/1.5.0.6 (Swiftfox)'...
2017-12-02 11:15:52,753;zeus-log;DEBUG;using default search engine (Google)...
2017-12-02 11:15:52,753;zeus-log;INFO;using default search engine...
2017-12-02 11:15:52,753;zeus-log;INFO;searching Google using dork 'allintitle: "index of/admin"' for a total of 10 links...
2017-12-02 11:15:52,753;zeus-log;WARNING;searching multiple pages will not be done on Google...
2017-12-02 11:15:52,753;zeus-log;INFO;random IP address generated for header '200.63.119.98'...
2017-12-02 11:15:52,754;zeus-log;INFO;random IP address generated for header '124.214.111.106'...
2017-12-02 11:15:52,754;zeus-log;INFO;random IP address generated for header '183.67.59.178'...
2017-12-02 11:15:52,754;zeus-log;DEBUG;searching page number 1...
2017-12-02 11:15:53,334;zeus-log;INFO;a total of 15 URL(s) found out of the requested 10...
2017-12-02 11:15:53,335;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/url-log/url-log-1.log'...
2017-12-02 11:15:53,335;zeus-log;INFO;currently running on 'http://www.denvercitymotorparts.com/admin/' (target #1)...
2017-12-02 11:15:53,335;zeus-log;INFO;checking for HTTP headers...
2017-12-02 11:15:53,335;zeus-log;INFO;checking if target URL is protected by some kind of WAF/IPS/IDS...
2017-12-02 11:15:53,335;zeus-log;DEBUG;attempting connection to 'http://www.denvercitymotorparts.com/admin/ AND 1=1 UNION ALL SELECT 1,NULL,'<script>alert("XSS")</script>',table_name FROM information_schema.tables WHERE 2>1--/**/; EXEC xp_cmdshell('cat ../../../etc/passwd')#'...
2017-12-02 11:15:53,336;zeus-log;INFO;random IP address generated for header '71.127.63.128'...
2017-12-02 11:15:53,336;zeus-log;INFO;random IP address generated for header '116.89.214.61'...
2017-12-02 11:15:53,336;zeus-log;INFO;random IP address generated for header '253.223.125.124'...
2017-12-02 11:15:57,241;zeus-log;WARNING;detection request failed, assuming no protection and continuing...
2017-12-02 11:15:57,241;zeus-log;INFO;no WAF/IDS/IPS has been identified on target URL...
2017-12-02 11:15:57,241;zeus-log;DEBUG;loading XML data...
2017-12-02 11:15:57,297;zeus-log;INFO;attempting to get request headers for 'http://www.denvercitymotorparts.com/admin/'...
2017-12-02 11:15:58,251;zeus-log;ERROR;unable to retrieve headers for site 'http://www.denvercitymotorparts.com/admin/'...
2017-12-02 11:15:58,353;zeus-log;INFO;parsing robots.txt...
2017-12-02 11:15:58,479;zeus-log;ERROR;[7;31;31mran into exception ''int' object has no attribute 'split'' exception has been saved to log file...
Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1001, in run_attacks
    verbose=verbose, do_threading=do_threading, batch=batch
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 215, in main
    results = check_for_externals(url, robots=True, batch=batch)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 59, in check_for_externals
    for line in data.split("\n"):
AttributeError: 'int' object has no attribute 'split'

2017-12-02 11:15:58,765;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-02 11:15:58,765;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-02 11:15:58,787;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-02 11:15:58,788;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/151d44beff9d5403c4d1769bf8f7dfd353df018a
