### ISSUE TITLE
Unhandled exception (sNPOuIk)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#221]
Zeus version:
`1.3.16.667610`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1023, in run_attacks
    github_gist_search_main(query, agent=agent, proxy=proxy, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 138, in github_gist_search_main
    gathered_links = get_raw_data(page_set, proxy=proxy, agent=agent, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 48, in get_raw_data
    _, _, data, _ = lib.core.common.get_page(url.format(page), agent=agent, proxy=proxy)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 332, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False if skip_verf else True, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 405, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 302, in get_connection
    proxy = prepend_scheme_if_needed(proxy, 'http')
  File "/home/baal/.local/lib/python2.7/site-packages/requests/utils.py", line 822, in prepend_scheme_if_needed
    scheme, netloc, path, params, query, fragment = urlparse(url, new_scheme)
  File "/usr/lib/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python2.7/urlparse.py", line 176, in urlsplit
    cached = _parse_cache.get(key, None)
TypeError: unhashable type: 'dict'
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle: "index of/root" --verbose --batch -g --x-forward --random-agent --proxy socks5://127.0.0.1:9050 --tamper=enclosebrackets -M -L 10`

Log file info:
```2017-12-02 14:18:08,916;zeus-log;WARNING;the target URL WAF/IDS/IPS has been identified as 'Varnish FireWall (OWASP)'...
2017-12-02 14:18:08,916;zeus-log;DEBUG;loading XML data...
2017-12-02 14:18:08,952;zeus-log;INFO;attempting to get request headers for 'https://link.springer.com/content/pdf/10.1007/s00784-013-0965-8.pdf'...
2017-12-02 14:18:12,692;zeus-log;INFO;found a request cookie, saving to file...
2017-12-02 14:18:12,711;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/link.springer.com-cookie.log'...
2017-12-02 14:18:12,711;zeus-log;DEBUG;fetched {'X-Timer': 'S1512245891.224026,VS0,VE816', 'Via': '1.1 varnish', 'X-Cache': 'MISS', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Set-Cookie': 'sim-inst-token=1::1512275890702:633c9b6b;Path=/;Domain=.springer.com;HttpOnly', 'Accept-Ranges': 'bytes', 'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'Vary': 'Accept-Encoding', 'X-Vcap-Request-Id': '29430dda-98c8-4aab-6532-4470bab09468, d572f5b7-81b9-4176-6d09-1a164cf6ce09', 'Server': 'openresty', 'Connection': 'keep-alive', 'X-Served-By': 'bunsen.live.cf.private.springer.com, cache-dfw18635-DFW', 'X-Cache-Hits': '0', 'Cache-Control': 'private, max-age=0, must-revalidate', 'Date': 'Sat, 02 Dec 2017 20:18:12 GMT', 'Content-Type': 'text/html;charset=utf-8', 'Age': '0'}...
2017-12-02 14:18:12,712;zeus-log;INFO;writing found headers to log file...
2017-12-02 14:18:12,712;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/link.springer.com-headers.json'...
2017-12-02 14:18:12,737;zeus-log;DEBUG;checking if you have exceeded your search limit...
2017-12-02 14:18:13,106;zeus-log;WARNING;you have 59 unauthenticated requests remaining...
2017-12-02 14:18:13,107;zeus-log;INFO;searching Github Gists for 'link.springer.com'...
2017-12-02 14:18:13,107;zeus-log;INFO;searching a total of 5 pages of Gists...
2017-12-02 14:18:13,109;zeus-log;ERROR;[7;31;31mran into exception 'unhashable type: 'dict'' exception has been saved to log file...
Traceback (most recent call last):
  File "zeus.py", line 408, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1023, in run_attacks
    github_gist_search_main(query, agent=agent, proxy=proxy, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 138, in github_gist_search_main
    gathered_links = get_raw_data(page_set, proxy=proxy, agent=agent, verbose=verbose)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 48, in get_raw_data
    _, _, data, _ = lib.core.common.get_page(url.format(page), agent=agent, proxy=proxy)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 332, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False if skip_verf else True, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 405, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 302, in get_connection
    proxy = prepend_scheme_if_needed(proxy, 'http')
  File "/home/baal/.local/lib/python2.7/site-packages/requests/utils.py", line 822, in prepend_scheme_if_needed
    scheme, netloc, path, params, query, fragment = urlparse(url, new_scheme)
  File "/usr/lib/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python2.7/urlparse.py", line 176, in urlsplit
    cached = _parse_cache.get(key, None)
TypeError: unhashable type: 'dict'

2017-12-02 15:16:07,571;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-02 15:16:07,572;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-02 15:16:07,572;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-02 15:16:07,572;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/bedcde92708233dcfe2db8d8e7e1a104e710d35a
