### ISSUE TITLE
Unhandled exception (fBiKMro)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#226]
Zeus version:
`1.3.17.bedcde`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 353, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1009, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 189, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 113, in scan_xss
    _, status, html_data, _ = lib.core.common.get_page(url, agent=agent, proxy=proxy)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 332, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False if skip_verf else True, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/baal/.local/lib/python2.7/site-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/models.py", line 373, in prepare_url
    raise InvalidURL(*e.args)
InvalidURL: Failed to parse: core.trac.wordpress.javascript:alert("hellox worldss")
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:admin.php --verbose --batch -x --x-forward --random-agent --proxy socks5://127.0.0.1:9050 --tamper=enclosebrackets -W -E`

Log file info:
```2017-12-04 00:11:03,177;zeus-log;ERROR;payload 'x['0']['0']['3']C;' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,209;zeus-log;ERROR;payload 'x['0']['0']['0']['3']C;' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,235;zeus-log;ERROR;payload 'x['0']['0']['0']['0']['3']C;' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,259;zeus-log;ERROR;payload 'x['0']['0']['0']['0']['0']['3']C;' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,294;zeus-log;ERROR;payload 'X['3']C' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,316;zeus-log;ERROR;payload 'X['0']['3']C' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,347;zeus-log;ERROR;payload 'X['0']['0']['3']C' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,377;zeus-log;ERROR;payload 'X['0']['0']['0']['3']C' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,404;zeus-log;ERROR;payload 'X['0']['0']['0']['0']['3']C' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,431;zeus-log;ERROR;payload 'X['0']['0']['0']['0']['0']['3']C' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,478;zeus-log;ERROR;payload 'X['3']C;' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,533;zeus-log;ERROR;payload 'X['0']['3']C;' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,567;zeus-log;ERROR;payload 'X['0']['0']['3']C;' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,594;zeus-log;ERROR;payload 'X['0']['0']['0']['3']C;' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,618;zeus-log;ERROR;payload 'X['0']['0']['0']['0']['3']C;' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,654;zeus-log;ERROR;payload 'X['0']['0']['0']['0']['0']['3']C;' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,699;zeus-log;ERROR;payload '/script>' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,764;zeus-log;ERROR;payload '/script>' caused a connection error, assuming no good and continuing...
2017-12-04 00:11:03,766;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code 'Failed to parse: core.trac.wordpress.javascript:alert("hellox worldss")'...
Traceback (most recent call last):
  File "zeus.py", line 353, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1009, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 189, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 113, in scan_xss
    _, status, html_data, _ = lib.core.common.get_page(url, agent=agent, proxy=proxy)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 332, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False if skip_verf else True, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/baal/.local/lib/python2.7/site-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/models.py", line 373, in prepare_url
    raise InvalidURL(*e.args)
InvalidURL: Failed to parse: core.trac.wordpress.javascript:alert("hellox worldss")

2017-12-04 00:11:04,366;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-04 00:11:04,367;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-04 00:11:04,393;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-04 00:11:04,394;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/c382c010fc51450dc3dce166fa4ee5b0febb86c3
