### ISSUE TITLE
Unhandled exception (JFFaquY)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#229]
Zeus version:
`1.3.18.bd5587`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 353, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1001, in run_attacks
    verbose=verbose, do_threading=do_threading, batch=batch
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 215, in main
    results = check_for_externals(url, robots=True, batch=batch)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 43, in check_for_externals
    _, code, data, _ = lib.core.common.get_page(full_url)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 332, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False if skip_verf else True, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='news.ycombinator.com', port=443): Read timed out. (read timeout=20)
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:admin.php --verbose --batch -a --x-forward --random-agent --proxy socks5://127.0.0.1:9050 --tamper=lowercase,lowercase,space2comment -W -E`

Log file info:
```2017-12-05 06:31:38,663;zeus-log;DEBUG;loading script 'wallarm'...
2017-12-05 06:31:38,663;zeus-log;DEBUG;loading script 'yunsuo'...
2017-12-05 06:31:38,664;zeus-log;DEBUG;loading script 'bigip'...
2017-12-05 06:31:38,664;zeus-log;DEBUG;loading script 'anquanbao'...
2017-12-05 06:31:38,665;zeus-log;DEBUG;loading script 'generic'...
2017-12-05 06:31:38,665;zeus-log;WARNING;the target URL WAF/IDS/IPS has been identified as 'CloudFlare Web Application Firewall (CloudFlare)'...
2017-12-05 06:31:38,665;zeus-log;DEBUG;loading XML data...
2017-12-05 06:31:38,696;zeus-log;INFO;attempting to get request headers for 'https://news.ycombinator.com/item?id=11489185'...
2017-12-05 06:31:40,815;zeus-log;INFO;found a request cookie, saving to file...
2017-12-05 06:31:40,829;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/news.ycombinator.com(1).log'...
2017-12-05 06:31:40,830;zeus-log;DEBUG;fetched {'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Set-Cookie': '__cfduid=dee753c6cb0e9ddd23fdb329e1251f90d1512477100; expires=Wed, 05-Dec-18 12:31:40 GMT; path=/; domain=.ycombinator.com; HttpOnly', 'Strict-Transport-Security': 'max-age=31556900; includeSubDomains', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare-nginx', 'Connection': 'keep-alive', 'Cache-Control': 'private, max-age=0', 'Date': 'Tue, 05 Dec 2017 12:31:40 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'text/html; charset=utf-8', 'CF-RAY': '3c8706136edf2af1-WAW'}...
2017-12-05 06:31:40,830;zeus-log;WARNING;provided target has protection against clickjacking vulnerabilities...
2017-12-05 06:31:40,830;zeus-log;WARNING;provided target has protection against unencrypted connections (force HTTPS connection)...
2017-12-05 06:31:40,830;zeus-log;INFO;writing found headers to log file...
2017-12-05 06:31:40,832;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/news.ycombinator.com(1).json'...
2017-12-05 06:31:40,832;zeus-log;INFO;parsing robots.txt...
2017-12-05 06:32:01,017;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code 'HTTPSConnectionPool(host='news.ycombinator.com', port=443): Read timed out. (read timeout=20)'...
Traceback (most recent call last):
  File "zeus.py", line 353, in <module>
    __run_attacks_main()
  File "zeus.py", line 305, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1001, in run_attacks
    verbose=verbose, do_threading=do_threading, batch=batch
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 215, in main
    results = check_for_externals(url, robots=True, batch=batch)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 43, in check_for_externals
    _, code, data, _ = lib.core.common.get_page(full_url)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 332, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False if skip_verf else True, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='news.ycombinator.com', port=443): Read timed out. (read timeout=20)

2017-12-05 06:32:01,685;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-05 06:32:01,685;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-05 06:32:01,740;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-05 06:32:01,746;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/27fe53817d66797e6537040e0083fc5d2b457994
