### ISSUE TITLE
Unhandled exception (dDXGAsx)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#230]
Zeus version:
`1.3.19.bd5587`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 359, in <module>
    __run_attacks_main()
  File "zeus.py", line 298, in __run_attacks_main
    identify_plugins=opt.identifyPlugin, identify_waf=opt.identifyProtection
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 263, in main_header_check
    identified_plugin = detect_plugins(url)
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 133, in detect_plugins
    if plugin_detection(html, headers=headers) is True:
TypeError: 'module' object is not callable
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:php?id=10 --identify-waf --identify-plugin -x`

Log file info:
```2017-12-05 12:47:45,538;zeus-log;INFO;log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-15.log'...
2017-12-05 12:47:45,541;zeus-log;INFO;using default search engine...
2017-12-05 12:47:45,541;zeus-log;INFO;starting dork scan with query 'inurl:php?id=10'...
2017-12-05 12:47:45,572;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-12-05 12:47:45,572;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-12-05 12:47:45,572;zeus-log;INFO;attempting to gather query URL...
2017-12-05 12:47:45,573;zeus-log;INFO;setting up virtual display to hide the browser...
2017-12-05 12:47:47,118;zeus-log;INFO;setting the browser...
2017-12-05 12:48:29,058;zeus-log;INFO;browser will open shortly...
2017-12-05 12:48:31,573;zeus-log;INFO;searching search engine using query 'http://google.com'...
2017-12-05 12:48:34,740;zeus-log;INFO;closing the browser and continuing process..
2017-12-05 12:48:36,221;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-12-05 12:48:36,221;zeus-log;INFO;no proxy configuration detected...
2017-12-05 12:48:36,776;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner/1.3.19.bd5587 (Language=Python/2.7.13; Platform=Linux)'...
2017-12-05 12:48:37,096;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/url-log/url-log-13.log'...
2017-12-05 12:48:37,096;zeus-log;INFO;found a total of 21 URLs with given query 'inurl:php?id=10'...
2017-12-05 12:48:37,209;zeus-log;WARNING;ran into unexpected webcache URL skipping...
2017-12-05 12:48:37,209;zeus-log;INFO;currently running on 'https://www.apsf.org/initiatives.' (target #2)...
2017-12-05 12:48:37,209;zeus-log;INFO;checking for HTTP headers...
2017-12-05 12:48:37,210;zeus-log;INFO;checking if target URL is protected by some kind of WAF/IPS/IDS...
2017-12-05 12:48:39,238;zeus-log;WARNING;the target URL WAF/IDS/IPS has been identified as 'CloudFlare Web Application Firewall (CloudFlare)'...
2017-12-05 12:48:39,238;zeus-log;INFO;attempting to identify plugins...
2017-12-05 12:48:39,910;zeus-log;ERROR;[7;31;31mran into exception ''module' object is not callable' exception has been saved to log file...
Traceback (most recent call last):
  File "zeus.py", line 359, in <module>
    __run_attacks_main()
  File "zeus.py", line 298, in __run_attacks_main
    identify_plugins=opt.identifyPlugin, identify_waf=opt.identifyProtection
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 263, in main_header_check
    identified_plugin = detect_plugins(url)
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 133, in detect_plugins
    if plugin_detection(html, headers=headers) is True:
TypeError: 'module' object is not callable

2017-12-05 12:48:40,251;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-05 12:48:40,252;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-05 12:48:40,359;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-05 12:48:40,359;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
oops this is suppose to be a surprise, working on plugin identification
