### ISSUE TITLE
Unhandled exception (gCwPQzS)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#233]
Zeus version:
`1.4`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 179, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 263, in main_header_check
    req, status, html, headers = get_page(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 332, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:cp.php?cl=cp nowmenuid= --verbose --batch -P --x-forward --random-agent --proxy socks5://127.0.0.1:9050 --tamper=url,base64,enclosebrackets,unicode -W -E --identify-waf --identify-plugins`

Log file info:
```2017-12-06 09:51:40,535;zeus-log;DEBUG;loading script 'atomfeed'...
2017-12-06 09:51:40,536;zeus-log;DEBUG;loading script 'html5'...
2017-12-06 09:51:40,538;zeus-log;DEBUG;loading script '3com'...
2017-12-06 09:51:40,542;zeus-log;DEBUG;loading script 'googleapi'...
2017-12-06 09:51:40,544;zeus-log;DEBUG;loading script '1024'...
2017-12-06 09:51:40,547;zeus-log;DEBUG;loading script 'accellion'...
2017-12-06 09:51:40,547;zeus-log;DEBUG;loading script 'rssfeed'...
2017-12-06 09:51:40,549;zeus-log;DEBUG;loading script '4images'...
2017-12-06 09:51:40,551;zeus-log;DEBUG;loading script 'openxchange'...
2017-12-06 09:51:40,552;zeus-log;INFO;possible plugin identified as 'JQuery'...
2017-12-06 09:51:40,553;zeus-log;DEBUG;loading XML data...
2017-12-06 09:51:40,553;zeus-log;INFO;attempting to get request headers for 'http://www.kedn-china.com/cp.php?cl=cp&nowmenuid=2537'...
2017-12-06 09:51:40,554;zeus-log;INFO;found a request cookie, saving to file...
2017-12-06 09:51:40,554;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/www.kedn(2).log'...
2017-12-06 09:51:40,555;zeus-log;DEBUG;fetched {'X-Powered-By': 'PHP/5.4.45', 'Transfer-Encoding': 'chunked', 'Set-Cookie': 'PHPSESSID=unlfais6d1n6ap8avad8mueta5; path=/, language=en; expires=Thu, 07-Dec-2017 15:52:37 GMT; path=/', 'Expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'Vary': 'Accept-Encoding', 'Server': 'nginx/1.13.3', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Date': 'Wed, 06 Dec 2017 15:51:37 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Encoding': 'gzip'}...
2017-12-06 09:51:40,555;zeus-log;INFO;writing found headers to log file...
2017-12-06 09:51:40,555;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.kedn(2).json'...
2017-12-06 09:51:40,556;zeus-log;INFO;searching public PGP files with given query 'kedn-china'...
2017-12-06 09:51:41,077;zeus-log;WARNING;did not find anything using query 'kedn-china'...
2017-12-06 09:51:41,078;zeus-log;INFO;currently running on 'http://www.kinggardentools.com/cp.php?cl%3Dcp%26nowmenuid%3D20110334%2Binurl:cp.php?cl%3Dcp' (target #5)...
2017-12-06 09:51:41,079;zeus-log;INFO;fetching target meta-data...
2017-12-06 09:51:41,079;zeus-log;INFO;random IP address generated for header '249.70.155.23'...
2017-12-06 09:51:41,080;zeus-log;INFO;random IP address generated for header '181.59.69.101'...
2017-12-06 09:51:41,080;zeus-log;INFO;random IP address generated for header '187.216.107.22'...
2017-12-06 09:51:42,491;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code '('Connection aborted.', BadStatusLine("''",))'...
Traceback (most recent call last):
  File "zeus.py", line 179, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 263, in main_header_check
    req, status, html, headers = get_page(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 332, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

2017-12-06 09:51:42,723;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-06 09:51:42,723;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-06 09:51:42,730;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-06 09:51:42,730;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/b86db8008fdfffbcc14277b1ffe9f6c5075f352b
