### ISSUE TITLE
Unhandled exception (vtkoNxB)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#234]
Zeus version:
`1.4`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 229, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 263, in main_header_check
    req, status, html, headers = get_page(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 332, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: SOCKSHTTPConnectionPool(host='www.stylepanels.ie', port=80): Max retries exceeded with url: /admin/shop/%0A?Connection=close&X-Forwarded-For=198.158.99.38%2C+132.39.202.177%2C+15.19.203.58&User-Agent=Mozilla%2F4.0+%28compatible%3B+MSIE+4.5%3B+Windows+98%3B%29 (Caused by ConnectTimeoutError(<urllib3.contrib.socks.SOCKSConnection object at 0x7ff2265e6510>, 'Connection to www.stylepan...
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle: "index of/admin" --verbose --batch -w --x-forward --random-agent --proxy socks5://127.0.0.1:9050 --tamper=base64,randomcase,space2comment,appendnull -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 09:52:03,848;zeus-log;DEBUG;loading script 'atomfeed'...
2017-12-06 09:52:03,849;zeus-log;DEBUG;loading script 'html5'...
2017-12-06 09:52:03,850;zeus-log;DEBUG;loading script '3com'...
2017-12-06 09:52:03,853;zeus-log;DEBUG;loading script 'googleapi'...
2017-12-06 09:52:03,854;zeus-log;DEBUG;loading script '1024'...
2017-12-06 09:52:03,855;zeus-log;DEBUG;loading script 'accellion'...
2017-12-06 09:52:03,856;zeus-log;DEBUG;loading script 'rssfeed'...
2017-12-06 09:52:03,857;zeus-log;DEBUG;loading script '4images'...
2017-12-06 09:52:03,858;zeus-log;DEBUG;loading script 'openxchange'...
2017-12-06 09:52:03,860;zeus-log;INFO;possible plugin identified as 'JQuery'...
2017-12-06 09:52:03,860;zeus-log;DEBUG;loading XML data...
2017-12-06 09:52:03,860;zeus-log;INFO;attempting to get request headers for 'http://www.caritasdeitapipoca.org.br/admin/upload/'...
2017-12-06 09:52:03,861;zeus-log;DEBUG;fetched {'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Server': 'nginx/1.12.2', 'Last-Modified': 'Thu, 27 Feb 2014 01:43:54 GMT', 'Connection': 'keep-alive', 'Date': 'Wed, 06 Dec 2017 15:52:02 GMT', 'Content-Type': 'text/html'}...
2017-12-06 09:52:03,861;zeus-log;INFO;writing found headers to log file...
2017-12-06 09:52:03,862;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.caritasdeitapipoca.org.br-headers.json'...
2017-12-06 09:52:03,862;zeus-log;INFO;performing WhoIs lookup on given domain 'www.caritasdeitapipoca.org.br'...
2017-12-06 09:52:05,233;zeus-log;INFO;discovered raw information...
2017-12-06 09:52:05,234;zeus-log;INFO;gathering interesting information...
2017-12-06 09:52:05,235;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/whois/www.caritasdeitapipoca.org.br-whois.json'...
2017-12-06 09:52:05,235;zeus-log;INFO;currently running on 'http://www.stylepanels.ie/admin/shop/' (target #5)...
2017-12-06 09:52:05,236;zeus-log;INFO;fetching target meta-data...
2017-12-06 09:52:05,236;zeus-log;INFO;random IP address generated for header '198.158.99.38'...
2017-12-06 09:52:05,236;zeus-log;INFO;random IP address generated for header '132.39.202.177'...
2017-12-06 09:52:05,236;zeus-log;INFO;random IP address generated for header '15.19.203.58'...
2017-12-06 09:52:25,576;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code 'SOCKSHTTPConnectionPool(host='www.stylepanels.ie', port=80): Max retries exceeded with url: /admin/shop/%0A?Connection=close&X-Forwarded-For=198.158.99.38%2C+132.39.202.177%2C+15.19.203.58&User-Agent=Mozilla%2F4.0+%28compatible%3B+MSIE+4.5%3B+Windows+98%3B%29 (Caused by ConnectTimeoutError(<urllib3.contrib.socks.SOCKSConnection object at 0x7ff2265e6510>, 'Connection to www.stylepanels.ie timed out. (connect timeout=20)'))'...
Traceback (most recent call last):
  File "zeus.py", line 229, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 263, in main_header_check
    req, status, html, headers = get_page(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 332, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: SOCKSHTTPConnectionPool(host='www.stylepanels.ie', port=80): Max retries exceeded with url: /admin/shop/%0A?Connection=close&X-Forwarded-For=198.158.99.38%2C+132.39.202.177%2C+15.19.203.58&User-Agent=Mozilla%2F4.0+%28compatible%3B+MSIE+4.5%3B+Windows+98%3B%29 (Caused by ConnectTimeoutError(<urllib3.contrib.socks.SOCKSConnection object at 0x7ff2265e6510>, 'Connection to www.stylepanels.ie timed out. (connect timeout=20)'))

2017-12-06 09:52:25,818;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-06 09:52:25,818;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-06 09:52:25,822;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-06 09:52:25,823;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/b86db8008fdfffbcc14277b1ffe9f6c5075f352b
