### ISSUE TITLE
Unhandled exception (XRBencU)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#239]
Zeus version:
`1.4.1.b86db8`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 179, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 280, in main_header_check
    _, waf_status, waf_html, waf_headers = get_page(waf_url, xforward=xforward, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 338, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:cp.php?cl=cp nowmenuid= --verbose --batch -g --x-forward --random-agent --tamper=lowercase,randomcase,appendnull -W -E --identify-waf --identify-plugins`

Log file info:
```2017-12-06 11:04:26,881;zeus-log;INFO;found a webcache URL, extracting...
2017-12-06 11:04:26,882;zeus-log;DEBUG;found 'http://www.sunstar.cc/cp.php?cl%3Dcp%26nowmenuid%3D11802%2Binurl:cp.php?cl%3Dcp'...
2017-12-06 11:04:26,882;zeus-log;INFO;found a webcache URL, extracting...
2017-12-06 11:04:26,882;zeus-log;DEBUG;found 'http://unismartltd.com/cp.php?cl%3Dcp%26nowmenuid%3D20111503%2Binurl:cp.php?cl%3Dcp'...
2017-12-06 11:04:26,882;zeus-log;INFO;found a webcache URL, extracting...
2017-12-06 11:04:26,883;zeus-log;DEBUG;found 'http://www.szjyd.cn/cp.php?cl%3Dcp%26nowmenuid%3D10061632%2Binurl:cp.php?cl%3Dcp'...
2017-12-06 11:04:26,883;zeus-log;INFO;found a webcache URL, extracting...
2017-12-06 11:04:26,883;zeus-log;DEBUG;found 'http://www.kinggardentools.com/cp.php?cl%3Dcp%26nowmenuid%3D20110334%2Binurl:cp.php?cl%3Dcp'...
2017-12-06 11:04:26,883;zeus-log;INFO;found a webcache URL, extracting...
2017-12-06 11:04:26,884;zeus-log;DEBUG;found 'http://www.kedn-china.com/cp.php?cl%3Dcp%26nowmenuid%3D2537%2Binurl:cp.php?cl%3Dcp'...
2017-12-06 11:04:26,884;zeus-log;INFO;found a webcache URL, extracting...
2017-12-06 11:04:26,884;zeus-log;DEBUG;found 'http://www.forungloves.com/cp.php?cl%3Dcp%26nowmenuid%3D20112315%2Binurl:cp.php?cl%3Dcp'...
2017-12-06 11:04:26,885;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/url-log/url-log-1.log'...
2017-12-06 11:04:26,885;zeus-log;INFO;found a total of 20 URLs with given query 'inurl:cp.php?cl=cp nowmenuid='...
2017-12-06 11:04:26,887;zeus-log;INFO;currently running on 'http://www.kedn-china.com/cp.php?cl%3Dcp%26nowmenuid%3D2537%2Binurl:cp.php?cl%3Dcp' (target #1)...
2017-12-06 11:04:26,887;zeus-log;INFO;fetching target meta-data...
2017-12-06 11:04:26,887;zeus-log;INFO;random IP address generated for header '214.193.104.172'...
2017-12-06 11:04:26,888;zeus-log;INFO;random IP address generated for header '55.82.100.253'...
2017-12-06 11:04:26,888;zeus-log;INFO;random IP address generated for header '205.170.136.184'...
2017-12-06 11:04:27,186;zeus-log;INFO;detecting target charset...
2017-12-06 11:04:27,186;zeus-log;INFO;target charset appears to be 'UTF-8'...
2017-12-06 11:04:27,187;zeus-log;INFO;random IP address generated for header '96.189.206.12'...
2017-12-06 11:04:27,187;zeus-log;INFO;random IP address generated for header '52.196.191.127'...
2017-12-06 11:04:27,187;zeus-log;INFO;random IP address generated for header '178.250.129.226'...
2017-12-06 11:04:27,312;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code '('Connection aborted.', error(104, 'Connection reset by peer'))'...
Traceback (most recent call last):
  File "zeus.py", line 179, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 280, in main_header_check
    _, waf_status, waf_html, waf_headers = get_page(waf_url, xforward=xforward, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 338, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

2017-12-06 11:28:12,486;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-06 11:28:12,487;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-06 11:28:12,494;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-06 11:28:12,494;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
fixed via https://github.com/Ekultek/Zeus-Scanner/commit/4e0945b842a4640db0b4cb70648279738efcb1f1
