### ISSUE TITLE
Unhandled exception (mEoJoBh)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#242]
Zeus version:
`1.4.1.b86db8`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 179, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 263, in main_header_check
    req, status, html, headers = get_page(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 338, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
````

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:cp.php?cl=cp nowmenuid= --verbose --batch -x --x-forward --random-agent --tamper=url,lowercase,base64,hex -W -E --identify-waf --identify-plugins`

Log file info:
```2017-12-06 12:25:06,448;zeus-log;DEBUG;host 'http://www.m-legend.com/cp.php?cl=cp&nowmenuid=20001627' does not appear to be vulnerable to XSS attacks with payload 'cl=cp&nowmenuid=200016270x66adce237eb970a'...
2017-12-06 12:25:06,668;zeus-log;INFO;trying payload 'cl=cp&nowmenuid=200016270x1e7ea3909a332baf'...
2017-12-06 12:25:06,668;zeus-log;DEBUG;host 'http://www.m-legend.com/cp.php?cl=cp&nowmenuid=20001627' does not appear to be vulnerable to XSS attacks with payload 'cl=cp&nowmenuid=200016270x1e7ea3909a332baf'...
2017-12-06 12:25:06,902;zeus-log;INFO;trying payload 'cl=cp&nowmenuid=200016270x19c74335e8724ac'...
2017-12-06 12:25:06,903;zeus-log;DEBUG;host 'http://www.m-legend.com/cp.php?cl=cp&nowmenuid=20001627' does not appear to be vulnerable to XSS attacks with payload 'cl=cp&nowmenuid=200016270x19c74335e8724ac'...
2017-12-06 12:25:07,118;zeus-log;INFO;trying payload 'cl=cp&nowmenuid=200016270x115d4c2543e10ac'...
2017-12-06 12:25:07,120;zeus-log;DEBUG;host 'http://www.m-legend.com/cp.php?cl=cp&nowmenuid=20001627' does not appear to be vulnerable to XSS attacks with payload 'cl=cp&nowmenuid=200016270x115d4c2543e10ac'...
2017-12-06 12:25:07,364;zeus-log;INFO;trying payload 'cl=cp&nowmenuid=200016270x580af5deed68fd2a'...
2017-12-06 12:25:07,364;zeus-log;DEBUG;host 'http://www.m-legend.com/cp.php?cl=cp&nowmenuid=20001627' does not appear to be vulnerable to XSS attacks with payload 'cl=cp&nowmenuid=200016270x580af5deed68fd2a'...
2017-12-06 12:25:07,503;zeus-log;ERROR;payload 'cl=cp&nowmenuid=200016270x72bdd65814ae38a4' caused a connection error, assuming no good and continuing...
2017-12-06 12:25:07,722;zeus-log;INFO;trying payload 'cl=cp&nowmenuid=200016270x628f2d295de9842f'...
2017-12-06 12:25:07,722;zeus-log;DEBUG;host 'http://www.m-legend.com/cp.php?cl=cp&nowmenuid=20001627' does not appear to be vulnerable to XSS attacks with payload 'cl=cp&nowmenuid=200016270x628f2d295de9842f'...
2017-12-06 12:25:07,957;zeus-log;INFO;trying payload 'cl=cp&nowmenuid=200016270x48cc0fd09e4a78'...
2017-12-06 12:25:07,957;zeus-log;DEBUG;host 'http://www.m-legend.com/cp.php?cl=cp&nowmenuid=20001627' does not appear to be vulnerable to XSS attacks with payload 'cl=cp&nowmenuid=200016270x48cc0fd09e4a78'...
2017-12-06 12:25:08,211;zeus-log;INFO;trying payload 'cl=cp&nowmenuid=200016270x2dfbb8c96613a87'...
2017-12-06 12:25:08,211;zeus-log;DEBUG;host 'http://www.m-legend.com/cp.php?cl=cp&nowmenuid=20001627' does not appear to be vulnerable to XSS attacks with payload 'cl=cp&nowmenuid=200016270x2dfbb8c96613a87'...
2017-12-06 12:25:08,438;zeus-log;INFO;trying payload 'cl=cp&nowmenuid=200016270x7f1cc5699caf4eab'...
2017-12-06 12:25:08,438;zeus-log;DEBUG;host 'http://www.m-legend.com/cp.php?cl=cp&nowmenuid=20001627' does not appear to be vulnerable to XSS attacks with payload 'cl=cp&nowmenuid=200016270x7f1cc5699caf4eab'...
2017-12-06 12:25:08,438;zeus-log;ERROR;host 'http://www.m-legend.com/cp.php?cl=cp&nowmenuid=20001627' does not appear to be vulnerable to XSS attacks...
2017-12-06 12:25:08,439;zeus-log;INFO;currently running on 'http://www.wintechpil.com/cp.php?cl=cp&nowmenuid=20112301&ppid=20112300' (target #7)...
2017-12-06 12:25:08,439;zeus-log;INFO;fetching target meta-data...
2017-12-06 12:25:08,440;zeus-log;INFO;random IP address generated for header '48.65.139.157'...
2017-12-06 12:25:08,440;zeus-log;INFO;random IP address generated for header '61.224.122.111'...
2017-12-06 12:25:08,440;zeus-log;INFO;random IP address generated for header '121.88.248.17'...
2017-12-06 12:25:09,006;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code '('Connection aborted.', error(104, 'Connection reset by peer'))'...
Traceback (most recent call last):
  File "zeus.py", line 179, in <module>
    __run_attacks_main()
  File "zeus.py", line 117, in __run_attacks_main
    show_description=opt.showPluginDescription
  File "/home/baal/bin/python/zeus-scanner/lib/header_check/__init__.py", line 263, in main_header_check
    req, status, html, headers = get_page(url, proxy=proxy, agent=agent, xforward=xforward)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 338, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

2017-12-06 12:25:09,700;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-12-06 12:25:09,700;zeus-log;INFO;[32mgetting authorization...[0m
2017-12-06 12:25:09,727;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-12-06 12:25:09,729;zeus-log;INFO;[32mattempting to get firefox browser version...[0m
```

**Comment by Ekultek** [comment]
Duplicate of #239
