### ISSUE TITLE
Unhandled exception (VvNBXgj)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#256]
Zeus version:
`1.4.3.6e3d4b`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
```

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle: "index of/root" --verbose --batch -g --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 23:23:31,670;zeus-log;DEBUG;loading script 'bomgar'
2017-12-06 23:23:31,688;zeus-log;DEBUG;loading script 'mssqlreportmanager'
2017-12-06 23:23:31,705;zeus-log;DEBUG;loading script 'opengraph'
2017-12-06 23:23:31,707;zeus-log;DEBUG;loading script 'atomfeed'
2017-12-06 23:23:31,714;zeus-log;DEBUG;loading script 'html5'
2017-12-06 23:23:31,729;zeus-log;DEBUG;loading script '3com'
2017-12-06 23:23:31,880;zeus-log;DEBUG;loading script 'moodle'
2017-12-06 23:23:31,888;zeus-log;DEBUG;loading script 'googleapi'
2017-12-06 23:23:31,893;zeus-log;DEBUG;loading script '1024'
2017-12-06 23:23:32,057;zeus-log;DEBUG;loading script 'accellion'
2017-12-06 23:23:32,058;zeus-log;DEBUG;loading script 'rssfeed'
2017-12-06 23:23:32,063;zeus-log;DEBUG;loading script '4images'
2017-12-06 23:23:32,070;zeus-log;DEBUG;loading script 'openxchange'
2017-12-06 23:23:32,076;zeus-log;INFO;possible plugin identified as 'JQuery'
2017-12-06 23:23:32,076;zeus-log;INFO;possible plugin identified as 'Open-Graph-Protocol'
2017-12-06 23:23:32,076;zeus-log;INFO;possible plugin identified as 'Google API'
2017-12-06 23:23:32,077;zeus-log;DEBUG;loading XML data
2017-12-06 23:23:32,111;zeus-log;INFO;attempting to get request headers for 'https://link.springer.com/content/pdf/10.1007/s00784-013-0965-8.pdf'
2017-12-06 23:23:32,112;zeus-log;INFO;found a request cookie, saving to file
2017-12-06 23:23:32,113;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/cookies/link.springer.com-cookie.log'
2017-12-06 23:23:32,114;zeus-log;DEBUG;fetched {'X-Timer': 'S1512624210.507137,VS0,VE393', 'Via': '1.1 varnish', 'X-Cache': 'MISS', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Set-Cookie': 'sim-inst-token=1::1512654209414:c4456ade;Path=/;Domain=.springer.com;HttpOnly', 'Accept-Ranges': 'bytes', 'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'Vary': 'Accept-Encoding', 'X-Vcap-Request-Id': '0e3aba21-b74c-461c-4688-890bd0cd0b46, 2adaeae6-abe3-48d8-635f-0b64e542e8a7', 'Server': 'openresty', 'Connection': 'keep-alive', 'X-Served-By': 'bunsen.live.cf.private.springer.com, cache-dfw18641-DFW', 'X-Cache-Hits': '0', 'Cache-Control': 'private, max-age=0, must-revalidate', 'Date': 'Thu, 07 Dec 2017 05:23:29 GMT', 'Content-Type': 'text/html;charset=utf-8', 'Age': '0'}
2017-12-06 23:23:32,114;zeus-log;INFO;writing found headers to log file
2017-12-06 23:23:32,115;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/link.springer.com-headers.json'
2017-12-06 23:23:32,150;zeus-log;INFO;searching a total of 5 pages of Gists for 'link.springer.com'
2017-12-06 23:23:32,150;zeus-log;INFO;fetching all Gists on page #1
2017-12-06 23:23:32,762;zeus-log;INFO;fetching all Gists on page #2
2017-12-06 23:23:33,305;zeus-log;INFO;fetching all Gists on page #3
2017-12-06 23:23:33,829;zeus-log;INFO;fetching all Gists on page #4
2017-12-06 23:23:34,434;zeus-log;INFO;fetching all Gists on page #5
2017-12-06 23:23:35,030;zeus-log;DEBUG;found a total of 52 links to search
2017-12-06 23:23:35,793;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/78d9d3b8448898e7650c199d56681e27/raw/5df6b3b31b1d88b93e7b88a8e75536c6b33c7cd5/brlog.trunk-test.20171207-140531'
2017-12-06 23:23:37,078;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/x831617/3d434d22bad00b4aa6f89dd057006fe4/raw/6106e4bb52e6cf2e903851c2d5923f0465518852/gistfile1.txt'
2017-12-06 23:23:38,472;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/40536a74787c6c67119faa45220fe123/raw/5d6baf4c1a2f890bea59b1381a80bb662ff46931/brlog.trunk-test.20171207-142138'
2017-12-06 23:23:39,930;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/theatlasroom/b09c9ef74aec56858383a11b28b3f8df/raw/239b238f870c10dbb54027bbe2bbb9b2c545ebaf/glossing-over-ethereum.md'
2017-12-06 23:23:41,832;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/TakashiYoshinaga/1ab5662cc38ad811d0aad9e11e1a0eca/raw/e51661fc01a9e4f99ecc823cf5047cbc9d52ae49/WebARSample.html'
2017-12-06 23:23:43,228;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/bb98542f524d307378eb1327e23ceb6c/raw/80b9fbce9daa43d71a75187f62665db90b10c135/brlog.trunk-test.20171207-141639'
2017-12-06 23:23:46,442;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/nitinware/e611ff7caf61ddf62c6652c359df83e1/raw/a9df894b278261c426ce889854ec719e3e2923f8/temperature.json'
2017-12-06 23:23:47,696;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/MadRabbit/04be36aacebc7ce582e53362c8c63d63/raw/a81794b971993bc7d562315376740516457033a4/index.jsx'
2017-12-06 23:23:48,820;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/81b9e8b51b34f729b6957d96812dce6e/raw/775fb73394951aea5bf8c74e6b1089235c6a39d5/brlog.trunk-test.20171207-141653'
2017-12-06 23:23:50,042;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/9fdb2a59ae754ccafbfa60eb42f5e4d5/raw/52f8b3e0e8d2d90d70f2c5df8bad6d7fd49822e4/brlog.trunk-test.20171207-141404'
2017-12-06 23:23:52,347;zeus-log;ERROR;[7;31;31mGist search has failed with error ''NoneType' object is not iterable'
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable

2017-12-06 23:23:52,825;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-06 23:23:52,825;zeus-log;INFO;[32mgetting authorization[0m
2017-12-06 23:23:52,867;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-06 23:23:52,867;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
should be patched via https://github.com/Ekultek/Zeus-Scanner/commit/43199d690d4a268e3d9154dca380d60e6f676b5a gonna leave this open for a little bit

**Comment by Ekultek** [comment]
fixed via https://github.com/Ekultek/Zeus-Scanner/commit/82f0c1f1ec7639017456c66d3bbfa5013ee220c8
