### ISSUE TITLE
Unhandled exception (xqAsoCr)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#270]
Zeus version:
`1.4.3.6e3d4b`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable
```

Running details:
`Linux-4.10.0-40-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d allintitle:"Network Camera NetworkCamera" --verbose --batch -g --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-06 23:37:58,345;zeus-log;DEBUG;loading script 'ihtml'
2017-12-06 23:37:58,346;zeus-log;DEBUG;loading script '360'
2017-12-06 23:37:58,348;zeus-log;DEBUG;loading script '3dcart'
2017-12-06 23:37:58,349;zeus-log;DEBUG;loading script 'b2evolution'
2017-12-06 23:37:58,351;zeus-log;DEBUG;loading script 'bmcremedy'
2017-12-06 23:37:58,352;zeus-log;DEBUG;loading script 'abyss'
2017-12-06 23:37:58,353;zeus-log;DEBUG;loading script '68classified'
2017-12-06 23:37:58,354;zeus-log;DEBUG;loading script 'bomgar'
2017-12-06 23:37:58,356;zeus-log;DEBUG;loading script 'mssqlreportmanager'
2017-12-06 23:37:58,357;zeus-log;DEBUG;loading script 'opengraph'
2017-12-06 23:37:58,359;zeus-log;DEBUG;loading script 'atomfeed'
2017-12-06 23:37:58,360;zeus-log;DEBUG;loading script 'html5'
2017-12-06 23:37:58,361;zeus-log;DEBUG;loading script '3com'
2017-12-06 23:37:58,364;zeus-log;DEBUG;loading script 'moodle'
2017-12-06 23:37:58,366;zeus-log;DEBUG;loading script 'googleapi'
2017-12-06 23:37:58,367;zeus-log;DEBUG;loading script '1024'
2017-12-06 23:37:58,369;zeus-log;DEBUG;loading script 'accellion'
2017-12-06 23:37:58,369;zeus-log;DEBUG;loading script 'rssfeed'
2017-12-06 23:37:58,371;zeus-log;DEBUG;loading script '4images'
2017-12-06 23:37:58,372;zeus-log;DEBUG;loading script 'openxchange'
2017-12-06 23:37:58,374;zeus-log;INFO;possible plugin identified as 'JQuery'
2017-12-06 23:37:58,374;zeus-log;DEBUG;loading XML data
2017-12-06 23:37:58,374;zeus-log;INFO;attempting to get request headers for 'http://www.securitysystemsnews.com/article/body-camera-company-opens-dealer-network'
2017-12-06 23:37:58,375;zeus-log;DEBUG;fetched {'Content-Length': '4454', 'X-Drupal-Cache': 'MISS', 'Content-Language': 'en', 'X-Content-Type-Options': 'nosniff, nosniff', 'X-Powered-By': 'PHP/5.3.3', 'Expires': 'Sun, 19 Nov 1978 05:00:00 GMT', 'Vary': 'Cookie,Accept-Encoding', 'Keep-Alive': 'timeout=3, max=300', 'Server': 'Apache/2.2.3 (Red Hat)', 'Last-Modified': 'Thu, 07 Dec 2017 05:37:57 GMT', 'Connection': 'Keep-Alive', 'Etag': '"1512625077-1"', 'Cache-Control': 'public, max-age=0', 'Date': 'Thu, 07 Dec 2017 05:37:57 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Type': 'text/html; charset=utf-8', 'Content-Encoding': 'gzip', 'X-Generator': 'Drupal 7 (http://drupal.org)'}
2017-12-06 23:37:58,375;zeus-log;WARNING;provided target has protection against MIME type attacks
2017-12-06 23:37:58,375;zeus-log;WARNING;provided target has protection against clickjacking vulnerabilities
2017-12-06 23:37:58,375;zeus-log;INFO;writing found headers to log file
2017-12-06 23:37:58,376;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.securitysystemsnews.com-headers.json'
2017-12-06 23:37:58,377;zeus-log;INFO;searching a total of 5 pages of Gists for 'www.securitysystemsnews.com'
2017-12-06 23:37:58,377;zeus-log;INFO;fetching all Gists on page #1
2017-12-06 23:37:58,920;zeus-log;INFO;fetching all Gists on page #2
2017-12-06 23:37:59,402;zeus-log;INFO;fetching all Gists on page #3
2017-12-06 23:37:59,915;zeus-log;INFO;fetching all Gists on page #4
2017-12-06 23:38:00,480;zeus-log;INFO;fetching all Gists on page #5
2017-12-06 23:38:01,012;zeus-log;DEBUG;found a total of 52 links to search
2017-12-06 23:38:01,656;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/rajegannathan/222d72698580c2e9b2bdbf2cc887c12d/raw/badbb7146de1bb73a72af49a14f6bbec9bbd9d65/racist-ai.ipynb'
2017-12-06 23:38:02,572;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/debashisbarman/f2a708ff8fb8e9a68463ea014e73b062/raw/6553c03d8632dfe021114e74019e7f4dd3e93849/package.json'
2017-12-06 23:38:03,760;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/d14a2f9a72c2d721745992b56bc53d11/raw/6569bf2cfbe63f7dd7de177f1bc042754288e52b/brlog.trunk-test.20171207-142233'
2017-12-06 23:38:05,129;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/499940e908907614cff8f076937be6c2/raw/42294004b447d32f843d6ebd11f5d89dc6a95489/brlog.trunk-test.20171207-143132'
2017-12-06 23:38:06,396;zeus-log;DEBUG;found raw Gist URL 'https://gist.github.com/ko1/eb5258165c582ded1c8328438e4b7f6b/raw/059a54383f2781763f91892b690ac8bb0f08eb1a/brlog.trunk-test.20171207-143100'
2017-12-06 23:38:07,744;zeus-log;ERROR;[7;31;31mGist search has failed with error ''NoneType' object is not iterable'
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 153, in github_gist_search_main
    gist, gist_link = get_raw_html(link, verbose=verbose)
TypeError: 'NoneType' object is not iterable

2017-12-06 23:38:07,880;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-06 23:38:07,880;zeus-log;INFO;[32mgetting authorization[0m
2017-12-06 23:38:07,881;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-06 23:38:07,881;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
duplicate of #256
