### ISSUE TITLE
Unhandled exception (txlButF)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#287]
Zeus version:
`1.4.6`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/var/blackwidow/__init__.py", line 45, in test_connection
    proxy=self.proxy
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 335, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 405, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 302, in get_connection
    proxy = prepend_scheme_if_needed(proxy, 'http')
  File "/home/baal/.local/lib/python2.7/site-packages/requests/utils.py", line 822, in prepend_scheme_if_needed
    scheme, netloc, path, params, query, fragment = urlparse(url, new_scheme)
  File "/usr/lib/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python2.7/urlparse.py", line 176, in urlsplit
    cached = _parse_cache.get(key, None)
TypeError: unhashable type: 'dict'
```

Running details:
`Linux-4.10.0-42-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -b http://www.grayhatforum.org --proxy=socks5://127.0.0.1:9050 --random-agent`

Log file info:
```2017-12-08 11:41:38,771;zeus-log;INFO;log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-12.log'
2017-12-08 11:41:38,771;zeus-log;WARNING;timeout will be increased to 40s due to Tor being used
2017-12-08 11:41:38,772;zeus-log;INFO;random agent being used 'Mozilla/5.0 (X11; U; Linux i686 (x86_64); en-US; rv:1.8.0.3) Gecko/20060426 Firefox/1.5.0.3'
2017-12-08 11:41:38,772;zeus-log;INFO;using default search engine
2017-12-08 11:41:38,791;zeus-log;INFO;starting blackwidow on 'http://www.grayhatforum.org'
2017-12-08 11:41:38,819;zeus-log;ERROR;[7;31;31mfailed to connect to 'http://www.grayhatforum.org' received error 'unhashable type: 'dict''
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/var/blackwidow/__init__.py", line 45, in test_connection
    proxy=self.proxy
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 335, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 405, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/adapters.py", line 302, in get_connection
    proxy = prepend_scheme_if_needed(proxy, 'http')
  File "/home/baal/.local/lib/python2.7/site-packages/requests/utils.py", line 822, in prepend_scheme_if_needed
    scheme, netloc, path, params, query, fragment = urlparse(url, new_scheme)
  File "/usr/lib/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python2.7/urlparse.py", line 176, in urlsplit
    cached = _parse_cache.get(key, None)
TypeError: unhashable type: 'dict'

2017-12-08 11:41:49,389;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-08 11:41:49,390;zeus-log;INFO;[32mgetting authorization[0m
2017-12-08 11:41:49,399;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-08 11:41:49,400;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/a30256289398affe8ee5fce97cabf42201b6e23d
