### ISSUE TITLE
Unhandled exception (GsHiiIi)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#289]
Zeus version:
`1.4.7`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 160, in <module>
    show_success=opt.showSuccessRate
  File "/home/baal/bin/python/zeus-scanner/var/search/selenium_search.py", line 401, in parse_search_results
    file_path = write_to_log_file(true_retval, URL_LOG_PATH, URL_FILENAME)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 177, in write_to_log_file
    item = item.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

Running details:
`Linux-4.10.0-42-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d ext:conf inurl:rsyncd.conf -cvs -man --verbose --batch -w --x-forward --random-agent -W -E --identify-waf --identify-plugins`

Log file info:
```2017-12-09 09:58:09,780;zeus-log;DEBUG;found 'https://files.directadmin.com/services/all/rsyncd.conf'
2017-12-09 09:58:09,780;zeus-log;DEBUG;found 'https://files.directadmin.com/services/all/<b'
2017-12-09 09:58:09,784;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:L8UqaQwAT8QJ:https://files.directadmin.com/services/all/rsyncd.conf%2Bext:conf+inurl:rsyncd.conf+-cvs+-man&hl=en&gbv=2&ct=clnk'
2017-12-09 09:58:09,785;zeus-log;DEBUG;found 'https://svn.apache.org/repos/asf/spamassassin/trunk/build/automc/etc-rsyncd.conf'
2017-12-09 09:58:09,785;zeus-log;DEBUG;found 'https://svn.apache.org/repos/asf/spamassassin/.../etc-<b'
2017-12-09 09:58:09,786;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:IKrk3KV1ONcJ:https://svn.apache.org/repos/asf/spamassassin/trunk/build/automc/etc-rsyncd.conf%2Bext:conf+inurl:rsyncd.conf+-cvs+-man&hl=en&gbv=2&ct=clnk'
2017-12-09 09:58:09,786;zeus-log;DEBUG;found 'https://svn.apache.org/repos/asf/spamassassin/trunk/build/automc/etc-rsyncd.conf'
2017-12-09 09:58:09,787;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:FbPq_nb9lqMJ:ftp://distro.ibiblio.org/rootlinux/rootlinux-ports/net/rsync/rsyncd.conf%2Bext:conf+inurl:rsyncd.conf+-cvs+-man&hl=en&gbv=2&ct=clnk'
2017-12-09 09:58:09,787;zeus-log;DEBUG;found 'https://build.opensuse.org/package/view_file/network/rsync/rsyncd.conf?expand=1'
2017-12-09 09:58:09,787;zeus-log;DEBUG;found 'https://build.opensuse.org/package/view_file/.../<b'
2017-12-09 09:58:09,788;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:hhFlfxukOI8J:https://build.opensuse.org/package/view_file/network/rsync/rsyncd.conf?expand%3D1%2Bext:conf+inurl:rsyncd.conf+-cvs+-man&hl=en&gbv=2&ct=clnk'
2017-12-09 09:58:09,788;zeus-log;DEBUG;found 'https://git.ustclug.org/mirrors/mirrors-system-conf/blob/master/rsyncd.conf'
2017-12-09 09:58:09,788;zeus-log;DEBUG;found 'https://git.ustclug.org/mirrors/mirrors-system-conf/.../<b'
2017-12-09 09:58:09,790;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:0tKmZQzNAmcJ:https://git.ustclug.org/mirrors/mirrors-system-conf/blob/master/rsyncd.conf%2Bext:conf+inurl:rsyncd.conf+-cvs+-man&hl=en&gbv=2&ct=clnk'
2017-12-09 09:58:09,790;zeus-log;DEBUG;found 'http://www.pehjota.net/~pj/rsyncd.conf'
2017-12-09 09:58:09,791;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:bIvzMwmPYsoJ:http://www.pehjota.net/~pj/rsyncd.conf%2Bext:conf+inurl:rsyncd.conf+-cvs+-man&hl=en&gbv=2&ct=clnk'
2017-12-09 09:58:09,791;zeus-log;DEBUG;found 'https://dev.openwrt.org/browser/packages/net/rsync/files/rsyncd.conf?rev=26630'
2017-12-09 09:58:09,791;zeus-log;DEBUG;found 'https://dev.openwrt.org/browser/packages/net/rsync/.../<b'
2017-12-09 09:58:09,792;zeus-log;DEBUG;found 'http://webcache.googleusercontent.com/search?q=cache:omCrU5s9qxEJ:https://dev.openwrt.org/browser/packages/net/rsync/files/rsyncd.conf?rev%3D26630%2Bext:conf+inurl:rsyncd.conf+-cvs+-man&hl=en&gbv=2&ct=clnk'
2017-12-09 09:58:09,797;zeus-log;DEBUG;found 'https://dev.openwrt.org/browser/packages/net/rsync/files/rsyncd.conf?rev=26630'
2017-12-09 09:58:09,798;zeus-log;INFO;found a webcache URL, extracting
2017-12-09 09:58:09,798;zeus-log;DEBUG;found 'None'
2017-12-09 09:58:09,798;zeus-log;INFO;found a webcache URL, extracting
2017-12-09 09:58:09,798;zeus-log;DEBUG;found 'https://build.opensuse.org/package/view_file/network/rsync/rsyncd.conf?expand%3D1%2Bext:conf'
2017-12-09 09:58:09,798;zeus-log;INFO;found a webcache URL, extracting
2017-12-09 09:58:09,799;zeus-log;DEBUG;found 'https://svn.apache.org/repos/asf/spamassassin/trunk/build/automc/etc-rsyncd.conf%2Bext:conf'
2017-12-09 09:58:09,799;zeus-log;INFO;found a webcache URL, extracting
2017-12-09 09:58:09,799;zeus-log;DEBUG;found 'https://www.artila.com/download/9200/Linux/Utility/rsync/rsyncd.conf%2Bext:conf'
2017-12-09 09:58:09,799;zeus-log;INFO;found a webcache URL, extracting
2017-12-09 09:58:09,799;zeus-log;DEBUG;found 'http://www.pehjota.net/~pj/rsyncd.conf%2Bext:conf'
2017-12-09 09:58:09,803;zeus-log;INFO;found a webcache URL, extracting
2017-12-09 09:58:09,805;zeus-log;DEBUG;found 'https://files.directadmin.com/services/all/rsyncd.conf%2Bext:conf'
2017-12-09 09:58:09,805;zeus-log;INFO;found a webcache URL, extracting
2017-12-09 09:58:09,805;zeus-log;DEBUG;found 'https://git.ustclug.org/mirrors/mirrors-system-conf/blob/master/rsyncd.conf%2Bext:conf'
2017-12-09 09:58:09,808;zeus-log;INFO;found a webcache URL, extracting
2017-12-09 09:58:09,808;zeus-log;DEBUG;found 'https://dev.openwrt.org/browser/packages/net/rsync/files/rsyncd.conf?rev%3D26630%2Bext:conf'
2017-12-09 09:58:09,848;zeus-log;ERROR;[7;31;31mran into exception ''NoneType' object has no attribute 'strip''
Traceback (most recent call last):
  File "zeus.py", line 160, in <module>
    show_success=opt.showSuccessRate
  File "/home/baal/bin/python/zeus-scanner/var/search/selenium_search.py", line 401, in parse_search_results
    file_path = write_to_log_file(true_retval, URL_LOG_PATH, URL_FILENAME)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 177, in write_to_log_file
    item = item.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

2017-12-09 09:58:10,541;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-09 09:58:10,547;zeus-log;INFO;[32mgetting authorization[0m
2017-12-09 09:58:10,627;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-09 09:58:10,628;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
This is related to #286
