### ISSUE TITLE
Unhandled exception (IAFjjie)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#291]
Zeus version:
`1.4.8.73a645`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 138, in github_gist_search_main
    links = get_links(page_set, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 66, in get_links
    if not any(s in redirect for s in gist_skip_schema):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 66, in <genexpr>
    if not any(s in redirect for s in gist_skip_schema):
TypeError: argument of type 'NoneType' is not iterable
```

Running details:
`Linux-4.10.0-42-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:general.php?menu= --verbose --batch -g --x-forward --random-agent -M -L 10 --identify-waf --identify-plugins`

Log file info:
```2017-12-10 13:04:12,147;zeus-log;DEBUG;loading script 'generic'
2017-12-10 13:04:12,147;zeus-log;INFO;no WAF/IDS/IPS has been identified on target URL
2017-12-10 13:04:12,147;zeus-log;INFO;attempting to identify plugins
2017-12-10 13:04:12,148;zeus-log;DEBUG;loading script 'aardvark'
2017-12-10 13:04:12,148;zeus-log;DEBUG;loading script '4d'
2017-12-10 13:04:12,149;zeus-log;DEBUG;loading script 'jquery'
2017-12-10 13:04:12,150;zeus-log;DEBUG;loading script 'clipbucket'
2017-12-10 13:04:12,151;zeus-log;DEBUG;loading script 'ihtml'
2017-12-10 13:04:12,152;zeus-log;DEBUG;loading script '360'
2017-12-10 13:04:12,153;zeus-log;DEBUG;loading script '3dcart'
2017-12-10 13:04:12,153;zeus-log;DEBUG;loading script 'b2evolution'
2017-12-10 13:04:12,155;zeus-log;DEBUG;loading script 'bmcremedy'
2017-12-10 13:04:12,156;zeus-log;DEBUG;loading script 'abyss'
2017-12-10 13:04:12,157;zeus-log;DEBUG;loading script '68classified'
2017-12-10 13:04:12,158;zeus-log;DEBUG;loading script 'bomgar'
2017-12-10 13:04:12,159;zeus-log;DEBUG;loading script 'mssqlreportmanager'
2017-12-10 13:04:12,159;zeus-log;DEBUG;loading script 'opengraph'
2017-12-10 13:04:12,160;zeus-log;DEBUG;loading script 'atomfeed'
2017-12-10 13:04:12,161;zeus-log;DEBUG;loading script 'html5'
2017-12-10 13:04:12,162;zeus-log;DEBUG;loading script '3com'
2017-12-10 13:04:12,163;zeus-log;DEBUG;loading script 'moodle'
2017-12-10 13:04:12,164;zeus-log;DEBUG;loading script 'googleapi'
2017-12-10 13:04:12,165;zeus-log;DEBUG;loading script '1024'
2017-12-10 13:04:12,166;zeus-log;DEBUG;loading script 'accellion'
2017-12-10 13:04:12,167;zeus-log;DEBUG;loading script 'rssfeed'
2017-12-10 13:04:12,167;zeus-log;DEBUG;loading script '4images'
2017-12-10 13:04:12,168;zeus-log;DEBUG;loading script 'openxchange'
2017-12-10 13:04:12,169;zeus-log;WARNING;no known plugins identified on target
2017-12-10 13:04:12,169;zeus-log;DEBUG;loading XML data
2017-12-10 13:04:12,171;zeus-log;INFO;attempting to get request headers for 'http://www.tropentag.de/conference/general.php'
2017-12-10 13:04:12,172;zeus-log;DEBUG;fetched {'Content-Length': '3116', 'Keep-Alive': 'timeout=10, max=600', 'Server': 'Apache', 'Connection': 'Keep-Alive', 'Date': 'Sun, 10 Dec 2017 19:04:11 GMT', 'Content-Type': 'text/html'}
2017-12-10 13:04:12,172;zeus-log;INFO;writing found headers to log file
2017-12-10 13:04:12,173;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/header-log/www.tropentag.de-headers.json'
2017-12-10 13:04:12,208;zeus-log;INFO;searching a total of 5 pages of Gists for 'www.tropentag.de'
2017-12-10 13:04:12,208;zeus-log;INFO;fetching all Gists on page #1
2017-12-10 13:04:12,781;zeus-log;INFO;fetching all Gists on page #2
2017-12-10 13:04:13,295;zeus-log;ERROR;[7;31;31mGist search has failed with error 'argument of type 'NoneType' is not iterable'
Traceback (most recent call last):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 138, in github_gist_search_main
    links = get_links(page_set, proxy=proxy, agent=agent)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 66, in get_links
    if not any(s in redirect for s in gist_skip_schema):
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/gist_lookup/__init__.py", line 66, in <genexpr>
    if not any(s in redirect for s in gist_skip_schema):
TypeError: argument of type 'NoneType' is not iterable

2017-12-10 13:04:13,645;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-10 13:04:13,646;zeus-log;INFO;[32mgetting authorization[0m
2017-12-10 13:04:13,681;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-10 13:04:13,681;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/14f2506ef52a2ec9a1a5045fc58ea8a805b4cc81
