### ISSUE TITLE
Unhandled exception (yvcTPaA)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#304]
Zeus version:
`1.4.8.73a645`

Firefox version:
`(56, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/hsm/zeus-scanner/var/search/selenium_search.py", line 264, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/home/hsm/zeus-scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/home/hsm/zeus-scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 93, in start
    (os.path.basename(self.path), self.start_error_message, str(e)))
  File "/usr/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

Running details:
`Linux-4.10.0-42-generic-x86_64-with-Ubuntu-16.04-xenial`

Commands used:
`zeus.py -d inurl:php?id= -s`

Log file info:
```2017-12-12 19:44:43,986;zeus-log;INFO;log file being saved to '/home/hsm/zeus-scanner/log/zeus-log-7.log'
2017-12-12 19:44:43,986;zeus-log;INFO;using default search engine
2017-12-12 19:44:43,988;zeus-log;INFO;starting dork scan with query 'inurl:php?id='
2017-12-12 19:44:43,990;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)
2017-12-12 19:44:43,991;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)
2017-12-12 19:44:43,991;zeus-log;INFO;attempting to gather query URL
2017-12-12 19:44:44,000;zeus-log;INFO;setting up virtual display to hide the browser
2017-12-12 19:44:44,572;zeus-log;INFO;setting the browser
2017-12-12 19:44:44,754;zeus-log;ERROR;[7;31;31mselenium_search.pyc failed to gather the URL from search engine, caught exception ''NoneType' object has no attribute 'rfind'' exception has been logged to current log file
Traceback (most recent call last):
  File "/home/hsm/zeus-scanner/var/search/selenium_search.py", line 264, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/home/hsm/zeus-scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/home/hsm/zeus-scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 93, in start
    (os.path.basename(self.path), self.start_error_message, str(e)))
  File "/usr/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'

2017-12-12 19:45:10,293;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-12 19:45:10,294;zeus-log;INFO;[32mgetting authorization[0m
2017-12-12 19:45:10,322;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-12 19:45:10,324;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
Alright, I'll fix this, but just so you're aware, there's currently a really big test running through zeus, there will be no updates pushed until that test is done.

**Comment by Ekultek** [comment]
This is related to #286
