### ISSUE TITLE
Unhandled exception (uXGBOLu)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#308]
Zeus version:
`1.4.8.73a645`

Firefox version:
`(52, 5)`

Geckodriver version:
`geckodriver-v0.17.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "./zeus.py", line 412, in <module>
    with io.open(opt.dorkFileToUse, encoding="utf-8") as dorks:
IOError: [Errno 2] No such file or directory: 'd0rks.txt'
2017-12-05 21:12:14,914;zeus-log;CRITICAL;[7;31;31mprovided file does not exist, make sure you have the full path...
2017-12-05 21:12:48,106;zeus-log;INFO;log file being saved to '/root/zeus-scanner/log/zeus-log-21.log'...
2017-12-05 21:12:48,106;zeus-log;WARNING;AOL will take a little longer due to pop-ups...
2017-12-05 21:12:48,106;zeus-log;INFO;specified to use non-default search engine...
2017-12-05 21:12:48,106;zeus-log;ERROR;[Errno 2] No such file or directory: 'd0rk.txt'
Traceback (most recent call last):
  File "./zeus.py", line 412, in <module>
    with io.open(opt.dorkFileToUse, encoding="utf-8") as dorks:
IOError: [Errno 2] No such file or directory: 'd0rk.txt'
2017-12-05 21:12:48,106;zeus-log;CRITICAL;[7;31;31mprovided file does not exist, make sure you have the full path...
2017-12-05 21:13:24,224;zeus-log;INFO;log file being saved to '/root/zeus-scanner/log/zeus-log-21.log'...
2017-12-05 21:13:24,224;zeus-log;WARNING;AOL will take a little longer due to pop-ups...
2017-12-05 21:13:24,224;zeus-log;INFO;specified to use non-default search engine...
2017-12-05 21:13:24,224;zeus-log;ERROR;[Errno 2] No such file or directory: '/root/zeus-scanner/d0rk.txt'
Traceback (most recent call last):
  File "./zeus.py", line 412, in <module>
    with io.open(opt.dorkFileToUse, encoding="utf-8") as dorks:
IOError: [Errno 2] No such file or directory: '/root/zeus-scanner/d0rk.txt'
2017-12-05 21:13:24,225;zeus-log;CRITICAL;[7;31;31mprovided file does not exist, make sure you have the full path...
2017-12-05 21:14:04,290;zeus-log;INFO;log file being saved to '/root/zeus-scanner/log/zeus-log-21.log'...
2017-12-05 21:14:04,290;zeus-log;WARNING;AOL will take a little longer due to pop-ups...
2017-12-05 21:14:04,290;zeus-log;INFO;specified to use non-default search engine...
2017-12-05 21:14:04,291;zeus-log;INFO;starting dork scan with query '-inurl:".ph/" -inurl:".php?cid="'...
2017-12-05 21:14:04,291;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-12-05 21:14:04,291;zeus-log;INFO;attempting to gather query URL...
2017-12-05 21:14:04,291;zeus-log;INFO;setting up virtual display to hide the browser...
2017-12-05 21:14:04,420;zeus-log;INFO;setting the browser...
2017-12-05 21:14:07,805;zeus-log;INFO;browser will open shortly...
2017-12-05 21:14:22,510;zeus-log;INFO;searching search engine using query 'http://aol.com'...
2017-12-05 21:14:26,165;zeus-log;INFO;closing the browser and continuing process..
2017-12-05 22:01:11,908;zeus-log;CRITICAL;[7;31;31muser aborted process...
2017-12-05 22:01:55,926;zeus-log;INFO;log file being saved to '/root/zeus-scanner/log/zeus-log-20.log'...
2017-12-05 22:01:55,926;zeus-log;WARNING;AOL will take a little longer due to pop-ups...
2017-12-05 22:01:55,926;zeus-log;INFO;specified to use non-default search engine...
2017-12-05 22:01:55,926;zeus-log;INFO;starting dork scan with query '-inurl:".ph/" -inurl:".php?cid="'...
2017-12-05 22:01:55,927;zeus-log;INFO;attempting to gather query URL...
2017-12-05 22:01:55,927;zeus-log;INFO;setting up virtual display to hide the browser...
2017-12-05 22:01:56,046;zeus-log;INFO;setting the browser...
2017-12-05 22:01:58,921;zeus-log;INFO;browser will open shortly...
2017-12-05 22:02:12,490;zeus-log;INFO;searching search engine using query 'http://aol.com'...
2017-12-05 22:02:15,992;zeus-log;INFO;closing the browser and continuing process..
2017-12-06 00:39:28,602;zeus-log;CRITICAL;[7;31;31muser aborted process...
2017-12-06 00:39:57,126;zeus-log;INFO;log file being saved to '/root/zeus-scanner/log/zeus-log-20.log'...
2017-12-06 00:39:57,126;zeus-log;INFO;using default search engine...
2017-12-06 00:39:57,126;zeus-log;INFO;starting dork scan with query '-inurl:".ph/" -inurl:".php?cid="'...
2017-12-06 00:39:57,126;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-12-06 00:39:57,126;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-12-06 00:39:57,126;zeus-log;INFO;attempting to gather query URL...
2017-12-06 00:39:57,127;zeus-log;INFO;setting up virtual display to hide the browser...
2017-12-06 00:39:57,241;zeus-log;INFO;setting the browser...
2017-12-06 00:40:00,117;zeus-log;INFO;browser will open shortly...
2017-12-06 00:40:00,575;zeus-log;INFO;searching search engine using query 'http://google.com'...
2017-12-06 00:40:03,735;zeus-log;INFO;closing the browser and continuing process..
2017-12-06 00:40:03,770;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-12-06 00:40:03,770;zeus-log;INFO;no proxy configuration detected...
2017-12-06 00:40:04,287;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner/1.3.18.bd5587 (Language=Python/2.7.14; Platform=Linux)'...
2017-12-06 00:40:04,289;zeus-log;CRITICAL;[7;31;31mdid not find any URLs with given query '-inurl:".ph/" -inurl:".php?cid="' writing query to blacklist...
2017-12-06 00:40:04,289;zeus-log;INFO;successfully wrote found items to '/root/zeus-scanner/log/blacklist/.blacklist'...
2017-12-10 03:24:30,114;zeus-log;INFO;log file being saved to '/root/zeus-scanner/log/zeus-log-20.log'...
2017-12-10 03:24:30,115;zeus-log;INFO;using default search engine...
2017-12-10 03:24:30,116;zeus-log;INFO;using random dork 'inurl:info.php?seccion=' as the search query...
2017-12-10 03:24:30,117;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)...
2017-12-10 03:24:30,117;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)...
2017-12-10 03:24:30,117;zeus-log;INFO;attempting to gather query URL...
2017-12-10 03:24:30,118;zeus-log;INFO;setting up virtual display to hide the browser...
2017-12-10 03:24:30,240;zeus-log;INFO;setting the browser...
2017-12-10 03:24:33,246;zeus-log;INFO;browser will open shortly...
2017-12-10 03:24:33,550;zeus-log;INFO;searching search engine using query 'http://google.com'...
2017-12-10 03:24:36,696;zeus-log;INFO;closing the browser and continuing process..
2017-12-10 03:24:36,726;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-12-10 03:24:36,726;zeus-log;INFO;no proxy configuration detected...
2017-12-10 03:24:36,972;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner/1.3.18.bd5587 (Language=Python/2.7.14; Platform=Linux)'...
2017-12-10 03:24:36,988;zeus-log;INFO;successfully wrote found items to '/root/zeus-scanner/log/url-log/url-log-32.log'...
2017-12-10 03:24:36,989;zeus-log;INFO;found a total of 14 URLs with given query 'inurl:info.php?seccion='...
2017-12-10 03:24:36,990;zeus-log;WARNING;ran into unexpected webcache URL skipping...
2017-12-10 03:24:36,990;zeus-log;WARNING;ran into unexpected webcache URL skipping...
2017-12-10 03:24:36,991;zeus-log;INFO;currently running on 'http://php.net/manual/fr/function.mysql-get-server-info.php' (target #3)...
2017-12-10 03:24:36,991;zeus-log;INFO;checking for HTTP headers...
2017-12-10 03:24:36,992;zeus-log;INFO;checking if target URL is protected by some kind of WAF/IPS/IDS...
2017-12-10 03:24:37,693;zeus-log;INFO;no WAF/IDS/IPS has been identified on target URL...
2017-12-10 03:24:37,695;zeus-log;INFO;attempting to get request headers for 'http://php.net/manual/fr/function.mysql-get-server-info.php'...
2017-12-10 03:24:38,166;zeus-log;INFO;found a request cookie, saving to file...
2017-12-10 03:24:38,167;zeus-log;INFO;successfully wrote found items to '/root/zeus-scanner/log/cookies/php.net-cookie.log'...
2017-12-10 03:24:38,167;zeus-log;WARNING;provided target has protection against clickjacking vulnerabilities...
2017-12-10 03:24:38,167;zeus-log;INFO;writing found headers to log file...
2017-12-10 03:24:38,167;zeus-log;INFO;successfully wrote found items to '/root/zeus-scanner/log/header-log/php.net-headers.json'...
2017-12-10 03:24:38,167;zeus-log;ERROR;it appears that you have enabled multiple attack types, as of now only 1 attack is supported at a time, choose your attack and try again. You can use the -f flag if you do not want to complete an entire search again (IE -f /home/me/zeus-scanner/log/url-log/url-log-1.log)...
2017-12-10 03:25:12,095;zeus-log;INFO;log file being saved to '/root/zeus-scanner/log/header-log'...
2017-12-10 03:25:12,095;zeus-log;INFO;using default search engine...
2017-12-10 03:25:12,095;zeus-log;INFO;starting blackwidow on 'http://107.170.150.37:80/phpmyadmin'...
2017-12-10 03:25:12,541;zeus-log;CRITICAL;[7;31;31mconnection test failed with status code: 403, reason: 'Forbidden'. test connection needs to pass, try a different link...
2017-12-10 03:25:42,402;zeus-log;INFO;log file being saved to '/root/zeus-scanner/log/zeus-log-20.log'...
2017-12-10 03:25:42,402;zeus-log;INFO;using default search engine...
2017-12-13 23:04:58,505;zeus-log;INFO;update in progress...
2017-12-13 23:05:21,430;zeus-log;INFO;log file being saved to '/root/zeus-scanner/log/zeus-log-20.log'
2017-12-13 23:05:21,431;zeus-log;INFO;using default search engine
2017-12-13 23:05:21,431;zeus-log;CRITICAL;[7;31;31mfailed to provide a mandatory argument, you will be redirected to the help menu
Traceback (most recent call last):
  File "./zeus.py", line 243, in <module>
    with io.open(opt.dorkFileToUse, encoding="utf-8") as dorks:
IOError: [Errno 2] No such file or directory: '=sites.txt'
2017-12-13 23:09:03,583;zeus-log;CRITICAL;[7;31;31mprovided file does not exist, make sure you have the full path
Traceback (most recent call last):
  File "./zeus.py", line 243, in <module>
    with io.open(opt.dorkFileToUse, encoding="utf-8") as dorks:
IOError: [Errno 2] No such file or directory: '=/root/zeus-scanner/sites.txt'
2017-12-13 23:11:04,893;zeus-log;CRITICAL;[7;31;31mprovided file does not exist, make sure you have the full path
Traceback (most recent call last):
  File "./zeus.py", line 253, in <module>
    tor=opt.useTor, batch=opt.runInBatch
  File "/root/zeus-scanner/var/search/selenium_search.py", line 213, in parse_search_results
    if not parse_webcache and "google" in url_to_search:
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "./zeus.py", line 253, in <module>
    tor=opt.useTor, batch=opt.runInBatch
  File "/root/zeus-scanner/var/search/selenium_search.py", line 213, in parse_search_results
    if not parse_webcache and "google" in url_to_search:
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "./zeus.py", line 253, in <module>
    tor=opt.useTor, batch=opt.runInBatch
  File "/root/zeus-scanner/var/search/selenium_search.py", line 213, in parse_search_results
    if not parse_webcache and "google" in url_to_search:
TypeError: argument of type 'NoneType' is not iterable
```

Running details:
`Linux-4.4.0-103-generic-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`./zeus.py --dork-list=/root/zeus-scanner/sites.txt --url-file=/root/zeus-scanner/site.txt -s -x -w -a --random-agent`

Log file info:
```Traceback (most recent call last):
  File "./zeus.py", line 243, in <module>
    with io.open(opt.dorkFileToUse, encoding="utf-8") as dorks:
IOError: [Errno 2] No such file or directory: '=/root/zeus-scanner/sites.txt'
2017-12-13 23:11:04,893;zeus-log;CRITICAL;[7;31;31mprovided file does not exist, make sure you have the full path

2017-12-13 23:12:20,451;zeus-log;INFO;log file being saved to '/root/zeus-scanner/log/zeus-log-20.log'
2017-12-13 23:12:20,451;zeus-log;INFO;random agent being used 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X; zh-tw) AppleWebKit/525.13 (KHTML, like Gecko) Version/3.1 Safari/525.13.3'
2017-12-13 23:12:20,451;zeus-log;INFO;running enumeration on given file '/root/zeus-scanner/site.txt'
2017-12-13 23:12:20,451;zeus-log;INFO;starting dork scan with query 'site:.ca inurl:cart.php?id='
2017-12-13 23:12:20,452;zeus-log;ERROR;[7;31;31mran into exception 'argument of type 'NoneType' is not iterable'
Traceback (most recent call last):
  File "./zeus.py", line 253, in <module>
    tor=opt.useTor, batch=opt.runInBatch
  File "/root/zeus-scanner/var/search/selenium_search.py", line 213, in parse_search_results
    if not parse_webcache and "google" in url_to_search:
TypeError: argument of type 'NoneType' is not iterable

2017-12-13 23:12:43,393;zeus-log;INFO;Zeus got an unexpected error and will automatically create an issue for this error, please wait
2017-12-13 23:12:43,393;zeus-log;INFO;getting authorization
2017-12-13 23:12:43,393;zeus-log;INFO;extracting traceback from log file
2017-12-13 23:12:43,394;zeus-log;INFO;attempting to get firefox browser version
2017-12-13 23:12:46,719;zeus-log;INFO;issue has been created successfully with the following name 'Unhandled exception (ErpqQAV)', your unique identifier for this issue is 'ErpqQAV' and the URL to your issue is 'https://github.com/Ekultek/Zeus-Scanner/issues/306'
2017-12-13 23:12:46,719;zeus-log;INFO;starting dork scan with query 'site:.ca inurl:product.php?id='
2017-12-13 23:12:46,719;zeus-log;ERROR;[7;31;31mran into exception 'argument of type 'NoneType' is not iterable'
Traceback (most recent call last):
  File "./zeus.py", line 253, in <module>
    tor=opt.useTor, batch=opt.runInBatch
  File "/root/zeus-scanner/var/search/selenium_search.py", line 213, in parse_search_results
    if not parse_webcache and "google" in url_to_search:
TypeError: argument of type 'NoneType' is not iterable

2017-12-13 23:12:48,805;zeus-log;INFO;Zeus got an unexpected error and will automatically create an issue for this error, please wait
2017-12-13 23:12:48,806;zeus-log;INFO;getting authorization
2017-12-13 23:12:48,806;zeus-log;INFO;extracting traceback from log file
2017-12-13 23:12:48,806;zeus-log;INFO;attempting to get firefox browser version
2017-12-13 23:12:51,791;zeus-log;INFO;issue has been created successfully with the following name 'Unhandled exception (VKqqROM)', your unique identifier for this issue is 'VKqqROM' and the URL to your issue is 'https://github.com/Ekultek/Zeus-Scanner/issues/307'
2017-12-13 23:12:51,792;zeus-log;INFO;starting dork scan with query 'site:.ca inurl:list.php?Prodid='
2017-12-13 23:12:51,792;zeus-log;ERROR;[7;31;31mran into exception 'argument of type 'NoneType' is not iterable'
Traceback (most recent call last):
  File "./zeus.py", line 253, in <module>
    tor=opt.useTor, batch=opt.runInBatch
  File "/root/zeus-scanner/var/search/selenium_search.py", line 213, in parse_search_results
    if not parse_webcache and "google" in url_to_search:
TypeError: argument of type 'NoneType' is not iterable

2017-12-13 23:12:53,031;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-13 23:12:53,031;zeus-log;INFO;[32mgetting authorization[0m
2017-12-13 23:12:53,031;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-13 23:12:53,031;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
dupe of #306
