### ISSUE TITLE
Unhandled exception (kPevlTr)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#309]
Zeus version:
`1.4.8.73a645`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 189, in <module>
    __run_attacks_main()
  File "zeus.py", line 140, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1007, in run_attacks
    verbose=verbose, do_threading=do_threading, batch=batch
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 216, in main
    results = check_for_externals(url, robots=True, batch=batch)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 44, in check_for_externals
    _, code, data, _ = lib.core.common.get_page(full_url)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 442, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/baal/.local/lib/python2.7/site-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/models.py", line 382, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
InvalidURL: Invalid URL u'http:///robots.txt': No host supplied
```

Running details:
`Linux-4.10.0-42-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d inurl:nota.php?filepath= --verbose --batch -a --x-forward --random-agent -W -E --identify-waf --identify-plugins`

Log file info:
```2017-12-14 00:45:28,644;zeus-log;WARNING;connection timed out assuming won't connect and skipping
2017-12-14 00:45:28,645;zeus-log;INFO;found 0 possible connections(s) and 0 successful connection(s)
2017-12-14 00:45:28,645;zeus-log;CRITICAL;[7;31;31mdid not receive any successful connections to the admin page of http://appmonster.net/nds4ios/nota.php?filepath%3D%2Binurl:nota.php?filepath%3D&hl=en&gbv=2&ct=clnk
2017-12-14 00:45:28,645;zeus-log;INFO;currently running on 'http://' (target #9)
2017-12-14 00:45:28,646;zeus-log;INFO;fetching target meta-data
2017-12-14 00:45:28,646;zeus-log;INFO;random IP address generated for header '84.100.146.226'
2017-12-14 00:45:28,646;zeus-log;INFO;random IP address generated for header '255.109.240.28'
2017-12-14 00:45:28,646;zeus-log;INFO;random IP address generated for header '81.38.128.241'
2017-12-14 00:45:38,652;zeus-log;WARNING;target actively refused the connection, sleeping for 5s and retrying the request
2017-12-14 00:45:43,654;zeus-log;INFO;random IP address generated for header '229.129.78.200'
2017-12-14 00:45:43,655;zeus-log;INFO;random IP address generated for header '48.250.124.103'
2017-12-14 00:45:43,656;zeus-log;INFO;random IP address generated for header '228.243.149.137'
2017-12-14 00:45:53,667;zeus-log;WARNING;target actively refused the connection, sleeping for 5s and retrying the request
2017-12-14 00:45:58,671;zeus-log;INFO;random IP address generated for header '182.204.12.147'
2017-12-14 00:45:58,671;zeus-log;INFO;random IP address generated for header '95.128.99.51'
2017-12-14 00:45:58,671;zeus-log;INFO;random IP address generated for header '165.103.38.105'
2017-12-14 00:46:08,682;zeus-log;ERROR;target is refusing to allow meta-data dumping, skipping
2017-12-14 00:46:08,683;zeus-log;INFO;parsing robots.txt
2017-12-14 00:46:08,685;zeus-log;ERROR;[7;31;31mURL provided is not valid, schema appears to be missing
Traceback (most recent call last):
  File "zeus.py", line 189, in <module>
    __run_attacks_main()
  File "zeus.py", line 140, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/home/baal/bin/python/zeus-scanner/lib/core/settings.py", line 1007, in run_attacks
    verbose=verbose, do_threading=do_threading, batch=batch
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 216, in main
    results = check_for_externals(url, robots=True, batch=batch)
  File "/home/baal/bin/python/zeus-scanner/lib/attacks/admin_panel_finder/__init__.py", line 44, in check_for_externals
    _, code, data, _ = lib.core.common.get_page(full_url)
  File "/home/baal/bin/python/zeus-scanner/lib/core/common.py", line 442, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/baal/.local/lib/python2.7/site-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/home/baal/.local/lib/python2.7/site-packages/requests/models.py", line 382, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
InvalidURL: Invalid URL u'http:///robots.txt': No host supplied

2017-12-14 00:46:09,284;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-14 00:46:09,284;zeus-log;INFO;[32mgetting authorization[0m
2017-12-14 00:46:09,538;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-14 00:46:09,541;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
Dupe #286
