### ISSUE TITLE
Unhandled exception (Tyqwbds)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#313]
Zeus version:
`1.4.11.b0ea07`

Firefox version:
`(52, 5)`

Geckodriver version:
`geckodriver-v0.17.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "./zeus.py", line 330, in <module>
    __run_attacks_main()
  File "./zeus.py", line 141, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/opt/Zeus-Scanner/Zeus-Scanner/lib/core/settings.py", line 1007, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/opt/Zeus-Scanner/Zeus-Scanner/lib/attacks/xss_scan/__init__.py", line 194, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/opt/Zeus-Scanner/Zeus-Scanner/lib/attacks/xss_scan/__init__.py", line 122, in scan_xss
    _, status, html_data, _ = lib.core.common.get_page(url, agent=agent, proxy=proxy)
  File "/opt/Zeus-Scanner/Zeus-Scanner/lib/core/common.py", line 335, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 360, in prepare_url
    raise InvalidURL(*e.args)
InvalidURL: Failed to parse: community.successfactors.comjavascript:alert("hellox worldss")
```

Running details:
`Linux-4.14.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`./zeus.py -b https://www.successfactors.com/ -x --batch`

Log file info:
```2017-12-19 14:27:04,378;zeus-log;INFO;found a request cookie, saving to file
2017-12-19 14:27:04,379;zeus-log;INFO;successfully wrote found items to '/opt/Zeus-Scanner/Zeus-Scanner/log/cookies/event.on24.com-cookie.log'
2017-12-19 14:27:04,379;zeus-log;INFO;writing found headers to log file
2017-12-19 14:27:04,379;zeus-log;INFO;successfully wrote found items to '/opt/Zeus-Scanner/Zeus-Scanner/log/header-log/event.on24.com-headers.json'
2017-12-19 14:27:04,379;zeus-log;INFO;loading payloads
2017-12-19 14:27:04,379;zeus-log;INFO;payloads will be written to a temporary file and read from there
2017-12-19 14:27:04,380;zeus-log;INFO;loaded URL's have been saved to '/tmp/tmpLgkWeX'
2017-12-19 14:27:04,380;zeus-log;INFO;testing for XSS vulnerabilities on host 'https://event.on24.com/eventRegistration/EventLobbyServlet?target=reg20.jsp&partnerref=SFBanner&referrer=&eventid=1360268&sessionid=1&key=8FCF0F43BB161807F748B88A3819CF96&regTag=83216&sourcepage=register'
2017-12-19 14:33:12,523;zeus-log;ERROR;host 'https://event.on24.com/eventRegistration/EventLobbyServlet?target=reg20.jsp&partnerref=SFBanner&referrer=&eventid=1360268&sessionid=1&key=8FCF0F43BB161807F748B88A3819CF96&regTag=83216&sourcepage=register' does not appear to be vulnerable to XSS attacks
2017-12-19 14:33:12,523;zeus-log;INFO;currently running on 'http://community.successfactors.com' (target #13)
2017-12-19 14:33:12,524;zeus-log;INFO;fetching target meta-data
2017-12-19 14:33:12,717;zeus-log;WARNING;target actively refused the connection, sleeping for 5s and retrying the request
2017-12-19 14:33:17,770;zeus-log;WARNING;target actively refused the connection, sleeping for 5s and retrying the request
2017-12-19 14:33:22,822;zeus-log;ERROR;target is refusing to allow meta-data dumping, skipping
2017-12-19 14:33:22,823;zeus-log;INFO;loading payloads
2017-12-19 14:33:22,823;zeus-log;INFO;payloads will be written to a temporary file and read from there
2017-12-19 14:33:22,824;zeus-log;INFO;loaded URL's have been saved to '/tmp/tmpYftNFn'
2017-12-19 14:33:22,824;zeus-log;INFO;testing for XSS vulnerabilities on host 'http://community.successfactors.com'
2017-12-19 14:33:27,202;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code 'Failed to parse: community.successfactors.comjavascript:alert("hellox worldss")'
Traceback (most recent call last):
  File "./zeus.py", line 330, in <module>
    __run_attacks_main()
  File "./zeus.py", line 141, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/opt/Zeus-Scanner/Zeus-Scanner/lib/core/settings.py", line 1007, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/opt/Zeus-Scanner/Zeus-Scanner/lib/attacks/xss_scan/__init__.py", line 194, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/opt/Zeus-Scanner/Zeus-Scanner/lib/attacks/xss_scan/__init__.py", line 122, in scan_xss
    _, status, html_data, _ = lib.core.common.get_page(url, agent=agent, proxy=proxy)
  File "/opt/Zeus-Scanner/Zeus-Scanner/lib/core/common.py", line 335, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 360, in prepare_url
    raise InvalidURL(*e.args)
InvalidURL: Failed to parse: community.successfactors.comjavascript:alert("hellox worldss")

2017-12-19 15:43:04,493;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-19 15:43:04,493;zeus-log;INFO;[32mgetting authorization[0m
2017-12-19 15:43:04,510;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-19 15:43:04,511;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
Did it process the correct URL?

**Comment by Ekultek** [comment]
dupe of #314
