### ISSUE TITLE
Unhandled exception (leEKqWg)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#314]
Zeus version:
`1.4.11.b0ea07`

Firefox version:
`(52, 5)`

Geckodriver version:
`geckodriver-v0.17.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "./zeus.py", line 330, in <module>
    __run_attacks_main()
  File "./zeus.py", line 141, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/opt/Zeus-Scanner/Zeus-Scanner/lib/core/settings.py", line 1007, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/opt/Zeus-Scanner/Zeus-Scanner/lib/attacks/xss_scan/__init__.py", line 194, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/opt/Zeus-Scanner/Zeus-Scanner/lib/attacks/xss_scan/__init__.py", line 122, in scan_xss
    _, status, html_data, _ = lib.core.common.get_page(url, agent=agent, proxy=proxy)
  File "/opt/Zeus-Scanner/Zeus-Scanner/lib/core/common.py", line 335, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 360, in prepare_url
    raise InvalidURL(*e.args)
InvalidURL: Failed to parse: www.skyadvertising.nzjavascript:alert("hellox worldss")
```

Running details:
`Linux-4.14.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`./zeus.py -b https://www.sky.co.nz/ -x --batch`

Log file info:
```2017-12-19 15:49:24,443;zeus-log;INFO;log file being saved to '/opt/Zeus-Scanner/Zeus-Scanner/log/zeus-log-25.log'
2017-12-19 15:49:24,443;zeus-log;INFO;using default search engine
2017-12-19 15:49:24,443;zeus-log;INFO;starting blackwidow on 'https://www.sky.co.nz/'
2017-12-19 15:49:27,280;zeus-log;INFO;connection test succeeded, continuing
2017-12-19 15:49:27,280;zeus-log;INFO;crawling given URL 'https://www.sky.co.nz/' for links
2017-12-19 15:49:29,678;zeus-log;INFO;found a total of 104 links from given URL 'https://www.sky.co.nz/'
2017-12-19 15:49:29,691;zeus-log;INFO;successfully wrote found items to '/opt/Zeus-Scanner/Zeus-Scanner/log/blackwidow-log/blackwidow-log-16.log'
2017-12-19 15:49:29,691;zeus-log;INFO;currently running on 'http://www.skyadvertising.nz' (target #1)
2017-12-19 15:49:29,691;zeus-log;INFO;fetching target meta-data
2017-12-19 15:49:29,873;zeus-log;WARNING;target actively refused the connection, sleeping for 5s and retrying the request
2017-12-19 15:49:34,926;zeus-log;WARNING;target actively refused the connection, sleeping for 5s and retrying the request
2017-12-19 15:49:39,977;zeus-log;ERROR;target is refusing to allow meta-data dumping, skipping
2017-12-19 15:49:39,994;zeus-log;INFO;loading payloads
2017-12-19 15:49:39,997;zeus-log;INFO;payloads will be written to a temporary file and read from there
2017-12-19 15:49:39,999;zeus-log;INFO;loaded URL's have been saved to '/tmp/tmp96t_h8'
2017-12-19 15:49:39,999;zeus-log;INFO;testing for XSS vulnerabilities on host 'http://www.skyadvertising.nz'
2017-12-19 15:49:44,094;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code 'Failed to parse: www.skyadvertising.nzjavascript:alert("hellox worldss")'
Traceback (most recent call last):
  File "./zeus.py", line 330, in <module>
    __run_attacks_main()
  File "./zeus.py", line 141, in __run_attacks_main
    threads=opt.amountOfThreads
  File "/opt/Zeus-Scanner/Zeus-Scanner/lib/core/settings.py", line 1007, in run_attacks
    agent=agent, tamper=tamper_script, batch=batch,
  File "/opt/Zeus-Scanner/Zeus-Scanner/lib/attacks/xss_scan/__init__.py", line 194, in main_xss
    result = scan_xss(url, proxy=proxy, agent=agent)
  File "/opt/Zeus-Scanner/Zeus-Scanner/lib/attacks/xss_scan/__init__.py", line 122, in scan_xss
    _, status, html_data, _ = lib.core.common.get_page(url, agent=agent, proxy=proxy)
  File "/opt/Zeus-Scanner/Zeus-Scanner/lib/core/common.py", line 335, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 360, in prepare_url
    raise InvalidURL(*e.args)
InvalidURL: Failed to parse: www.skyadvertising.nzjavascript:alert("hellox worldss")

2017-12-19 15:49:48,095;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-19 15:49:48,095;zeus-log;INFO;[32mgetting authorization[0m
2017-12-19 15:49:48,095;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-19 15:49:48,095;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
Hmm, that’s not suppose to happen...

**Comment by Ekultek** [comment]
I have a question, having this fixed, would you like to keep the https:// or would processing http:// be sufficient for you?

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/Zeus-Scanner/commit/cadc40b81a083c5ee9a06e95e88e73a7b8e299dd
