### ISSUE TITLE
Unhandled exception (lkflEUy)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#315]
Zeus version:
`1.4.13.e5ac63`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/darkshadow/Desktop/Zeus-Scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/home/darkshadow/Desktop/Zeus-Scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/home/darkshadow/Desktop/Zeus-Scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: address not available
```

Running details:
`Linux-4.14.0-parrot2-amd64-x86_64-with-Parrot-3.10-intruder`

Commands used:
`zeus.py -d index.php?id= -s -l /root/Desktop/sqli.txt`

Log file info:
```2017-12-20 01:24:31,877;zeus-log;INFO;log file being saved to '/home/darkshadow/Desktop/Zeus-Scanner/log/zeus-log-5.log'
2017-12-20 01:24:31,878;zeus-log;INFO;using default search engine
2017-12-20 01:24:31,878;zeus-log;INFO;starting dork scan with query 'index.php?id='
2017-12-20 01:24:31,879;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)
2017-12-20 01:24:31,879;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)
2017-12-20 01:24:31,879;zeus-log;INFO;attempting to gather query URL
2017-12-20 01:24:31,879;zeus-log;INFO;setting up virtual display to hide the browser
2017-12-20 01:24:32,012;zeus-log;INFO;setting the browser
2017-12-20 01:26:39,382;zeus-log;ERROR;[7;31;31mselenium_search.pyc failed to gather the URL from search engine, caught exception 'Message: address not available' exception has been logged to current log file
Traceback (most recent call last):
  File "/home/darkshadow/Desktop/Zeus-Scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/home/darkshadow/Desktop/Zeus-Scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/home/darkshadow/Desktop/Zeus-Scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: address not available


2017-12-20 01:27:06,425;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-20 01:27:06,425;zeus-log;INFO;[32mgetting authorization[0m
2017-12-20 01:27:06,426;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-20 01:27:06,426;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
I have no idea what is causing this

**Comment by Ekultek** [comment]
No reply and can’t reproduce closing
