### ISSUE TITLE
Unhandled exception (UqbmuwP)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#318]
Zeus version:
`1.4.13.e5ac63`

Firefox version:
`(52, 5)`

Geckodriver version:
`geckodriver-v0.17.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/attack/Zeus-Scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/attack/Zeus-Scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/attack/Zeus-Scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 93, in start
    (os.path.basename(self.path), self.start_error_message, str(e)))
  File "/usr/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

Running details:
`Linux-4.14.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`zeus.py -d inurl:asp?id=10 -W -E --verbose`

Log file info:
```2017-12-23 18:52:16,271;zeus-log;DEBUG;checking if the application has been run before
2017-12-23 18:52:16,271;zeus-log;DEBUG;verifying operating system
2017-12-23 18:52:16,272;zeus-log;DEBUG;already ran, skipping
2017-12-23 18:52:16,274;zeus-log;DEBUG;running with options '{'noExclude': True, 'runInVerbose': True, 'parseWebcache': True, 'dorkToUse': 'inurl:asp?id=10'}'
2017-12-23 18:52:16,275;zeus-log;INFO;log file being saved to '/attack/Zeus-Scanner/log/zeus-log-19.log'
2017-12-23 18:52:16,275;zeus-log;DEBUG;using default search engine (Google)
2017-12-23 18:52:16,275;zeus-log;INFO;using default search engine
2017-12-23 18:52:16,275;zeus-log;INFO;starting dork scan with query 'inurl:asp?id=10'
2017-12-23 18:52:16,275;zeus-log;DEBUG;parsing blacklist
2017-12-23 18:52:16,276;zeus-log;DEBUG;checking for user-agent and proxy configuration
2017-12-23 18:52:16,276;zeus-log;INFO;attempting to gather query URL
2017-12-23 18:52:16,276;zeus-log;INFO;setting up virtual display to hide the browser
2017-12-23 18:52:16,533;zeus-log;INFO;setting the browser
2017-12-23 18:52:16,833;zeus-log;ERROR;[7;31;31mselenium_search.pyc failed to gather the URL from search engine, caught exception ''NoneType' object has no attribute 'rfind'' exception has been logged to current log file
Traceback (most recent call last):
  File "/attack/Zeus-Scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/attack/Zeus-Scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/attack/Zeus-Scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 93, in start
    (os.path.basename(self.path), self.start_error_message, str(e)))
  File "/usr/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'

2017-12-23 18:52:19,523;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-23 18:52:19,524;zeus-log;INFO;[32mgetting authorization[0m
2017-12-23 18:52:19,529;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-23 18:52:19,529;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
update firefox and selenium with the`etc/scripts/reinstall.sh` script and you should be good
