### ISSUE TITLE
Unhandled exception (oqHpEhe)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#322]
Zeus version:
`1.4.13.e5ac63`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/hsm/Desktop/test1/Zeus-Scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/home/hsm/Desktop/test1/Zeus-Scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/home/hsm/Desktop/test1/Zeus-Scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 93, in start
    (os.path.basename(self.path), self.start_error_message, str(e)))
  File "/usr/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

Running details:
`Linux-4.10.0-42-generic-x86_64-with-Ubuntu-16.04-xenial`

Commands used:
`zeus.py -l etc/text_files/dorks.txt -D`

Log file info:
```2017-12-28 03:56:16,556;zeus-log;INFO;log file being saved to '/home/hsm/Desktop/test1/Zeus-Scanner/log/zeus-log-65.log'
2017-12-28 03:56:16,557;zeus-log;INFO;specified to use non-default search engine
2017-12-28 03:56:16,566;zeus-log;INFO;starting dork scan with query 'inurl:"topic.asp?ID="'
2017-12-28 03:56:16,578;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)
2017-12-28 03:56:16,578;zeus-log;INFO;attempting to gather query URL
2017-12-28 03:56:16,588;zeus-log;INFO;setting up virtual display to hide the browser
2017-12-28 03:56:17,483;zeus-log;INFO;setting the browser
2017-12-28 03:56:17,650;zeus-log;ERROR;[7;31;31mselenium_search.pyc failed to gather the URL from search engine, caught exception ''NoneType' object has no attribute 'rfind'' exception has been logged to current log file
Traceback (most recent call last):
  File "/home/hsm/Desktop/test1/Zeus-Scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/home/hsm/Desktop/test1/Zeus-Scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/home/hsm/Desktop/test1/Zeus-Scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 93, in start
    (os.path.basename(self.path), self.start_error_message, str(e)))
  File "/usr/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'

2017-12-28 03:57:31,294;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-28 03:57:31,294;zeus-log;INFO;[32mgetting authorization[0m
2017-12-28 03:57:31,317;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-28 03:57:31,318;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
You need to reinstall, go to etc/scripts and run `sudo bash reinstall.sh`
