### ISSUE TITLE
Unhandled exception (CZFBKIF)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#326]
Zeus version:
`1.4.13.e5ac63`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gzgeckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "./zeus.py", line 283, in <module>
    tor=opt.useTor, batch=opt.runInBatch
  File "/home/test/zeus-scanner/var/search/selenium_search.py", line 217, in parse_search_results
    if not parse_webcache and "google" in url_to_search:
TypeError: argument of type 'NoneType' is not iterable
```

Running details:
`Linux-4.13.0-21-generic-x86_64-with-Ubuntu-17.10-artful`

Commands used:
`./zeus.py -f /home/test/zeus-scanner/log/blackwidow-log/blackwidow-log-1.log -r`

Log file info:
```2017-12-30 19:10:56,634;zeus-log;INFO;log file being saved to '/home/test/zeus-scanner/log/zeus-log-11.log'
2017-12-30 19:10:56,635;zeus-log;INFO;running enumeration on given file '/home/test/zeus-scanner/log/blackwidow-log/blackwidow-log-1.log'
2017-12-30 19:10:56,635;zeus-log;INFO;using random dork 'inurl:"shopcart.asp?title="' as the search query
2017-12-30 19:10:56,636;zeus-log;ERROR;[7;31;31mran into exception 'argument of type 'NoneType' is not iterable' and cannot continue, saved to current log file
Traceback (most recent call last):
  File "./zeus.py", line 283, in <module>
    tor=opt.useTor, batch=opt.runInBatch
  File "/home/test/zeus-scanner/var/search/selenium_search.py", line 217, in parse_search_results
    if not parse_webcache and "google" in url_to_search:
TypeError: argument of type 'NoneType' is not iterable

2017-12-30 19:11:18,926;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2017-12-30 19:11:18,926;zeus-log;INFO;[32mgetting authorization[0m
2017-12-30 19:11:18,927;zeus-log;INFO;[32mextracting traceback from log file[0m
2017-12-30 19:11:18,927;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
I was able to get this reproduced. Leave off the `-r` when using the crawler and it should work.

**Comment by Ekultek** [comment]
The crawler log file is meant to be used with an attack, not a search

**Comment by Ekultek** [comment]
So this is on hold because I’m going to have to create a way to verify ALL arguments passed and make sure that they are compatible with one another. Until I figure out a way to do this, that doesn’t look like shit, I’m going to keep this on hold
