### ISSUE TITLE
Unhandled exception (VLAgVzw)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#329]
Zeus version:
`1.4.13.e5ac63`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/root/zeus-scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/root/zeus-scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/root/zeus-scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Process unexpectedly closed with status: {unknown}
```

Running details:
`Linux-2.6.32-042stab125.3-x86_64-with-debian-buster-sid`

Commands used:
`/root/zeus-scanner/zeus.py -d inurl:forums_thread_show_one_posteronleftstyle.php?ticker= -L 100 -W --proxy=socks4://127.0.0.1:16919`

Log file info:
```2018-01-03 07:55:20,692;zeus-log;INFO;log file being saved to '/root/zeus-scanner/log/zeus-log-177.log'
2018-01-03 07:55:20,692;zeus-log;WARNING;timeout will be increased to 40s due to Tor being used
2018-01-03 07:55:20,692;zeus-log;INFO;using default search engine
2018-01-03 07:55:20,692;zeus-log;INFO;starting dork scan with query 'inurl:forums_thread_show_one_posteronleftstyle.php?ticker='
2018-01-03 07:55:20,693;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)
2018-01-03 07:55:20,693;zeus-log;INFO;attempting to gather query URL
2018-01-03 07:55:20,693;zeus-log;INFO;setting up virtual display to hide the browser
2018-01-03 07:55:20,880;zeus-log;INFO;setting the browser
2018-01-03 07:55:35,607;zeus-log;ERROR;[7;31;31mselenium_search.pyc failed to gather the URL from search engine, caught exception 'Message: Process unexpectedly closed with status: {unknown}' exception has been logged to current log file
Traceback (most recent call last):
  File "/root/zeus-scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/root/zeus-scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/root/zeus-scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Process unexpectedly closed with status: {unknown}


2018-01-03 07:55:42,914;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2018-01-03 07:55:42,914;zeus-log;INFO;[32mgetting authorization[0m
2018-01-03 07:55:42,916;zeus-log;INFO;[32mextracting traceback from log file[0m
2018-01-03 07:55:42,916;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
Never seen this one before, could be your proxy same as #327. Could also be that your driver needs to be turned executable.

Try `chmod +x`ing the geckodriver and see if that does anything interesting

**Comment by Ekultek** [comment]
I have not been able to reproduce this, and not reply, closing as unreproducible
