### ISSUE TITLE
Unhandled exception (vAgDKxu)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#330]
Zeus version:
`1.4.13.e5ac63`

Firefox version:
`failed to start`

Geckodriver version:
`geckodriver-v0.19.0-linux32.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/root/Zeus-Scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/root/Zeus-Scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/root/Zeus-Scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Failed to start browser /usr/bin/firefox: permission denied
```

Running details:
`Linux-4.9.0-kali3-686-pae-i686-with-Kali-kali-rolling-kali-rolling`

Commands used:
`zeus.py -d inurl:php?id=`

Log file info:
```2018-01-07 11:22:26,118;zeus-log;INFO;seems this is your first time running the application, doing setup please wait
2018-01-07 11:22:26,131;zeus-log;INFO;attempting to get firefox browser version
2018-01-07 11:22:26,137;zeus-log;ERROR;[7;31;31mfailed to run firefox
2018-01-07 11:22:29,947;zeus-log;INFO;done, continuing process
2018-01-07 11:22:29,947;zeus-log;INFO;log file being saved to '/root/Zeus-Scanner/log/zeus-log-10.log'
2018-01-07 11:22:29,948;zeus-log;INFO;using default search engine
2018-01-07 11:22:29,948;zeus-log;INFO;starting dork scan with query 'inurl:php?id='
2018-01-07 11:22:29,949;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)
2018-01-07 11:22:29,949;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)
2018-01-07 11:22:29,949;zeus-log;INFO;attempting to gather query URL
2018-01-07 11:22:29,949;zeus-log;INFO;setting up virtual display to hide the browser
2018-01-07 11:22:30,101;zeus-log;INFO;setting the browser
2018-01-07 11:22:32,570;zeus-log;ERROR;[7;31;31mselenium_search.pyc failed to gather the URL from search engine, caught exception 'Message: Failed to start browser /usr/bin/firefox: permission denied' exception has been logged to current log file
Traceback (most recent call last):
  File "/root/Zeus-Scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/root/Zeus-Scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/root/Zeus-Scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Failed to start browser /usr/bin/firefox: permission denied


2018-01-07 11:22:40,903;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2018-01-07 11:22:40,903;zeus-log;INFO;[32mgetting authorization[0m
2018-01-07 11:22:40,904;zeus-log;INFO;[32mextracting traceback from log file[0m
2018-01-07 11:22:40,904;zeus-log;INFO;[32mattempting to get firefox browser version[0m
2018-01-07 11:22:40,912;zeus-log;ERROR;[7;31;31mfailed to run firefox[0m
```

**Comment by Ekultek** [comment]
You’re not sudo, use sudo

**Comment by Ekultek** [comment]
Try it with sudo

**Comment by Ekultek** [comment]
No response assuming solved
