### ISSUE TITLE
Unhandled exception (RCUpMxD)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#331]
Zeus version:
`1.4.13.e5ac63`

Firefox version:
`(52, 5)`

Geckodriver version:
`geckodriver-v0.17.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/mrrobot/zeus-scanner/var/blackwidow/__init__.py", line 43, in test_connection
    proxy=self.proxy
  File "/home/mrrobot/zeus-scanner/lib/core/common.py", line 335, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='www.jxzwfww.gov.cn', port=80): Read timed out. (read timeout=20)
```

Running details:
`Linux-4.14.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`./zeus.py -b http://www.jxzwfww.gov.cn/ -B -s`

Log file info:
```2018-01-07 17:08:55,300;zeus-log;INFO;log file being saved to '/home/mrrobot/zeus-scanner/log/zeus-log-14.log'
2018-01-07 17:08:55,300;zeus-log;INFO;specified to use non-default search engine
2018-01-07 17:08:55,300;zeus-log;INFO;starting blackwidow on 'http://www.jxzwfww.gov.cn/'
2018-01-07 17:09:15,766;zeus-log;ERROR;[7;31;31mfailed to connect to 'http://www.jxzwfww.gov.cn/' received error 'HTTPConnectionPool(host='www.jxzwfww.gov.cn', port=80): Read timed out. (read timeout=20)'
Traceback (most recent call last):
  File "/home/mrrobot/zeus-scanner/var/blackwidow/__init__.py", line 43, in test_connection
    proxy=self.proxy
  File "/home/mrrobot/zeus-scanner/lib/core/common.py", line 335, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='www.jxzwfww.gov.cn', port=80): Read timed out. (read timeout=20)

2018-01-07 17:09:41,862;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2018-01-07 17:09:41,862;zeus-log;INFO;[32mgetting authorization[0m
2018-01-07 17:09:41,863;zeus-log;INFO;[32mextracting traceback from log file[0m
2018-01-07 17:09:41,864;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
update firefox to the latest version and it'll work
