### ISSUE TITLE
Unhandled exception (LQKzwUt)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#333]
Zeus version:
`1.4.13.e5ac63`

Firefox version:
`(52, 5)`

Geckodriver version:
`geckodriver-v0.17.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/root/zeus-scanner/var/blackwidow/__init__.py", line 43, in test_connection
    proxy=self.proxy
  File "/root/zeus-scanner/lib/core/common.py", line 335, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
```

Running details:
`Linux-4.13.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`zeus.py -b http://www.byzoro.com`

Log file info:
```2018-01-08 00:22:11,546;zeus-log;INFO;log file being saved to '/root/zeus-scanner/log/zeus-log-20.log'
2018-01-08 00:22:11,546;zeus-log;INFO;using default search engine
2018-01-08 00:22:11,546;zeus-log;INFO;starting blackwidow on 'http://www.byzoro.com'
2018-01-08 00:22:11,650;zeus-log;ERROR;[7;31;31mfailed to connect to 'http://www.byzoro.com' received error '('Connection aborted.', error(104, 'Connection reset by peer'))'
Traceback (most recent call last):
  File "/root/zeus-scanner/var/blackwidow/__init__.py", line 43, in test_connection
    proxy=self.proxy
  File "/root/zeus-scanner/lib/core/common.py", line 335, in get_page
    req = requests.get(url, params=headers, proxies=proxies, verify=False, timeout=20)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

2018-01-08 00:22:13,965;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2018-01-08 00:22:13,965;zeus-log;INFO;[32mgetting authorization[0m
2018-01-08 00:22:13,986;zeus-log;INFO;[32mextracting traceback from log file[0m
2018-01-08 00:22:13,987;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
Fix is the same as #331
