### ISSUE TITLE
Unhandled exception (wCEeWoB)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#334]
Zeus version:
`1.4.13.e5ac63`

Firefox version:
`(52, 5)`

Geckodriver version:
`geckodriver-v0.17.0-linux64.tar.gzgeckodriver-v0.17.0-linux64.tar.gzgeckodriver-v0.17.0-linux64.tar.gzgeckodriver-v0.17.0-linux64.tar.gzgeckodriver-v0.17.0-linux64.tar.gzgeckodriver-v0.17.0-linux64.tar.gzgeckodriver-v0.17.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 328, in <module>
    verbose=opt.runInVerbose, forward=opt.forwardedForRandomIP)
  File "/home/linq/Zeus-Scanner/var/blackwidow/__init__.py", line 158, in blackwidow_main
    filename=lib.core.settings.BLACKWIDOW_FILENAME)
  File "/home/linq/Zeus-Scanner/lib/core/common.py", line 152, in write_to_log_file
    with open(full_file_path, "a+") as log:
IOError: [Errno 13] Permission denied: '/home/linq/Zeus-Scanner/log/blackwidow-log/blackwidow-log-1.log'
```

Running details:
`Linux-4.4.104-39-default-x86_64-with-SuSE-42.3-x86_64`

Commands used:
`zeus.py -b https://www.lazada.com.ph/`

Log file info:
```2018-01-12 11:06:26,005;zeus-log;INFO;log file being saved to '/home/linq/Zeus-Scanner/log/zeus-log-11.log'
2018-01-12 11:06:26,005;zeus-log;INFO;using default search engine
2018-01-12 11:06:26,005;zeus-log;INFO;starting blackwidow on 'https://www.lazada.com.ph/'
2018-01-12 11:06:39,542;zeus-log;INFO;connection test succeeded, continuing
2018-01-12 11:06:39,543;zeus-log;INFO;crawling given URL 'https://www.lazada.com.ph/' for links
2018-01-12 11:06:54,252;zeus-log;INFO;found a total of 1179 links from given URL 'https://www.lazada.com.ph/'
2018-01-12 11:06:54,253;zeus-log;ERROR;[7;31;31mZeus has hit an unexpected error and cannot continue, error code '[Errno 13] Permission denied: '/home/linq/Zeus-Scanner/log/blackwidow-log/blackwidow-log-1.log''
Traceback (most recent call last):
  File "zeus.py", line 328, in <module>
    verbose=opt.runInVerbose, forward=opt.forwardedForRandomIP)
  File "/home/linq/Zeus-Scanner/var/blackwidow/__init__.py", line 158, in blackwidow_main
    filename=lib.core.settings.BLACKWIDOW_FILENAME)
  File "/home/linq/Zeus-Scanner/lib/core/common.py", line 152, in write_to_log_file
    with open(full_file_path, "a+") as log:
IOError: [Errno 13] Permission denied: '/home/linq/Zeus-Scanner/log/blackwidow-log/blackwidow-log-1.log'

2018-01-12 11:07:12,361;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2018-01-12 11:07:12,361;zeus-log;INFO;[32mgetting authorization[0m
2018-01-12 11:07:12,362;zeus-log;INFO;[32mextracting traceback from log file[0m
2018-01-12 11:07:12,362;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
sudo
