### ISSUE TITLE
Unhandled exception (BtDylxb)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#335]
Zeus version:
`1.4.13.e5ac63`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 330, in <module>
    __run_attacks_main()
  File "zeus.py", line 141, in __run_attacks_main
    threads=opt.amountOfThreads, force_ssl=opt.forceSSL
  File "/scan/zeus-scanner/lib/core/settings.py", line 1009, in run_attacks
    force_ssl=force_ssl
  File "/scan/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 233, in main_xss
    requests.exceptions.ReadTimeout,
AttributeError: 'module' object has no attribute 'ReadTimeout'
```

Running details:
`Linux-4.4.0-93-generic-x86_64-with-Ubuntu-14.04-trusty`

Commands used:
`zeus.py -b http://www.xizi.com -x`

Log file info:
```2018-01-12 17:56:52,771;zeus-log;INFO;log file being saved to '/scan/zeus-scanner/log/zeus-log-12.log'
2018-01-12 17:56:52,771;zeus-log;INFO;using default search engine
2018-01-12 17:56:52,772;zeus-log;INFO;starting blackwidow on 'http://www.xizi.com'
2018-01-12 17:56:53,034;zeus-log;INFO;connection test succeeded, continuing
2018-01-12 17:56:53,035;zeus-log;INFO;crawling given URL 'http://www.xizi.com' for links
2018-01-12 17:56:53,936;zeus-log;INFO;found a total of 395 links from given URL 'http://www.xizi.com'
2018-01-12 17:56:53,936;zeus-log;INFO;successfully wrote found items to '/scan/zeus-scanner/log/blackwidow-log/blackwidow-log-2.log'
2018-01-12 17:56:53,937;zeus-log;INFO;currently running on 'http://bbs.xizi.com/thread-4321773-1-1.html' (target #1)
2018-01-12 17:56:53,937;zeus-log;INFO;fetching target meta-data
2018-01-12 17:56:54,729;zeus-log;INFO;detecting target charset
2018-01-12 17:56:54,729;zeus-log;INFO;target charset appears to be 'gbk'
2018-01-12 17:56:54,739;zeus-log;INFO;attempting to get request headers for 'http://bbs.xizi.com/thread-4321773-1-1.html'
2018-01-12 17:56:54,740;zeus-log;INFO;found a request cookie, saving to file
2018-01-12 17:56:54,740;zeus-log;INFO;successfully wrote found items to '/scan/zeus-scanner/log/cookies/bbs.xizi.com-cookie.log'
2018-01-12 17:56:54,741;zeus-log;INFO;writing found headers to log file
2018-01-12 17:56:54,741;zeus-log;INFO;successfully wrote found items to '/scan/zeus-scanner/log/header-log/bbs.xizi.com-headers.json'
2018-01-12 17:57:03,569;zeus-log;INFO;loading payloads
2018-01-12 17:57:03,581;zeus-log;INFO;payloads will be written to a temporary file and read from there
2018-01-12 17:57:03,582;zeus-log;INFO;loaded URL's have been saved to '/tmp/tmpLFZYJG'
2018-01-12 17:57:03,582;zeus-log;INFO;testing for XSS vulnerabilities on host 'http://bbs.xizi.com/thread-4321773-1-1.html'
2018-01-12 17:57:28,401;zeus-log;ERROR;host 'http://bbs.xizi.com/thread-4321773-1-1.html' does not appear to be vulnerable to XSS attacks
2018-01-12 17:57:30,624;zeus-log;INFO;currently running on 'http://bbs.xizi.com/thread-4321569-1-1.html' (target #2)
2018-01-12 17:57:30,624;zeus-log;INFO;fetching target meta-data
2018-01-12 17:57:31,082;zeus-log;INFO;detecting target charset
2018-01-12 17:57:31,083;zeus-log;INFO;target charset appears to be 'gbk'
2018-01-12 17:57:31,083;zeus-log;INFO;attempting to get request headers for 'http://bbs.xizi.com/thread-4321569-1-1.html'
2018-01-12 17:57:31,083;zeus-log;INFO;found a request cookie, saving to file
2018-01-12 17:57:31,084;zeus-log;INFO;successfully wrote found items to '/scan/zeus-scanner/log/cookies/bbs.xizi.com(1).log'
2018-01-12 17:57:31,084;zeus-log;INFO;writing found headers to log file
2018-01-12 17:57:31,084;zeus-log;INFO;successfully wrote found items to '/scan/zeus-scanner/log/header-log/bbs.xizi.com(1).json'
2018-01-12 17:57:37,400;zeus-log;INFO;loading payloads
2018-01-12 17:57:37,400;zeus-log;INFO;payloads will be written to a temporary file and read from there
2018-01-12 17:57:37,401;zeus-log;INFO;loaded URL's have been saved to '/tmp/tmp5eWSsH'
2018-01-12 17:57:37,401;zeus-log;INFO;testing for XSS vulnerabilities on host 'http://bbs.xizi.com/thread-4321569-1-1.html'
2018-01-12 17:58:22,803;zeus-log;ERROR;[7;31;31mran into exception ''module' object has no attribute 'ReadTimeout'' exception has been saved to log file
Traceback (most recent call last):
  File "zeus.py", line 330, in <module>
    __run_attacks_main()
  File "zeus.py", line 141, in __run_attacks_main
    threads=opt.amountOfThreads, force_ssl=opt.forceSSL
  File "/scan/zeus-scanner/lib/core/settings.py", line 1009, in run_attacks
    force_ssl=force_ssl
  File "/scan/zeus-scanner/lib/attacks/xss_scan/__init__.py", line 233, in main_xss
    requests.exceptions.ReadTimeout,
AttributeError: 'module' object has no attribute 'ReadTimeout'

2018-01-12 17:58:37,066;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2018-01-12 17:58:37,066;zeus-log;INFO;[32mgetting authorization[0m
2018-01-12 17:58:37,078;zeus-log;INFO;[32mextracting traceback from log file[0m
2018-01-12 17:58:37,078;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
python2 not python3
