### ISSUE TITLE
Unhandled exception (yDbcnYu)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#340]
Zeus version:
`1.4.13.e5ac63`

Firefox version:
`(52, 5)`

Geckodriver version:
`geckodriver-v0.17.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 258, in <module>
    tor=opt.useTor, batch=opt.runInBatch
  File "/root/zeus-scanner/var/search/selenium_search.py", line 234, in parse_search_results
    proxy_string = proxy_string_to_dict(proxy_string)
  File "/root/zeus-scanner/lib/core/settings.py", line 450, in proxy_string_to_dict
    proxy_data = get_proxy_type(proxy_string)
  File "/root/zeus-scanner/lib/core/settings.py", line 438, in get_proxy_type
    "{}..".format(prox_list[0], difflib.get_close_matches(prox_list[0], acceptable))
InvalidProxyType: [159.89.39.79:1911] is not a valid proxy type, you might be looking for []..
```

Running details:
`Linux-4.14.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`zeus.py --dork-list=/root/Desktop/sql.txt --sqli --proxy-file=/root/Desktop/ghjgjh.txt --verbose --sqlmap-args=threads 10, randomAgent true, getDbs, noCast, --batch --identify-waf --random-agent`

Log file info:
```2018-01-12 10:33:08,425;zeus-log;DEBUG;checking if the application has been run before
2018-01-12 10:33:08,426;zeus-log;DEBUG;verifying operating system
2018-01-12 10:33:08,426;zeus-log;DEBUG;already ran, skipping
2018-01-12 10:33:08,426;zeus-log;DEBUG;running with options '{'proxyFileRand': '/root/Desktop/ghjgjh.txt', 'runSqliScan': True, 'identifyProtection': True, 'useRandomAgent': True, 'runInBatch': True, 'dorkFileToUse': '/root/Desktop/sql.txt', 'sqlmapArguments': 'threads 10, randomAgent true, getDbs, noCast,', 'runInVerbose': True}'
2018-01-12 10:33:08,426;zeus-log;INFO;log file being saved to '/root/zeus-scanner/log/zeus-log-51.log'
2018-01-12 10:33:08,426;zeus-log;DEBUG;loading random proxy from '/root/Desktop/ghjgjh.txt'
2018-01-12 10:33:08,427;zeus-log;DEBUG;grabbing random user-agent from '/root/zeus-scanner/etc/text_files/agents.txt'
2018-01-12 10:33:08,427;zeus-log;INFO;random agent being used 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.2.15) Gecko/20110303 Firefox/3.6.15 (.NET CLR 3.5.30729)'
2018-01-12 10:33:08,428;zeus-log;DEBUG;using default search engine (Google)
2018-01-12 10:33:08,428;zeus-log;INFO;using default search engine
2018-01-12 10:33:08,428;zeus-log;INFO;starting dork scan with query '/Shopping.css?card=2017'
2018-01-12 10:33:08,428;zeus-log;DEBUG;parsing blacklist
2018-01-12 10:33:08,428;zeus-log;DEBUG;checking for user-agent and proxy configuration
2018-01-12 10:33:08,428;zeus-log;WARNING;will not parse webcache URL's (to parse webcache pass -W)
2018-01-12 10:33:08,428;zeus-log;WARNING;only pulling URLs with GET(query) parameters (to pull all URL's pass -E)
2018-01-12 10:33:08,429;zeus-log;ERROR;[7;31;31mran into exception '[159.89.39.79:1911] is not a valid proxy type, you might be looking for []..'
Traceback (most recent call last):
  File "zeus.py", line 258, in <module>
    tor=opt.useTor, batch=opt.runInBatch
  File "/root/zeus-scanner/var/search/selenium_search.py", line 234, in parse_search_results
    proxy_string = proxy_string_to_dict(proxy_string)
  File "/root/zeus-scanner/lib/core/settings.py", line 450, in proxy_string_to_dict
    proxy_data = get_proxy_type(proxy_string)
  File "/root/zeus-scanner/lib/core/settings.py", line 438, in get_proxy_type
    "{}..".format(prox_list[0], difflib.get_close_matches(prox_list[0], acceptable))
InvalidProxyType: [159.89.39.79:1911] is not a valid proxy type, you might be looking for []..

2018-01-12 10:33:15,170;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2018-01-12 10:33:15,170;zeus-log;INFO;[32mgetting authorization[0m
2018-01-12 10:33:15,170;zeus-log;INFO;[32mextracting traceback from log file[0m
2018-01-12 10:33:15,170;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
Can you give me an example of how the proxies look in your file?

**Comment by Ekultek** [comment]
The reason you’re getting this is that your proxy has no protocol. I guess I could auto assign a protocol if none is given, but that would probably cause more issues. If you can provide an example of what your proxies look like in your file, I can do something about this. And stop trying to do the same thing it’s obviously not working
