### ISSUE TITLE
Unhandled exception (NCDTRSj)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#342]
Zeus version:
`1.4.13.e5ac63`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/home/chiou_mark/zeus-scanner/lib/attacks/sqlmap_scan/__init__.py", line 222, in sqlmap_scan_main
    sqlmap_scan.show_sqlmap_log(api_id)
  File "/home/chiou_mark/zeus-scanner/lib/attacks/sqlmap_scan/__init__.py", line 126, in show_sqlmap_log
    log_json = json.loads(log_req.content)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Running details:
`Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-16.04-xenial`

Commands used:
`zeus.py --tor --sqli --show-possibles -b http://comicxstudio.com/`

Log file info:
```2018-01-15 06:23:46,500;zeus-log;INFO;found a total of 18 links from given URL 'http://comicxstudio.com/'
2018-01-15 06:23:46,503;zeus-log;INFO;successfully wrote found items to '/home/chiou_mark/zeus-scanner/log/blackwidow-log/blackwidow-log-10.log'
2018-01-15 06:23:46,507;zeus-log;INFO;currently running on 'http://comicxstudio.com/#news' (target #1)
2018-01-15 06:23:46,507;zeus-log;INFO;fetching target meta-data
2018-01-15 06:23:46,602;zeus-log;INFO;detecting target charset
2018-01-15 06:23:46,603;zeus-log;INFO;target charset appears to be 'utf-8'
2018-01-15 06:23:46,605;zeus-log;INFO;attempting to get request headers for 'http://comicxstudio.com/#news'
2018-01-15 06:23:46,606;zeus-log;INFO;writing found headers to log file
2018-01-15 06:23:46,608;zeus-log;INFO;successfully wrote found items to '/home/chiou_mark/zeus-scanner/log/header-log/comicxstudio.com(3).json'
2018-01-15 06:23:50,612;zeus-log;INFO;creating arguments for sqlmap
2018-01-15 06:23:52,104;zeus-log;INFO;initializing new sqlmap scan with given URL 'http://comicxstudio.com/#news'
2018-01-15 06:23:53,108;zeus-log;ERROR;sqlmap API is not started, did you forget to start it? You will need to open a new terminal, cd into sqlmap, and run `python sqlmapapi.py -s` otherwise pass the correct flags to auto start the API
2018-01-15 06:23:53,108;zeus-log;INFO;currently running on 'http://comicxstudio.com/#service' (target #2)
2018-01-15 06:23:53,108;zeus-log;INFO;fetching target meta-data
2018-01-15 06:23:53,186;zeus-log;INFO;detecting target charset
2018-01-15 06:23:53,186;zeus-log;INFO;target charset appears to be 'utf-8'
2018-01-15 06:23:53,187;zeus-log;INFO;attempting to get request headers for 'http://comicxstudio.com/#service'
2018-01-15 06:23:53,187;zeus-log;INFO;writing found headers to log file
2018-01-15 06:23:53,189;zeus-log;INFO;successfully wrote found items to '/home/chiou_mark/zeus-scanner/log/header-log/comicxstudio.com(4).json'
2018-01-15 06:24:25,831;zeus-log;WARNING;skipping 'http://comicxstudio.com/#service'
2018-01-15 06:24:25,831;zeus-log;INFO;currently running on 'http://www.comicxstudio.com/img/news/news003.html' (target #3)
2018-01-15 06:24:25,832;zeus-log;INFO;fetching target meta-data
2018-01-15 06:24:25,939;zeus-log;INFO;detecting target charset
2018-01-15 06:24:25,939;zeus-log;INFO;target charset appears to be 'iso-8859-1'
2018-01-15 06:24:25,940;zeus-log;INFO;attempting to get request headers for 'http://www.comicxstudio.com/img/news/news003.html'
2018-01-15 06:24:25,940;zeus-log;INFO;writing found headers to log file
2018-01-15 06:24:25,941;zeus-log;INFO;successfully wrote found items to '/home/chiou_mark/zeus-scanner/log/header-log/www.comicxstudio.com-headers.json'
2018-01-15 06:24:28,783;zeus-log;INFO;creating arguments for sqlmap
2018-01-15 06:24:30,858;zeus-log;INFO;initializing new sqlmap scan with given URL 'http://www.comicxstudio.com/img/news/news003.html'
2018-01-15 06:24:30,862;zeus-log;INFO;gathering sqlmap API scan ID
2018-01-15 06:24:30,866;zeus-log;INFO;starting sqlmap scan on url: 'http://www.comicxstudio.com/img/news/news003.html'
2018-01-15 06:24:30,866;zeus-log;WARNING;please keep in mind that this is the API, output will not be saved to log file, it may take a little longer to finish processing, launching sqlmap
2018-01-15 06:24:33,998;zeus-log;ERROR;[7;31;31mran into error 'No JSON object could be decoded', seems something went wrong, error has been saved to current log file.
Traceback (most recent call last):
  File "/home/chiou_mark/zeus-scanner/lib/attacks/sqlmap_scan/__init__.py", line 222, in sqlmap_scan_main
    sqlmap_scan.show_sqlmap_log(api_id)
  File "/home/chiou_mark/zeus-scanner/lib/attacks/sqlmap_scan/__init__.py", line 126, in show_sqlmap_log
    log_json = json.loads(log_req.content)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

2018-01-15 06:24:47,530;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2018-01-15 06:24:47,530;zeus-log;INFO;[32mgetting authorization[0m
2018-01-15 06:24:47,534;zeus-log;INFO;[32mextracting traceback from log file[0m
2018-01-15 06:24:47,538;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
You need to manually start the API, this is a known issue, and there's not really a fix for this
