### ISSUE TITLE
Unhandled exception (FQmkUUy)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#354]
Zeus version:
`1.4.13.e5ac63`

Firefox version:
`(57, 0)`

Geckodriver version:
`geckodriver-v0.19.0-linux64.tar.gz`

Error info:
```Traceback (most recent call last):
  File "/opt/Zeus-Scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/opt/Zeus-Scanner/var/search/selenium_search.py", line 84, in get_urls
    browser.get(url)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 324, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
TimeoutException: Message: Timeout loading page after 300000ms
```

Running details:
`Linux-4.9.77-1-lts-x86_64-with-glibc2.2.5`

Commands used:
`./zeus.py --random-agent -W -E --show-success -A --proxy-file=/home/shaman/Downloads/share/dorks/proxy --dork-list=/home/shaman/Downloads/share/dorks/mydorks`

Log file info:
```2018-01-26 14:04:37,961;zeus-log;INFO;log file being saved to '/opt/Zeus-Scanner/log/zeus-log-6.log'
2018-01-26 14:04:37,962;zeus-log;INFO;random agent being used 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.4) Gecko/20070531 Firefox/2.0.0.4'
2018-01-26 14:04:37,962;zeus-log;WARNING;AOL will take a little longer due to pop-ups
2018-01-26 14:04:37,962;zeus-log;INFO;specified to use non-default search engine
2018-01-26 14:04:37,962;zeus-log;INFO;starting dork scan with query 'fellows.php?id'
2018-01-26 14:04:37,962;zeus-log;INFO;attempting to gather query URL
2018-01-26 14:04:37,962;zeus-log;INFO;setting up virtual display to hide the browser
2018-01-26 14:04:38,078;zeus-log;INFO;setting the browser
2018-01-26 14:04:41,349;zeus-log;INFO;browser will open shortly
2018-01-26 14:09:41,355;zeus-log;ERROR;[7;31;31mselenium_search.pyc failed to gather the URL from search engine, caught exception 'Message: Timeout loading page after 300000ms' exception has been logged to current log file
Traceback (most recent call last):
  File "/opt/Zeus-Scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/opt/Zeus-Scanner/var/search/selenium_search.py", line 84, in get_urls
    browser.get(url)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 324, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
TimeoutException: Message: Timeout loading page after 300000ms


2018-01-26 14:10:53,552;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait[0m
2018-01-26 14:10:53,552;zeus-log;INFO;[32mgetting authorization[0m
2018-01-26 14:10:53,565;zeus-log;INFO;[32mextracting traceback from log file[0m
2018-01-26 14:10:53,565;zeus-log;INFO;[32mattempting to get firefox browser version[0m
```

**Comment by Ekultek** [comment]
It’s possible that this is just your proxy not playing nice with AOL. When you use aol there is a popup that occurs, Zeus will not continue until it has established that the pop is gone. If the popup does not show up however, it’s not going to work successfully.

Try using a different proxy, or Tor and see what happens

**Comment by Ekultek** [comment]
This is your proxy I cannot reproduce this with anything
