### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by stevenpsm** [Ekultek/Zeus-Scanner#387]
# What's the problem

simon@simon-virtual-machine:~/Documents/Zeus-Scanner-1.5$ python zeus.py
Traceback (most recent call last):
  File "zeus.py", line 10, in <module>
    from var import blackwidow
  File "/home/simon/Documents/Zeus-Scanner-1.5/var/blackwidow/__init__.py", line 6, in <module>
    import lib.core.common
  File "/home/simon/Documents/Zeus-Scanner-1.5/lib/core/common.py", line 19, in <module>
    import lib.core.settings
  File "/home/simon/Documents/Zeus-Scanner-1.5/lib/core/settings.py", line 38, in <module>
    PATCH_ID = str(subprocess.check_output(["git", "rev-parse", "origin/master"]))[:6]
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

# Running context

 - Operating system: 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial

 
 - Zeus version:
1.5
# Any idea on a solution?

# Full console commands run

# Stacktrace (if applicable)

# Full file log information

**Comment by Ekultek** [comment]
If you’re running 1.5 you need to update Zeus

**Comment by stevenpsm** [comment]
hi, thanks very much for reply, but it  still  not work after I updated to the master branch.
I'm using geckodriver  version 0.19.0  and firefox 58.0;

the error displayed when running:
------------------------------------------------------------------------------------------------
simon@simon-virtual-machine:~/Documents/Zeus-Scanner-master$ python zeus.py
Traceback (most recent call last):
  File "zeus.py", line 10, in <module>
    from var import blackwidow
  File "/home/simon/Documents/Zeus-Scanner-master/var/blackwidow/__init__.py", line 6, in <module>
    import lib.core.common
  File "/home/simon/Documents/Zeus-Scanner-master/lib/core/common.py", line 19, in <module>
    import lib.core.settings
  File "/home/simon/Documents/Zeus-Scanner-master/lib/core/settings.py", line 38, in <module>
    PATCH_ID = str(subprocess.check_output(["git", "rev-parse", "origin/master"]))[:6]
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by Ekultek** [comment]
What happens when you run `git pull origin master` from the Zeus directory?

**Comment by stevenpsm** [comment]
sorry  for  so long  time feedback，"git pull" is very slow in China.
it works!  previous error is gone.  **but another error accured:**
" geckodriver has hit an error that usually means it needs to be reinstalled"
I reinstalled it again  for several times, but still  hit the same error.
I'm using geckodriver version 0.19.0 and firefox 58.0;
-------------
[12:06:07 INFO] log file being saved to '/home/simon/Documents/zeus-scanner/log/zeus-log-8.log'
[12:06:07 INFO] using default search engine
[12:06:07 INFO] starting dork scan with query 'inurl:php?id='
[12:06:07 WARNING] will not parse webcache URL's (to parse webcache pass -W)
[12:06:07 WARNING] only pulling URLs with GET(query) parameters (to pull all URL's pass -E)
[12:06:07 INFO] attempting to gather query URL
[12:06:07 INFO] setting up virtual display to hide the browser
[12:06:07 INFO] setting the browser
[12:06:10 INFO] browser will open shortly
**[12:07:41 CRITICAL] geckodriver has hit an error that usually means it needs to be reinstalled**
[12:07:41 PROMPT] would you like to attempt a reinstallation of the geckodriver[y/N]: y
[12:08:23 WARNING] rewriting all executed information, path information, and removing geckodriver
[12:08:23 INFO] all paths rewritten, you will be forced to re-install everything next run of Zeus
-------------------------

**Comment by Ekultek** [comment]
Hey, sorry for the late response. Go ahead and reinstall firefox and that should do the trick

**Comment by stevenpsm** [comment]
hi, sorry for reply late, I found the reason,because in china google is not accessable without vpn or proxy,so the default search of zeus-scanner through google is not available, and did time out, but the error msg was " geckodriver has hit an error that usually means it needs to be reinstalled"  without showing the browser, and confused me, so i reinstalled it for many times...  
so i think it is a bug.  thanks a lot.

**Comment by Ekultek** [comment]
That makes sense. I’ll have to look into the errors
