### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'set' and 'str'

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#40]
Zeus version:
`1.0.27.de68`

Error info:
```Traceback (most recent call last):
  File "./zeus.py", line 410, in <module>
    agent=agent_to_use
  File "/root/Zeus-Scanner/var/google_search/search.py", line 274, in parse_search_results
    write_to_log_file(retval, URL_LOG_PATH, "url-log-{}.log")
  File "/root/Zeus-Scanner/lib/settings.py", line 399, in write_to_log_file
    log.write(data_to_write + "\n")
TypeError: unsupported operand type(s) for +: 'set' and 'str'
````

Running details:
`Linux-4.9.0-kali4-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`./zeus.py -d config.php`

Log file info:
```2017-10-04 14:14:51,021;zeus-log;INFO;log file being saved to '/root/Zeus-Scanner/log/zeus-log-6.log'...
2017-10-04 14:14:51,021;zeus-log;INFO;using default search engine...
2017-10-04 14:14:51,021;zeus-log;INFO;starting dork scan with query 'config.php'...
2017-10-04 14:14:51,021;zeus-log;INFO;attempting to gather query URL...
2017-10-04 14:14:51,147;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-04 14:14:51,147;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-04 14:14:55,334;zeus-log;INFO;browser will open shortly...
2017-10-04 14:14:56,023;zeus-log;INFO;searching 'http://google.com' using query 'config.php'...
2017-10-04 14:14:59,197;zeus-log;INFO;closing the browser and continuing process..
2017-10-04 14:14:59,226;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-04 14:14:59,226;zeus-log;INFO;no proxy configuration detected...
2017-10-04 14:14:59,606;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.27.de68)::Python->v2.7'...
2017-10-04 14:14:59,612;zeus-log;INFO;found a total of 5 URL's with a GET parameter...
2017-10-04 14:14:59,612;zeus-log;ERROR;[7;31;31mran into exception 'unsupported operand type(s) for +: 'set' and 'str''...
Traceback (most recent call last):
  File "./zeus.py", line 410, in <module>
    agent=agent_to_use
  File "/root/Zeus-Scanner/var/google_search/search.py", line 274, in parse_search_results
    write_to_log_file(retval, URL_LOG_PATH, "url-log-{}.log")
  File "/root/Zeus-Scanner/lib/settings.py", line 399, in write_to_log_file
    log.write(data_to_write + "\n")
TypeError: unsupported operand type(s) for +: 'set' and 'str'

2017-10-04 14:15:03,314;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-04 14:15:03,314;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-04 14:15:03,324;zeus-log;INFO;[32mextracting traceback from log file...[0m
```

**Comment by Ekultek** [comment]
```
baal@baal-Aspire-5733Z:~/bin/python/zeus-scanner$ sudo python zeus.py -d config.php

    __          __________                             __   
   / /          \____    /____  __ __  ______          \ \  
  / /    ______   /     // __ \|  |  \/  ___/  ______   \ \ 
  \ \   /_____/  /     /\  ___/|  |  /\___ \  /_____/   / / 
   \_\          /_______ \___  >____//____  >          /_/  
                       \/   \/           \/  v1.0.27.de68(revision)
	https://github.com/ekultek/zeus-scanner.git
		Advanced Dork Searching...


[*] starting up at 07:04:18..


[07:04:18 INFO] log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-275.log'...
[07:04:18 INFO] using default search engine...
[07:04:18 INFO] starting dork scan with query 'config.php'...
[07:04:18 INFO] attempting to gather query URL...
[07:04:19 INFO] firefox browser display will be hidden while it performs the query...
[07:04:19 WARNING] your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
[07:04:49 INFO] browser will open shortly...
[07:04:52 INFO] searching 'http://google.com' using query 'config.php'...
[07:04:55 INFO] closing the browser and continuing process..
[07:04:55 INFO] URL successfully gathered, searching for GET parameters...
[07:04:55 INFO] no proxy configuration detected...
[07:04:56 INFO] adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.27.de68)::Python->v2.7'...
[07:04:56 INFO] found a total of 5 URL's with a GET parameter...
[07:04:56 INFO] successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/url-log/url-log-71.log'...


[*] shutting down at 07:04:56..


baal@baal-Aspire-5733Z:~/bin/python/zeus-scanner$ 
```

fixed via 1e71aaa
