### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/usr/lib/firefoxdriver/webdriver.xpi'

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#52]
Zeus version:
`1.0.31`

Error info:
```Traceback (most recent call last):
  File "/home/hacker/Document/tools/Zeus-Scanner/var/google_search/search.py", line 241, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/home/hacker/Document/tools/Zeus-Scanner/var/google_search/search.py", line 129, in get_urls
    browser = webdriver.Firefox(profile, proxy=proxy_to_use)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 77, in __init__
    self.binary, timeout),
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 47, in __init__
    self.profile.add_extension()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_profile.py", line 91, in add_extension
    self._install_extension(extension)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_profile.py", line 251, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '/usr/lib/firefoxdriver/webdriver.xpi'
````

Running details:
`Linux-4.4.0-96-generic-x86_64-with-Ubuntu-16.04-xenial`

Commands used:
`zeus.py -d inurl:id`

Log file info:
```2017-10-08 15:17:48,862;zeus-log;INFO;log file being saved to '/home/hacker/Document/tools/Zeus-Scanner/log/zeus-log-9.log'...
2017-10-08 15:17:48,862;zeus-log;INFO;using default search engine...
2017-10-08 15:17:48,862;zeus-log;INFO;starting dork scan with query 'inurl:id'...
2017-10-08 15:17:48,862;zeus-log;INFO;attempting to gather query URL...
2017-10-08 15:17:48,977;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-08 15:17:48,977;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-08 15:17:48,978;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception '[Errno 2] No such file or directory: '/usr/lib/firefoxdriver/webdriver.xpi'' exception has been logged to current log file...
Traceback (most recent call last):
  File "/home/hacker/Document/tools/Zeus-Scanner/var/google_search/search.py", line 241, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/home/hacker/Document/tools/Zeus-Scanner/var/google_search/search.py", line 129, in get_urls
    browser = webdriver.Firefox(profile, proxy=proxy_to_use)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 77, in __init__
    self.binary, timeout),
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 47, in __init__
    self.profile.add_extension()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_profile.py", line 91, in add_extension
    self._install_extension(extension)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_profile.py", line 251, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '/usr/lib/firefoxdriver/webdriver.xpi'

2017-10-08 15:17:56,881;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-08 15:17:56,881;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-08 15:17:56,881;zeus-log;INFO;[32mextracting traceback from log file...[0m
```

**Comment by Ekultek** [comment]
I don't know what this is. Give me a little bit to do some research

**Comment by Ekultek** [comment]
Okay, this has something to do with your firefox installation, this error happens when firefox cannot be found in the default location, so if you've moved the installation or something then it won't be there and you'll get this error.. Not sure what's going on with it. A couple things you can try:

 - Restart the system and try again
 - Make sure that your `python` command is pointing to `2.7` and not `3.x`
 - Reinstall firefox

There's nothing I can do about this issue except create a patch to say it wasn't found.

**Comment by Ekultek** [comment]
I created a basic patch for this, just to catch the error and display that firefox was not found. Other then that, there's not much more I can do for you here (2937e9c)
