### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#54]
Zeus version:
`1.0.31`

Error info:
```Traceback (most recent call last):
  File "./zeus.py", line 494, in <module>
    __run_attacks_main()
  File "./zeus.py", line 431, in __run_attacks_main
    with open(urls_to_use) as urls:
TypeError: coercing to Unicode: need string or buffer, NoneType found
````

Running details:
`Linux-4.12.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling`

Commands used:
`./zeus.py -d texas -M -B -s -L 25`

Log file info:
```2017-10-08 05:19:10,424;zeus-log;INFO;log file being saved to '/root/Zeus-Scanner/log/zeus-log-5.log'...
2017-10-08 05:19:10,425;zeus-log;INFO;using default search engine...
2017-10-08 05:19:10,426;zeus-log;INFO;searching Google using dork 'texas' for a total of 25 links...
2017-10-08 05:19:10,427;zeus-log;WARNING;multiple pages will be searched using Google's API client, searches may be blocked after a certain amount of time...
2017-10-08 05:19:17,625;zeus-log;ERROR;unable to extract URL's from results...
2017-10-08 05:19:17,626;zeus-log;ERROR;unable to run attacks appears that no file was created for the retrieved data...
2017-10-08 05:19:17,626;zeus-log;ERROR;[7;31;31mran into exception 'coercing to Unicode: need string or buffer, NoneType found' exception has been saved to log file...
Traceback (most recent call last):
  File "./zeus.py", line 494, in <module>
    __run_attacks_main()
  File "./zeus.py", line 431, in __run_attacks_main
    with open(urls_to_use) as urls:
TypeError: coercing to Unicode: need string or buffer, NoneType found

2017-10-08 05:20:32,116;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-08 05:20:32,116;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-08 05:20:32,118;zeus-log;INFO;[32mextracting traceback from log file...[0m
```

**Comment by Ekultek** [comment]
Fixed via https://github.com/Ekultek/Zeus-Scanner/commit/4188c2c37c8384627f92807e125f5ff4ae54a90d
