### ISSUE TITLE
TypeError: worker() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#58]
Zeus version:
`1.0.36.6a42`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 563, in <module>
    __run_attacks_main()
  File "zeus.py", line 466, in __run_attacks_main
    auto=opt.autoStartSqlmap, verbose=opt.runInVerbose, batch=opt.runInBatch
  File "zeus.py", line 420, in __run_attacks
    auto_search=auto, given_path=given_path)
  File "/home/ubuntu/Zeus-Scanner/lib/attacks/sqlmap_scan/__init__.py", line 133, in sqlmap_scan_main
    path = ''.join(find_sqlmap(verbose=verbose, given_search_path=given_path))
  File "/home/ubuntu/Zeus-Scanner/lib/attacks/sqlmap_scan/__init__.py", line 115, in find_sqlmap
    return lib.core.settings.find_application(to_find, verbose=verbose, given_search_path=given_search_path)
  File "/home/ubuntu/Zeus-Scanner/lib/core/settings.py", line 333, in find_application
    results = pool.map(worker, file_data_gen)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: worker() takes exactly 2 arguments (1 given)
````

Running details:
`Linux-4.4.0-1022-aws-x86_64-with-Ubuntu-16.04-xenial`

Commands used:
`zeus.py -r -s --auto-start`

Log file info:
```2017-10-11 11:41:17,366;zeus-log;INFO;log file being saved to '/home/ubuntu/Zeus-Scanner/log/zeus-log-11.log'...
2017-10-11 11:41:17,366;zeus-log;INFO;using default search engine...
2017-10-11 11:41:17,367;zeus-log;INFO;using random dork 'resourcesinurl:/vulnerabilities_list.php?id=' as the search query...
2017-10-11 11:41:17,368;zeus-log;INFO;attempting to gather query URL...
2017-10-11 11:41:17,482;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-11 11:41:17,483;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-11 11:41:21,660;zeus-log;INFO;browser will open shortly...
2017-10-11 11:41:22,298;zeus-log;INFO;searching 'http://google.com' using query 'resourcesinurl:/vulnerabilities_list.php?id='...
2017-10-11 11:41:25,541;zeus-log;INFO;closing the browser and continuing process..
2017-10-11 11:41:25,572;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-11 11:41:25,572;zeus-log;INFO;no proxy configuration detected...
2017-10-11 11:41:25,886;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.36.6a42)::Python->v2.7'...
2017-10-11 11:41:25,888;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 11:41:25,889;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 11:41:25,889;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 11:41:25,889;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 11:41:25,890;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 11:41:25,890;zeus-log;INFO;found a total of 9 URL's with a GET parameter...
2017-10-11 11:41:25,890;zeus-log;INFO;successfully wrote found items to '/home/ubuntu/Zeus-Scanner/log/url-log/url-log-9.log'...
2017-10-11 11:41:28,620;zeus-log;INFO;creating arguments for sqlmap...
2017-10-11 11:41:28,620;zeus-log;INFO;attempting to find sqlmap on your system...
2017-10-11 11:41:28,620;zeus-log;ERROR;sqlmapapi.py not in your PATH, what kind of hacker are you?! defaulting to root search, this can take awhile...
2017-10-11 11:41:39,670;zeus-log;ERROR;[7;31;31mran into exception 'worker() takes exactly 2 arguments (1 given)' and cannot continue, saved to current log file...
Traceback (most recent call last):
  File "zeus.py", line 563, in <module>
    __run_attacks_main()
  File "zeus.py", line 466, in __run_attacks_main
    auto=opt.autoStartSqlmap, verbose=opt.runInVerbose, batch=opt.runInBatch
  File "zeus.py", line 420, in __run_attacks
    auto_search=auto, given_path=given_path)
  File "/home/ubuntu/Zeus-Scanner/lib/attacks/sqlmap_scan/__init__.py", line 133, in sqlmap_scan_main
    path = ''.join(find_sqlmap(verbose=verbose, given_search_path=given_path))
  File "/home/ubuntu/Zeus-Scanner/lib/attacks/sqlmap_scan/__init__.py", line 115, in find_sqlmap
    return lib.core.settings.find_application(to_find, verbose=verbose, given_search_path=given_search_path)
  File "/home/ubuntu/Zeus-Scanner/lib/core/settings.py", line 333, in find_application
    results = pool.map(worker, file_data_gen)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: worker() takes exactly 2 arguments (1 given)

2017-10-11 11:41:52,757;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-11 11:41:52,758;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-11 11:41:52,759;zeus-log;INFO;[32mextracting traceback from log file...[0m
```

**Comment by Ekultek** [comment]
For now add sqlmap to your ENV PATH, and make sure to start the `sqlmap API` before continuing. How you do that:

 - `cd "where ever you have sqlmap"`
 - `python sqlmapapi.py -s`

**Comment by Ekultek** [comment]
This is going to be taken out, completely, I'm working on fixing the sqlmap API launch, but for now I'm getting rid of this issue.

**Comment by Ekultek** [comment]
initial fix for this was done here https://github.com/Ekultek/Zeus-Scanner/commit/e9f5b82d0586766b9e2a177adefedee8f21c7943 there's still a ton of work to be done so I decided to suppress the help on the `--auto` flag until it is done (here https://github.com/Ekultek/Zeus-Scanner/commit/859ea19c44151a13e1e6c0847926774043c85b48). Other then that you should be good to go now. This is going to remain open until completely patched,

**Comment by Ekultek** [comment]
Work almost done with 37f1669

**Comment by Ekultek** [comment]
Work finished via https://github.com/Ekultek/Zeus-Scanner/commit/bdcc28b4122f3af4a53616429acc2334d09a3f56
