### ISSUE TITLE
cant get it started

### ISSUE THREAD

**Issue by vinkzspam** [Ekultek/Zeus-Scanner#658]
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/mypc which is owned by mypc.)
Traceback (most recent call last):ing the application, doing setup please wait..
  File "zeus.py", line 62, in <module>
    setup(verbose=opt.runInVerbose)
  File "/home/mypc/zeus-scanner/lib/core/settings.py", line 462, in setup
    bin.unzip_gecko.main(verbose=verbose)
  File "/home/mypc/zeus-scanner/bin/unzip_gecko.py", line 248, in main
    untar_gecko()
  File "/home/mypc/zeus-scanner/bin/unzip_gecko.py", line 178, in untar_gecko
    ff_version = lib.core.settings.get_browser_version(output=False)
  File "/home/mypc/zeus-scanner/lib/core/settings.py", line 613, in get_browser_version
    output = subprocess.check_output(firefox_version_command)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['firefox', '--version']' returned non-zero exit status 1

**Comment by vinkzspam** [comment]
pls someone should help me what should i do

**Comment by Ekultek** [comment]
hiya, this isnt really updated or even looked at anymore to be honest with you. Whats your firefox version?

**Comment by Ekultek** [comment]
your firefox isnt returning a version. so install selenium and change the "ran" file to say "YES"
