### ISSUE TITLE
HTTPError: HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#74]
Zeus version:
`1.0.36.6a42`

Error info:
```Traceback (most recent call last):
  File "/home/baal/bin/python/dev/zeus-scanner/lib/attacks/sqlmap_scan/__init__.py", line 176, in sqlmap_scan_main
    sqlmap_scan.start_scan(api_id, opts=opts)
  File "/home/baal/bin/python/dev/zeus-scanner/lib/attacks/sqlmap_scan/__init__.py", line 76, in start_scan
    return urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
````

Running details:
`Linux-4.10.0-35-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -d pagina.php?go= -s --verbose`

Log file info:
```2017-10-11 13:00:44,240;zeus-log;DEBUG;checking if the application has been run before...
2017-10-11 13:00:44,241;zeus-log;DEBUG;verifying operating system...
2017-10-11 13:00:44,241;zeus-log;DEBUG;already ran, skipping...
2017-10-11 13:00:46,953;zeus-log;DEBUG;running with options '{'runInVerbose': True, 'runSqliScan': True, 'dorkToUse': 'pagina.php?go='}'...
2017-10-11 13:00:46,954;zeus-log;INFO;log file being saved to '/home/baal/bin/python/dev/zeus-scanner/log/zeus-log-4.log'...
2017-10-11 13:00:46,954;zeus-log;DEBUG;using default search engine (Google)...
2017-10-11 13:00:46,955;zeus-log;INFO;using default search engine...
2017-10-11 13:00:46,955;zeus-log;INFO;starting dork scan with query 'pagina.php?go='...
2017-10-11 13:00:46,955;zeus-log;DEBUG;checking for user-agent and proxy configuration...
2017-10-11 13:00:46,955;zeus-log;INFO;attempting to gather query URL...
2017-10-11 13:00:46,956;zeus-log;DEBUG;setting up the virtual display to hide the browser...
2017-10-11 13:00:47,237;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-11 13:00:47,238;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-11 13:00:47,238;zeus-log;DEBUG;running selenium-webdriver and launching browser...
2017-10-11 13:00:47,238;zeus-log;DEBUG;adjusting selenium-webdriver user-agent to 'Zeus-Scanner(v1.0.36.6a42)::Python->v2.7'...
2017-10-11 13:00:57,773;zeus-log;INFO;browser will open shortly...
2017-10-11 13:00:59,941;zeus-log;DEBUG;searching search engine for the 'q' element (search button)...
2017-10-11 13:01:00,000;zeus-log;INFO;searching 'http://google.com' using query 'pagina.php?go='...
2017-10-11 13:01:03,471;zeus-log;DEBUG;obtaining URL from selenium...
2017-10-11 13:01:03,480;zeus-log;DEBUG;found current URL from selenium browser...
2017-10-11 13:01:03,480;zeus-log;INFO;closing the browser and continuing process..
2017-10-11 13:01:03,572;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-11 13:01:03,572;zeus-log;INFO;no proxy configuration detected...
2017-10-11 13:01:04,015;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.36.6a42)::Python->v2.7'...
2017-10-11 13:01:04,019;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 13:01:04,019;zeus-log;DEBUG;found 'https://stackoverflow.com/questions/768431/how-to-make-a-redirect-in-php'...
2017-10-11 13:01:04,020;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 13:01:04,020;zeus-log;DEBUG;found 'http://php.net/manual/en/tutorial.firstpage.php'...
2017-10-11 13:01:04,020;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 13:01:04,020;zeus-log;DEBUG;found 'http://php.net/manual/en/function.header.php'...
2017-10-11 13:01:04,021;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 13:01:04,021;zeus-log;DEBUG;found 'http://ccm.net/faq/9296-php-redirect-to-another-page'...
2017-10-11 13:01:04,021;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 13:01:04,022;zeus-log;DEBUG;found 'https://www.godaddy.com/help/view-or-change-your-php-version-3937'...
2017-10-11 13:01:04,022;zeus-log;DEBUG;found 'https://www.godaddy.com/help/view-or-change-your-php-version-3937+pagina.php?go='...
2017-10-11 13:01:04,022;zeus-log;DEBUG;found 'https://books.google.com/books?id=7kOZAwAAQBAJ'...
2017-10-11 13:01:04,022;zeus-log;DEBUG;found 'https://books.google.com/books?isbn=8575223607</cite'...
2017-10-11 13:01:04,023;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 13:01:04,023;zeus-log;DEBUG;found 'http://www.oddcast.com/home/demos/tts/tts_example.php'...
2017-10-11 13:01:04,023;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 13:01:04,023;zeus-log;DEBUG;found 'https://www.phpmyadmin.net/'...
2017-10-11 13:01:04,024;zeus-log;DEBUG;found 'https://www.phpmyadmin.net/+pagina.php?go='...
2017-10-11 13:01:04,024;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 13:01:04,024;zeus-log;DEBUG;found 'https://www.tiobe.com/tiobe-index/'...
2017-10-11 13:01:04,025;zeus-log;INFO;received webcache URL, extracting URL from webcache...
2017-10-11 13:01:04,025;zeus-log;DEBUG;found 'https://www.sublimetext.com/'...
2017-10-11 13:01:04,025;zeus-log;INFO;found a total of 13 URL's with a GET parameter...
2017-10-11 13:01:04,026;zeus-log;INFO;successfully wrote found items to '/home/baal/bin/python/dev/zeus-scanner/log/url-log/url-log-3.log'...
2017-10-11 13:01:19,046;zeus-log;INFO;creating arguments for sqlmap...
2017-10-11 13:01:19,047;zeus-log;INFO;initializing new sqlmap scan with given URL 'https://www.godaddy.com/help/view-or-change-your-php-version-3937'...
2017-10-11 13:01:19,055;zeus-log;DEBUG;scan initialized...
2017-10-11 13:01:19,056;zeus-log;INFO;gathering sqlmap API scan ID...
2017-10-11 13:01:19,062;zeus-log;DEBUG;current sqlmap scan ID: 'f29fff1ab8f3609b'...
2017-10-11 13:01:19,062;zeus-log;INFO;starting sqlmap scan on url: 'https://www.godaddy.com/help/view-or-change-your-php-version-3937'...
2017-10-11 13:01:19,062;zeus-log;DEBUG;no arguments passed, skipping...
2017-10-11 13:01:19,062;zeus-log;WARNING;please keep in mind that this is the API, output will not be saved to log file, it may take a little longer to finish processing, launching sqlmap...
2017-10-11 13:01:19,082;zeus-log;ERROR;[7;31;31mran into error 'HTTP Error 500: Internal Server Error', seems something went wrong, error has been saved to current log file.
Traceback (most recent call last):
  File "/home/baal/bin/python/dev/zeus-scanner/lib/attacks/sqlmap_scan/__init__.py", line 176, in sqlmap_scan_main
    sqlmap_scan.start_scan(api_id, opts=opts)
  File "/home/baal/bin/python/dev/zeus-scanner/lib/attacks/sqlmap_scan/__init__.py", line 76, in start_scan
    return urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error

2017-10-11 13:01:20,729;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-11 13:01:20,729;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-11 13:01:20,800;zeus-log;INFO;[32mextracting traceback from log file...[0m
```

**Comment by Ekultek** [comment]
This has been asked on sqlmaps page here https://github.com/sqlmapproject/sqlmap/issues/2741

**Comment by Ekultek** [comment]
Re-clone sqlmap and it should work from there.
