### ISSUE TITLE
[ CRITICAL] your current firefox version is not supported by Zeus

### ISSUE THREAD

**Issue by filebe777** [Ekultek/Zeus-Scanner#750]
OS - Parrot OS
python zeus.py --version
v1.5.2.21b875(revision)
=======================================================

seems this is your first time running the applicatIon, doing setup ple
seems this is your first time running the applicatiOn, doing setup ple
[05:49:18 CRITICAL] your current firefox version is not supported by Zeus

[*] shutting down at 05:49:18..

Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/user/Desktop/zeus-scanner/bin/unzip_gecko.py", line 28, in animation
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

I have installed and re-installed it ....still thesame error

**Comment by Jangojack14** [comment]
Same Here

**Comment by rtanx** [comment]
> # OS - Parrot OS
> python zeus.py --version
> v1.5.2.21b875(revision)
> seems this is your first time running the applicatIon, doing setup ple
> seems this is your first time running the applicatiOn, doing setup ple
> [05:49:18 CRITICAL] your current firefox version is not supported by Zeus
> 
> [*] shutting down at 05:49:18..
> 
> Exception in thread Thread-1 (most likely raised during interpreter shutdown):
> Traceback (most recent call last):
> File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
> File "/usr/lib/python2.7/threading.py", line 754, in run
> File "/home/user/Desktop/zeus-scanner/bin/unzip_gecko.py", line 28, in animation
> <type 'exceptions.TypeError'>: 'NoneType' object is not callable
> 
> I have installed and re-installed it ....still thesame error

YESSS, sameeeee, i use firefox 69.0 on Kubuntu

**Comment by Ekultek** [comment]
https://github.com/Ekultek/Zeus-Scanner/blob/master/bin/unzip_gecko.py#L109

**Comment by lav13enrose** [comment]
use version 58, as it supported on zeus. Reading the readme wont hurt you btw
