### ISSUE TITLE
ConnectionError: HTTPSConnectionPool(host='www.aol.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb3d6b66c>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#83]
Zeus version:
`1.0.39`

Error info:
```Traceback (most recent call last):
  File "zeus.py", line 531, in <module>
    agent=agent_to_use
  File "/home/bush911/Desktop/Zeus-Scanner/var/google_search/search.py", line 275, in parse_search_results
    req = requests.get(query_url, proxies=proxy_string)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='www.aol.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb3d6b66c>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
````

Running details:
`Linux-4.12.0-parrot6-686-pae-i686-with-Parrot-3.8-JollyRoger`

Commands used:
`zeus.py --dork-list=/home/bush911/Desktop/d0rks.txt --blackwidow=URL http://notebase.net/29216-video_98.html , -A --sqlmap-args=SQLMAP-ARGS sqlmaap`

Log file info:
```2017-10-12 23:26:57,170;zeus-log;INFO;log file being saved to '/home/bush911/Desktop/Zeus-Scanner/log/zeus-log-52.log'...
2017-10-12 23:26:57,170;zeus-log;WARNING;AOL will take a little longer due to pop-ups...
2017-10-12 23:26:57,170;zeus-log;INFO;specified to use non-default search engine...
2017-10-12 23:26:57,174;zeus-log;INFO;starting dork scan with query '.asp?cid='...
2017-10-12 23:26:57,175;zeus-log;INFO;attempting to gather query URL...
2017-10-12 23:26:57,323;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-12 23:26:57,324;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-12 23:27:09,401;zeus-log;INFO;browser will open shortly...
2017-10-12 23:27:59,760;zeus-log;INFO;searching 'http://aol.com' using query '.asp?cid='...
2017-10-12 23:28:03,635;zeus-log;INFO;closing the browser and continuing process..
2017-10-12 23:28:03,726;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-12 23:28:03,726;zeus-log;INFO;no proxy configuration detected...
2017-10-12 23:28:06,825;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.39)::Python->v2.7'...
2017-10-12 23:28:06,978;zeus-log;INFO;found a total of 184 URL's with a GET parameter...
2017-10-12 23:28:06,979;zeus-log;INFO;successfully wrote found items to '/home/bush911/Desktop/Zeus-Scanner/log/url-log/url-log-14.log'...
2017-10-12 23:28:06,980;zeus-log;INFO;starting dork scan with query '.php?id='...
2017-10-12 23:28:06,980;zeus-log;INFO;attempting to gather query URL...
2017-10-12 23:28:07,127;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-12 23:28:07,128;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-12 23:28:21,853;zeus-log;INFO;browser will open shortly...
2017-10-12 23:28:52,149;zeus-log;INFO;searching 'http://aol.com' using query '.php?id='...
2017-10-12 23:28:56,278;zeus-log;INFO;closing the browser and continuing process..
2017-10-12 23:28:56,370;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-12 23:28:56,370;zeus-log;INFO;no proxy configuration detected...
2017-10-12 23:28:57,753;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.39)::Python->v2.7'...
2017-10-12 23:28:57,759;zeus-log;INFO;found a total of 5 URL's with a GET parameter...
2017-10-12 23:28:57,760;zeus-log;INFO;successfully wrote found items to '/home/bush911/Desktop/Zeus-Scanner/log/url-log/url-log-15.log'...
2017-10-12 23:28:57,761;zeus-log;INFO;starting dork scan with query '.php?pid='...
2017-10-12 23:28:57,761;zeus-log;INFO;attempting to gather query URL...
2017-10-12 23:28:57,919;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-12 23:28:57,919;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-12 23:29:11,901;zeus-log;INFO;browser will open shortly...
2017-10-12 23:29:54,067;zeus-log;INFO;searching 'http://aol.com' using query '.php?pid='...
2017-10-12 23:29:58,206;zeus-log;INFO;closing the browser and continuing process..
2017-10-12 23:29:58,316;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-12 23:29:58,316;zeus-log;INFO;no proxy configuration detected...
2017-10-12 23:29:59,729;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.39)::Python->v2.7'...
2017-10-12 23:29:59,753;zeus-log;INFO;found a total of 5 URL's with a GET parameter...
2017-10-12 23:29:59,755;zeus-log;INFO;successfully wrote found items to '/home/bush911/Desktop/Zeus-Scanner/log/url-log/url-log-16.log'...
2017-10-12 23:29:59,756;zeus-log;INFO;starting dork scan with query 'lang_englishlang_main_album.php?phpbb_root_path='...
2017-10-12 23:29:59,760;zeus-log;INFO;attempting to gather query URL...
2017-10-12 23:29:59,914;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-12 23:29:59,914;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-12 23:30:15,332;zeus-log;INFO;browser will open shortly...
2017-10-12 23:30:57,886;zeus-log;INFO;searching 'http://aol.com' using query 'lang_englishlang_main_album.php?phpbb_root_path='...
2017-10-12 23:31:02,500;zeus-log;INFO;closing the browser and continuing process..
2017-10-12 23:31:02,600;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-12 23:31:02,600;zeus-log;INFO;no proxy configuration detected...
2017-10-12 23:31:08,150;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.39)::Python->v2.7'...
2017-10-12 23:31:08,267;zeus-log;INFO;found a total of 184 URL's with a GET parameter...
2017-10-12 23:31:08,268;zeus-log;INFO;successfully wrote found items to '/home/bush911/Desktop/Zeus-Scanner/log/url-log/url-log-17.log'...
2017-10-12 23:31:08,269;zeus-log;INFO;starting dork scan with query 's_in_area.asp?area_id='...
2017-10-12 23:31:08,269;zeus-log;INFO;attempting to gather query URL...
2017-10-12 23:31:08,422;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-12 23:31:08,423;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-12 23:31:22,777;zeus-log;INFO;browser will open shortly...
2017-10-12 23:32:05,375;zeus-log;INFO;searching 'http://aol.com' using query 's_in_area.asp?area_id='...
2017-10-12 23:32:10,108;zeus-log;INFO;closing the browser and continuing process..
2017-10-12 23:32:10,204;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-12 23:32:10,205;zeus-log;INFO;no proxy configuration detected...
2017-10-12 23:32:12,593;zeus-log;INFO;adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.39)::Python->v2.7'...
2017-10-12 23:32:12,600;zeus-log;INFO;found a total of 5 URL's with a GET parameter...
2017-10-12 23:32:12,601;zeus-log;INFO;successfully wrote found items to '/home/bush911/Desktop/Zeus-Scanner/log/url-log/url-log-18.log'...
2017-10-12 23:32:12,602;zeus-log;INFO;starting dork scan with query 's_in_area.php?area_id='...
2017-10-12 23:32:12,602;zeus-log;INFO;attempting to gather query URL...
2017-10-12 23:32:12,749;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-12 23:32:12,749;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-12 23:32:27,582;zeus-log;INFO;browser will open shortly...
2017-10-12 23:34:41,441;zeus-log;INFO;searching 'http://aol.com' using query 's_in_area.php?area_id='...
2017-10-12 23:34:45,743;zeus-log;INFO;closing the browser and continuing process..
2017-10-12 23:34:45,834;zeus-log;INFO;URL successfully gathered, searching for GET parameters...
2017-10-12 23:34:45,834;zeus-log;INFO;no proxy configuration detected...
2017-10-12 23:35:12,486;zeus-log;ERROR;[7;31;31mran into exception 'HTTPSConnectionPool(host='www.aol.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb3d6b66c>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))'...
Traceback (most recent call last):
  File "zeus.py", line 531, in <module>
    agent=agent_to_use
  File "/home/bush911/Desktop/Zeus-Scanner/var/google_search/search.py", line 275, in parse_search_results
    req = requests.get(query_url, proxies=proxy_string)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='www.aol.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb3d6b66c>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

2017-10-12 23:43:11,221;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-12 23:43:11,228;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-12 23:43:11,289;zeus-log;INFO;[32mextracting traceback from log file...[0m
```

**Comment by Ekultek** [comment]
Couple of possibilities here. Since you obviously don't know how to use this tool read what I said on #81, if you keep making issues like this I'll just close them as invalid.

Possible issue:

 - Your proxy, VPN, whatever that you're using is failing
 - You have to many connections with the web browser run `ps aux | grep firefox` and close the ones opened by `root`

**Comment by Ekultek** [comment]
On second though I should probably catch this error

**Comment by Ekultek** [comment]
Added a catch for this  b380c6e
