### ISSUE TITLE
(d9b451cd)', your unique identifier for this issue is 'd9b451cd'

### ISSUE THREAD

**Issue by sherif-yahya** [Ekultek/Zeus-Scanner#847]
kali linux

issue has been created successfully with the following name 'Unhandled exception (d9b451cd)', your unique identifier for this issue is 'd9b451cd' and the URL to your issue is 'None'

**Comment by sherif-yahya** [comment]
[*] starting up at 22:18:29..


[22:18:29 INFO] log file being saved to '/root/zeus-scanner/log/zeus-log-24.log'
[22:18:29 INFO] using default search engine
[22:18:29 INFO] starting dork scan with query 'inurl:php?id='
[22:18:29 WARNING] will not parse webcache URL's (to parse webcache pass -W)
[22:18:29 WARNING] only pulling URLs with GET(query) parameters (to pull all URL's pass -E)
[22:18:29 INFO] attempting to gather query URL
[22:18:29 INFO] setting up virtual display to hide the browser
[22:18:29 INFO] setting the browser
[22:18:31 ERROR] selenium_search.pyc failed to gather the URL from search engine, caught exception 'Message: Failed to start browser /usr/bin/firefox: other os error' exception has been logged to current log file                                                                                           
Traceback (most recent call last):
  File "/root/zeus-scanner/var/search/selenium_search.py", line 268, in parse_search_results
    tor=tor, batch=batch, xforward=forward_for
  File "/root/zeus-scanner/var/search/selenium_search.py", line 82, in get_urls
    browser = var.search.SetBrowser(agent=user_agent, proxy=proxy, tor=tor, xforward=xforward).set_browser()
  File "/root/zeus-scanner/var/search/__init__.py", line 148, in set_browser
    executable_path=whichcraft.which("geckodriver"))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
SessionNotCreatedException: Message: Failed to start browser /usr/bin/firefox: other os error

[22:18:31 PROMPT] would you like to create an anonymous issue and post it to Zeus's Github[y/N]: y
[22:18:48 INFO] Zeus got an unexpected error and will automatically create an issue for this error, please wait                                                                                           
[22:18:48 INFO] getting authorization
[22:18:48 INFO] extracting traceback from log file
[22:18:48 INFO] attempting to get firefox browser version
[22:18:48 ERROR] failed to run firefox
[22:18:49 INFO] issue has been created successfully with the following name 'Unhandled exception (d9b451cd)', your unique identifier for this issue is 'd9b451cd' and the URL to your issue is 'None'
