### ISSUE TITLE
WebDriverException: Message: Expected [object Undefined] undefined to be a string

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#85]
Zeus version:
`1.0.42.49ab`

Error info:
```Traceback (most recent call last):
  File "/home/carlos/WEB/Zeus-Scanner/var/google_search/search.py", line 233, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/home/carlos/WEB/Zeus-Scanner/var/google_search/search.py", line 137, in get_urls
    search.send_keys(query)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 350, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 499, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Expected [object Undefined] undefined to be a string
````

Running details:
`Linux-4.10.0-35-generic-x86_64-with-Ubuntu-17.04-zesty`

Commands used:
`zeus.py -r -b sii.ittg.edu.mx -s -p -i -a -x`

Log file info:
```2017-10-12 21:14:52,368;zeus-log;INFO;log file being saved to '/home/carlos/WEB/Zeus-Scanner/log/zeus-log-4.log'...
2017-10-12 21:14:52,368;zeus-log;INFO;using default search engine...
2017-10-12 21:14:52,402;zeus-log;INFO;using random dork 'template.php?where=' as the search query...
2017-10-12 21:14:52,403;zeus-log;INFO;attempting to gather query URL...
2017-10-12 21:14:52,661;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-12 21:14:52,661;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-12 21:15:06,348;zeus-log;INFO;browser will open shortly...
2017-10-12 21:15:08,746;zeus-log;INFO;searching 'http://google.com' using query 'template.php?where='...
2017-10-12 21:15:08,752;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception 'Message: Expected [object Undefined] undefined to be a string' exception has been logged to current log file...
Traceback (most recent call last):
  File "/home/carlos/WEB/Zeus-Scanner/var/google_search/search.py", line 233, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/home/carlos/WEB/Zeus-Scanner/var/google_search/search.py", line 137, in get_urls
    search.send_keys(query)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 350, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 499, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Expected [object Undefined] undefined to be a string


2017-10-12 21:15:46,746;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-12 21:15:46,747;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-12 21:15:46,828;zeus-log;INFO;[32mextracting traceback from log file...[0m
```

**Comment by Ekultek** [comment]
Researching, give me some time

**Comment by Ekultek** [comment]
Good reference https://stackoverflow.com/questions/43175013/selenium-firefox-dev-edition-send-keys-throwing-object-undefined-exception

**Comment by Ekultek** [comment]
Update to the newest version and try again:

```
baal@baal-Aspire-5733Z:~/bin/python/zeus-scanner$ sudo python zeus.py -r -b sii.ittg.edu.mx -s -p -i -a -x

    __          __________                             __   
   / /          \____    /____  __ __  ______          \ \  
  / /    ______   /     // __ \|  |  \/  ___/  ______   \ \ 
  \ \   /_____/  /     /\  ___/|  |  /\___ \  /_____/   / / 
   \_\          /_______ \___  >____//____  >          /_/  
                       \/   \/           \/  v1.0.44.f2a0(revision)
	https://github.com/ekultek/zeus-scanner.git
		Advanced Dork Searching...


[*] starting up at 10:16:02..


[10:16:02 INFO] log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-79.log'...
[10:16:02 INFO] using default search engine...
[10:16:02 INFO] using random dork 'sitio.php?read=' as the search query...
[10:16:02 INFO] attempting to gather query URL...
[10:16:02 INFO] firefox browser display will be hidden while it performs the query...
[10:16:02 WARNING] your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
[10:16:11 INFO] browser will open shortly...
[10:16:13 INFO] searching 'http://google.com' using query 'sitio.php?read='...
[10:16:17 INFO] closing the browser and continuing process..
[10:16:17 INFO] URL successfully gathered, searching for GET parameters...
[10:16:17 INFO] no proxy configuration detected...
[10:16:18 INFO] adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.44.f2a0)::Python->v2.7'...
[10:16:18 INFO] received webcache URL, extracting URL from webcache...
[10:16:18 INFO] received webcache URL, extracting URL from webcache...
[10:16:18 INFO] received webcache URL, extracting URL from webcache...
[10:16:18 INFO] received webcache URL, extracting URL from webcache...
[10:16:18 INFO] received webcache URL, extracting URL from webcache...
[10:16:18 INFO] received webcache URL, extracting URL from webcache...
[10:16:18 INFO] received webcache URL, extracting URL from webcache...
[10:16:18 INFO] received webcache URL, extracting URL from webcache...
[10:16:18 INFO] received webcache URL, extracting URL from webcache...
[10:16:18 INFO] received webcache URL, extracting URL from webcache...
[10:16:18 INFO] found a total of 12 URL's with a GET parameter...
[10:16:18 INFO] successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/url-log/url-log-20.log'...
[10:16:18 ERROR] it appears that you have enabled multiple attack types, as of now only 1 attack is supported at a time, choose your attack and try again. You can use the -f flag if you do not want to complete an entire search again...


[*] shutting down at 10:16:18..


baal@baal-Aspire-5733Z:~/bin/python/zeus-scanner$ 
```
