### ISSUE TITLE
NoSuchElementException: Message: Unable to locate element: [name="q"]

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#86]
Zeus version:
`1.0.39`

Error info:
```Traceback (most recent call last):
  File "/home/bush911/Desktop/Zeus-Scanner/var/google_search/search.py", line 248, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/home/bush911/Desktop/Zeus-Scanner/var/google_search/search.py", line 130, in get_urls
    search = browser.find_element_by_name('q')
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 426, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 832, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: [name="q"]
````

Running details:
`Linux-4.12.0-parrot6-686-pae-i686-with-Parrot-3.8-JollyRoger`

Commands used:
`zeus.py --dork-list=/home/bush911/Desktop/d0rks.txt --blackwidow=http://notebase.net/29216-video_98.html , -A --sqlmap-args=SQLMAP-ARGS sqlmaap`

Log file info:
```2017-10-13 05:17:27,647;zeus-log;INFO;log file being saved to '/home/bush911/Desktop/Zeus-Scanner/log/zeus-log-83.log'...
2017-10-13 05:17:27,648;zeus-log;WARNING;AOL will take a little longer due to pop-ups...
2017-10-13 05:17:27,648;zeus-log;INFO;specified to use non-default search engine...
2017-10-13 05:17:27,652;zeus-log;INFO;starting dork scan with query '.asp?cid='...
2017-10-13 05:17:27,652;zeus-log;INFO;attempting to gather query URL...
2017-10-13 05:17:27,792;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-13 05:17:27,793;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-13 05:17:44,677;zeus-log;INFO;browser will open shortly...
2017-10-13 05:18:13,239;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception 'Message: Unable to locate element: [name="q"]' exception has been logged to current log file...
Traceback (most recent call last):
  File "/home/bush911/Desktop/Zeus-Scanner/var/google_search/search.py", line 248, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/home/bush911/Desktop/Zeus-Scanner/var/google_search/search.py", line 130, in get_urls
    search = browser.find_element_by_name('q')
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 426, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 832, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: [name="q"]


2017-10-13 08:13:30,165;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-13 08:13:30,180;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-13 08:13:30,224;zeus-log;INFO;[32mextracting traceback from log file...[0m
```

**Comment by Ekultek** [comment]
Firstly bro you’re still using some weird ass arguments. It makes me wonder if you edited the code yourself. So if those arguments are there in the next issue you make ill assume you’ve been editing the code and close the issue as invalid.

This error means that the search button element “q” was not found

**Comment by Ekultek** [comment]
You need to update:

```
baal@baal-Aspire-5733Z:~/bin/python/zeus-scanner$ sudo python zeus.py --dork-list=/home/baal/Desktop/d0rks.txt --blackwidow=http://notebase.net/29216-video_98.html , -A --sqlmap-args=SQLMAP-ARGS sqlmaap

    __          __________                             __   
   / /          \____    /____  __ __  ______          \ \  
  / /    ______   /     // __ \|  |  \/  ___/  ______   \ \ 
  \ \   /_____/  /     /\  ___/|  |  /\___ \  /_____/   / / 
   \_\          /_______ \___  >____//____  >          /_/  
                       \/   \/           \/  v1.0.44.f2a0(revision)
	https://github.com/ekultek/zeus-scanner.git
		Advanced Dork Searching...


[*] starting up at 10:12:51..


[10:12:51 INFO] log file being saved to '/home/baal/bin/python/zeus-scanner/log/zeus-log-78.log'...
[10:12:51 WARNING] AOL will take a little longer due to pop-ups...
[10:12:51 INFO] specified to use non-default search engine...
[10:12:51 INFO] starting dork scan with query 'inurl:php?id=10'...
[10:12:51 INFO] attempting to gather query URL...
[10:12:51 INFO] firefox browser display will be hidden while it performs the query...
[10:12:51 WARNING] your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
[10:13:00 INFO] browser will open shortly...
[10:13:12 INFO] searching 'http://aol.com' using query 'inurl:php?id=10'...
[10:13:16 INFO] closing the browser and continuing process..
[10:13:16 INFO] URL successfully gathered, searching for GET parameters...
[10:13:16 INFO] no proxy configuration detected...
[10:13:16 INFO] adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.44.f2a0)::Python->v2.7'...
[10:13:16 INFO] found a total of 6 URL's with a GET parameter...
[10:13:16 INFO] successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/url-log/url-log-18.log'...
[10:13:16 INFO] starting dork scan with query 'inurl:manage?*='...
[10:13:16 INFO] attempting to gather query URL...
[10:13:17 INFO] firefox browser display will be hidden while it performs the query...
[10:13:17 WARNING] your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
[10:13:29 INFO] browser will open shortly...
[10:13:40 INFO] searching 'http://aol.com' using query 'inurl:manage?*='...
[10:13:44 INFO] closing the browser and continuing process..
[10:13:44 INFO] URL successfully gathered, searching for GET parameters...
[10:13:44 INFO] no proxy configuration detected...
[10:13:44 INFO] adjusting user-agent header to default user agent 'Zeus-Scanner(v1.0.44.f2a0)::Python->v2.7'...
[10:13:44 INFO] found a total of 6 URL's with a GET parameter...
[10:13:44 INFO] successfully wrote found items to '/home/baal/bin/python/zeus-scanner/log/url-log/url-log-19.log'...


[*] shutting down at 10:13:44..


baal@baal-Aspire-5733Z:~/bin/python/zeus-scanner$ 
```
