### ISSUE TITLE
WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 101

### ISSUE THREAD

**Issue by ZeusIssueReporter** [Ekultek/Zeus-Scanner#94]
Zeus version:
`1.0.44.f2a0`

Firefox version:
`failed to start`

Error info:
```Traceback (most recent call last):
  File "/opt/Zeus-Scanner/var/google_search/search.py", line 242, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/opt/Zeus-Scanner/var/google_search/search.py", line 129, in get_urls
    browser = webdriver.Firefox(profile, proxy=proxy_to_use)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 96, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    % (self.path, return_code)
WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 101
````

Running details:
`Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-14.04-trusty`

Commands used:
`zeus.py -d inurl.php?id=`

Log file info:
```2017-10-13 17:25:49,599;zeus-log;INFO;log file being saved to '/opt/Zeus-Scanner/log/zeus-log-7.log'...
2017-10-13 17:25:49,603;zeus-log;INFO;using default search engine...
2017-10-13 17:25:49,604;zeus-log;INFO;starting dork scan with query 'inurl.php?id='...
2017-10-13 17:25:49,606;zeus-log;INFO;attempting to gather query URL...
2017-10-13 17:25:49,911;zeus-log;INFO;firefox browser display will be hidden while it performs the query...
2017-10-13 17:25:49,913;zeus-log;WARNING;your web browser will be automated in order for Zeus to successfully bypass captchas and API calls. this is done in order to grab the URL from the search and parse the results. please give selenium time to finish it's task...
2017-10-13 17:25:51,940;zeus-log;ERROR;[7;31;31msearch.pyc failed to gather the URL from search engine, caught exception 'Message: Service geckodriver unexpectedly exited. Status code was: 101' exception has been logged to current log file...
Traceback (most recent call last):
  File "/opt/Zeus-Scanner/var/google_search/search.py", line 242, in parse_search_results
    query_url = get_urls(query, url_to_search, verbose=verbose, user_agent=user_agent, proxy=proxy_string)
  File "/opt/Zeus-Scanner/var/google_search/search.py", line 129, in get_urls
    browser = webdriver.Firefox(profile, proxy=proxy_to_use)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 96, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    % (self.path, return_code)
WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 101


2017-10-13 17:25:53,544;zeus-log;INFO;[32mZeus got an unexpected error and will automatically create an issue for this error, please wait...[0m
2017-10-13 17:25:53,545;zeus-log;INFO;[32mgetting authorization...[0m
2017-10-13 17:25:53,548;zeus-log;INFO;[32mextracting traceback from log file...[0m
2017-10-13 17:25:53,568;zeus-log;ERROR;[7;31;31mfailed to run forefox...[0m
```

**Comment by Ekultek** [comment]
What does it say in your `geckodriver.log` file? This usually happens from either:

 - Your firefox is not compatible
 - Your driver is not compatible

For some prerequisites that you need see [here](https://stackoverflow.com/questions/39312903/running-webdriver-with-firefox-python?answertab=votes#tab-top)

Also it seems that you are running the powershell for ubuntu given `Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-14.04-trusty` (or ubuntu on Windows). Try it with the terminal.

**Comment by Ekultek** [comment]
Caught the exception via 24cdc14. It's up to you if you want to update firefox or not.
